# Name of your blog (this will show up at the top of your page and in the RSS feed)
title: Anand Deopurkar

# Short description (goes below the title; it will also be used in the RSS feed)
description: 

# Your name, as you want it to appear underneath each post and in the footer
author: Anand Deopurkar

# Your email if you want it to be linked on the contact page
author_email: deopurkar@uga.edu

# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
#baseurl: /path/to/blog 
baseurl: 

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: http://deopurkar.github.io
encoding: UTF-8

#### Under the Hood Stuff #####

markdown: kramdown

# Makes pretty (descriptive) permalinks. See Jekyll docs for alternatives.
permalink: pretty

# Build settings
sass:
  sass_dir: _sass
kramdown:
  input: GFM

# Repository
repository: deopurkar/deopurkar.github.io

defaults:
  - 
    scope: 
      path: ""
    values:
      robots: true

# Compression
compress_html:
    clippings: all
    blanklines: true
    