# Created 2026-05-08 Fri 12:01
:PROPERTIES:
:ID:       d0fccab1-f7d2-415d-83bf-847772c6112c
:END:
#+options: broken-links:warn toc:1 ':t ":t num:0
#+title: 2026 Algebra 2
#+author: Anand Deopurkar
#+filetags: teaching
#+latex_class: article
#+latex_header: \usepackage[margin=1cm]{geometry} \usepackage[charter, cal=cmcal]{mathdesign} \usepackage{environ} \usepackage{multicol} \usepackage{mathabx} \renewcommand{\square}{\fbox{\phantom{x}}}
#+property: header-args:sage :eval no-export
#+bind: org-html-postamble nil
#+bind: org-html-preamble nil

* Algebra 2
[[Course information][The general course information is here.]]  Below is a week-by-week rundown of the course.  
** Week 9
- Homework (due 8 May) :: 
     Please submit your solution to one of the following problems.

  1. Exercise 16.3.2 (b) and (c)

  2. Let \(\alpha_1, \alpha_2, \alpha_3, \alpha_4\) be the four complex roots of the irreducible polynomial
     \(x^4-4x+2 \in \mathbf{Q}[x]\).
     Find the minimal polynomial of \(\alpha_1\alpha_2+\alpha_3\alpha_4\) over \(\mathbf{Q}\).

     For this problem, you may need to rewrite symmetric functions in terms of elementary symmetric functions.  Feel free to use a computer to do this.  In your write-up, you may assert the resulting equality and say that you found it using a computer.

  3. Let \(F \subset K\) be a finite extension of fields.  Prove that there exists a finite extension \(K \subset L\) such that \(F \subset L\) is a splitting field (of some polynomial in \(F[x]\)).  (Slogan: every finite extension can be enlarged to a splitting field.)

     For simplicity, you may assume that the characteristic is zero.  But the statement is true in all characteristics.

     Do not assume that \(F\) and \(K\) are subfields of the complex numbers!

- Workshop :: [[file:workshops/workshop08.pdf][Workshop 8]]

- Reading (to be done by 11 May) :: 16.6, 16.7
- Tips :: 
     This section contains the statements of the major theorems of Galois theory.
     Your first goal should be to understand these statements.

     Take an example: \(F = \mathbf{Q}\) and \(K = \mathbf{Q}[2^{1/3}, \zeta_3]\).
  1. Prove that this a Galois extension.  Can you prove it in different ways?
  2. What does Lemma 16.6.2 say for this extension?
  3. What does Lemma 16.6.3 say for this extension?
  4. Are the proerties in Theorem 16.6.4 evident here?  Are some less evident than others?
  5. Can you explain the action mentioned in Theorem 16.6.6 in this example?
  6. Can you write down the correspondence asserted in Theorem 16.7.1 in this example?
  7. Do you see Theorem 16.7.5 in this example?

  The proofs in this section are by combining proposition/lemmas that have already appeared.
  There is nothing that is significantly new.
  Try to work out the proofs yourselves as much as possible.
** Week 10
- Homework (due 15 May) :: 
     Please submit your solution to one of the following problems.  In each problem, you may assume the results of the previous ones.

     Let \(p\) be a prime number and let \(\zeta = e^{2\pi i /p}\).

  1. Let \(F = \mathbf{Q}[\zeta]\).
     Let \(K\) be the splitting field of \(x^p-2\) over \(F\).
     Describe all elements of \(\operatorname{Aut}(K/F)\).
     Describe a group isomorphism  \(\mathbf{Z}/p \mathbf{Z} \to \operatorname{Aut}(K/F)\).

  2. Let \(K\) be the splitting field of \(x^p-2\) over \(\mathbf{Q}\).
     Let \(G\) be the group of invertible upper triangular matrices of the form
     \[ \begin{pmatrix} 1 & b \\ & c\end{pmatrix},\]
     where \(b,c \in \mathbf{Z}/p \mathbf{Z}\) and \(c \neq 0\).
     Construct an isomorphism \(G \to \operatorname{Aut}_{\mathbf{Q}}(K)\).
     What is the pre-image of \(\operatorname{Aut}_F(K)\) under this isomorphism?

  3. For each \(j \in \mathbf{Z}/ p \mathbf{Z}\), we have the intermediate subfield \(\mathbf{Q} \subset \mathbf{Q}(2^{1/p} \zeta^j) \subset K\).
     Describe the corresponding subgroup of \(G\) in terms of matrices.

  4. (Challenge)
     Prove the following two (equivalent) statements.
     1. \(G\) has exactly \(p\) subgroups of index \(p\).
     2. \(K\) has exactly \(p\) subfields of degree \(p\) over \(\mathbf{Q}\).
- Workshop :: [[file:workshops/workshop09.pdf][Workshop 9]]
- Reading (to be done by 18 May) :: 16.8, 16.9, 16.10
- Tips for reading :: 
     There are no major results here.
     Everything is a further illustration of the main theorem of Galois theory.
     But it is no less important---it helps us understand and appreciate the main theorem.

  - [Theorem 16.8.5] Try to prove the theorem yourself.
  - [Examples 16.9.2] I find these more confusing than illuminating.
    Feel free to skip them.
  - [Proposition 16.9.5/6] If you understood the cubic, then there is nothing new here.
  - [Proposition 16.9.8] Again, the proof of this is not much harder than that of Proposition 16.9.5/6.
    But this proposition is usable only we can write down the resolvent cubic.
    This is possible, in principle, because the coefficients of the resolvent cubic are symmetric expressions in the roots of the original quartic.
    You can try to find it yourself or ask the internet.
  - [Proposition 16.10.2] We have seen examples of this in class already, so hopefully there is nothing surprising here.
    It is worth going through a moderately complicated example.
    Try reading the \(p = 17\) example in Artin or work out a smaller example by yourself.
  - [Theorem 16.10.12] Proving this in general is optional.  Do it if you find it enjoyable.  Otherwise, feel free to give it a pass.
** Previous weeks
*** Week 8
- Workshop :: [[file:workshops/workshop07.pdf][Workshop 7]] ([[file:workshops/Workshop_7_solutions.pdf][solutions thanks to Seetha]])

- Homework (due 1 May) :: 
     Please submit your solution to one of the following problems.
     In your solution to a problem, you may use the result of the previous problems.

  1. Let \(p\) be a prime number.
     Find the degree of the field extension \(\mathbf{Q} \subset \mathbf{Q}[\zeta_p, 2^{1/p}]\).

  2. Prove that we have an isomorphism
     \[ \mathbf{Q}[x,y]/(x^{p-1} + \dots + 1, y^p-2) \to \mathbf{Q}[\zeta_p, 2^{1/p}] \]
     that sends \(x\) to \(\zeta_p\) and \(y\) to \(2^{1/p}\).

  3. Let \(K = \mathbf{Q}[\zeta_p, 2^{1/p}]\).
     Using the presentation of \(K\) above, describe all elements of \(\operatorname{Aut}_{\mathbf{Q}}(K)\).

  4. (Do not submit this one) What kind of group is \(G = \operatorname{Aut}_{\mathbf{Q}}(K)\)?  Try various compositions and convince yourselves that it is not abelian.  What is the subgroup of automorphisms that fix \(2^{1/p}\)?  What is the subgroup of automorphisms that fix \(\zeta_p\)?

- Reading (to be done by 4 May) :: 16.4, 16.5

- Questions to think about :: 
  1. Give examples and non-examples of Galois extensions of \(\mathbf{Q}\).
  2. [Lemma 16.4.2] Try proving this by yourself.  We have seen all the ingredients.
  3. [Theorem 16.4.2] Remember that all fields in this section onwards are of characteristic 0.
     Where in the proof of Theorem 16.5.2 did we use the characteristic 0 assumption?
  4. Let \(K = \mathbf{C}(t)\) and let \(H = \mathbf{Z}/2 \mathbf{Z}\) act on \(K\) so that the generator sends \(t\) to \(-t\).  What is \(K^{H}\)?  What is the minimal polynomial of \(t\) over \(K^{H}\)?
  5. [Example 16.5.5] What if you drop \(\tau\) and only consider the action by \(\sigma\).
     Then we have an action of \(H = \mathbf{Z}/4 \mathbf{Z}\) (very similar to the previous problem).
     What is the fixed field?
*** Week 7
- Reading (to be done by 29 April) :: 16.1, 16.2, 16.3
- Questions to think about :: 
  1. [Definition of symmetric polynomials]
     - Construct some symmetric polynomials in \(\mathbf{Z}[x,y]\) and some non-symmetric ones.
     - In \(\mathbf{Z}[x,y,z]\), construct a polynomial
       - whose orbit has size 2 under \(S_3\)
       - whose orbit has size 3 under \(S_3\)
  2. [Symmetric functions theorem] Write \(x^3+y^3\) as a polynomial in \(x+y\) and \(xy\).
  3. [Symmetric functions theorem]
     This is how we will use this theorem most often.
     Let \(\alpha, \beta\) be two roots of \(x^2 + x + 3\).
     Find the value of \(\alpha^3 + \beta^3\) (without using a computer; use the previous exercise).
  4. [The discriminant]
     Search online for an expression of the discriminant of higher degree polynomials in terms of their coefficients.
  5. [Splitting theorem]
     Is \(\mathbf{Q} \subset \mathbf{Q}[2^{1/3}]\) a splitting field (of some polynomial)?  Why/why not?
     If not, construct a splitting field that contains \(\mathbf{Q}[2^{1/3}]\).
- Workshop :: 
     [[file:workshops/workshop06.pdf][Workshop 6]] ([[file:workshops/workshop06_solutions.pdf][solutions thanks to Seetha]])
- Homework (due 24 April) :: 
     Please submit your solution to one of the following problems.

  1. Exercise 15.10.1.  Recall that an algebraic number in \(\mathbf{C}\) is one that is algebraic over \(\mathbf{Q}\).

  2. Exercise 15.M.3.  For simplicity, feel free to assume that \(F \subset K \subset \mathbf{C}\).

     Let us make this question a bit more precise.
     What are the possible degrees of the irreducible factors of \(f\) in \(K[x]\)?
     That is, for each \(d \in \{1,\cdots, 6\}\), determine whether \(d\) is possible as a degree of an irreducible factor of \(f \in K[x]\).
     If you say that a degree \(d\) is possible, please give an example of an \(F\), a \(K\), and an \(f\) such that \(f \in K[x]\) has an irreducible factor of degree \(d\).
     If you say that a degree \(d\) is not possible, please explain why.

     We can ask for a refinement of this question (but you do not have to do this).
     The factorisation of \(f \in K[x]\) gives a partition of 6.
     For example, if \(f\) factors into two linear factors and two quadratic factors, we have the partition \(6 = 1 + 1 + 2 + 2\).
     What are the possible partitions of 6?
*** Week 6
- Workshop :: 
     [[file:workshops/workshop05.pdf][Workshop 5]] ([[file:workshops/workshop05_solutions.pdf][solutions thanks to Seetha]])
- Homework (due 7 Apr) :: 
Please submit your solution to one of the following problems.

1. Let \(m,n\) be integers. 
   Choose complex square roots \(\sqrt m\) and \(\sqrt n\) of \(m\) and \(n\), respectively.
   Consider the unique ring homomorphism \(\phi \colon \mathbf{Q}[x,y]/(x^2-m, y^2-n) \to \mathbf{Q}[\sqrt m, \sqrt n]\) that sends \(x\) to \(\sqrt m\) and \(y\) to \(\sqrt n\).
   For which \(m\) and \(n\) is \(\phi\) an isomorphism?

2. Determine the number of irreducible polynomials of degree \(6\) over \(\mathbf{F}_p\).
   (As a warm-up, you may want to do degrees \(2\), \(3\), \(5\), and \(4\)).

3. Exercise 15.7.8.

[[Assignment 5][The solution sketches are here.]]   
*** Week 5
- Workshop :: 
     [[file:workshops/workshop04.pdf][Workshop 4]] ([[file:workshops/workshop04_solutions.pdf][solutions thanks to Seetha]])
- Homework (due 27 Mar) :: 
     Please submit your solution to one of the following problems.
  1. Exercise 15.3.5
  2. For a complex number \(z\), we use \(\sqrt {z}\) to denote one of the two square roots of \(z\) (will not matter which one). 
     Given \(m, n \in \mathbf{Q}\), when is there an isomorphism of fields \(\mathbf{Q}[\sqrt m] \to \mathbf{Q}[\sqrt n]\)?
     If there is one isomorphism, are the any others?  How many?
  3. Exercise 15.3.2.

  [[Assignment 4][The solution sketches are here.]]     
- Reading (to be done by 30 Mar) :: 15.8, 15.10
- Questions to think about :: 
  1. [Proof of 15.8.1]
     Recall why the roots of an irreducible polynomial are distinct in characteristic 0?
     Can you construct an example where this fails in positive characteristic?
  2. [Proof of 15.8.1]
     For which values of \(c\) is \(\sqrt 2 + c \sqrt 3\) a primitive element of \(\mathbf{Q}[\sqrt 2, \sqrt 3]\)?
  3. [Theorem 15.10.1]
     What does the fundamental theorem of algebra say about the maximal ideals of \(\mathbf{C}[x]\)?

     There is a generalisation of the fundamental theorem of algebra to multivariate polynomial rings, called Hilbert's Nullstellensatz.
     It says that every maximal ideal of \(\mathbf{C}[x_1,\dots, x_n]\) is of the form \((x_1-a_1, \cdots, x_n-a_n)\) for some \(a_1, \dots, a_n \in \mathbf{C}\).
*** Week 4
- Homework (due 20 Mar) :: 
     Please submit your solution to one of the following problems.
  1. (Adapted from  Exercise 12.5.9)
     Let \(\omega = e^{2\pi i /3} \in \mathbf{C}\) and \(R = \mathbf{Z}[\omega] \subset \mathbf{C}\).
     Let \(p \in \mathbf{Z}\) be a prime number.
     Prove that the following are equivalent:
     1. \(p\) is a prime element of \(R\),
     2. \((p)\) is a maximal ideal of \(R\),
     3. the polynomial \(x^2+x+1\) has no zeros in \(\mathbf{Z}/p \mathbf{Z}\).

  2. Exercise 15.2.1

  3. Exercise 15.2.3

  [[Assignment 3][The solution sketches are here.]]

- Workshop :: [[file:workshops/workshop03.pdf][Workshop 3]] ([[file:workshops/workshop03_solutions.pdf][solutions]] thanks to Seetha)

- Reading (to be done by 23 Mar) :: 15.6, 15.7

- Questions to think about :: 
  1. [Lemma 15.6.2] What happens if \(f\) is reducible?
  2. [Proposition 15.6.4]
     Is the following stronger analogue of (e) true: if \(f(x)\) and \(g(x)\) have a common root in \(K\), then they have a common root in \(F\)?
  3. [Theorem 15.7.3]
     Make a diagram of fields of order \(3^n\) for \(n = 1, ..., 12\).
     In the diagram, draw a dot for every field and an arrow for every inclusion.
  4. [Theorem 15.7.3]
     Construct a field of order \(\mathbf{F}_{125}\).
  5. [Equation 15.7.8 and Lemma 15.7.11]
     Can you write the 16 elements of \(\mathbf{F}_{16}\) explicitly as in Equation 15.7.8 and describe how addition and multiplication works?
     In your list, what are the elements that satisfy \(x^4 = x\)?
     Do you see that they form a subfield of order 4?
*** Week 3
- Workshop :: [[file:workshops/workshop02.pdf][Workshop 2]]
- Homework (due 13 Mar) :: 
     Please submit your solution to one of the following problems.
  1. Exercise 12.3.1
  2. Try to prove or disprove the general statement: The kernel of any homomorphism \(\mathbf{Z}[x] \to \mathbf{C}\) is a principal ideal.
  3. Exercise 12.4.9
  4. Exercise 12.4.15

  [[Assignment 2][The solution sketches are here.]]     
- Reading (to be done by 17 Mar) :: 15.3, 15.4, 15.5
- Questions to think about :: 
  1. [Definition of degree]
     Write a basis of \(\mathbf{Q}[2^{1/3}]\) as a \(\mathbf{Q}\)-vector space.
  2. [Proposition 15.3.3]
     Where does the proof fail in characteristic 2?
  3. [Corollary 15.3.8]
     Consider \(K = \mathbf{Q}[\sqrt 2, \sqrt 3]\).
     What can you say about its degree over \(\mathbf{Q}\)?
     What will you need to prove to prove that its degree over \(\mathbf{Q}\) is 4?
  4. [Examples 15.4.1, 15.4.4]
     Convince yourselves that \(\mathbf{Q}[\sqrt 2 + \sqrt 3] = \mathbf{Q}[\sqrt 2, \sqrt 3]\).
  5. [Lemma 15.4.2]
     Are the \(d_1d_2\) monomials \(\alpha^i\beta^j\) always linearly independent?
     Construct an example where they are not.
  6. [Lemma 15.5.8]
     "This polynomial is irreducible over \(\mathbf{Q}\) because it has no integer root."
     Unpack this.
*** Week 2
- Workshop :: [[ws01][Workshop 1]]
- Homework (due 6 Mar) :: 
     Please submit your solution to one of the following problems.
  1. Exercise 12.2.4
  2. Exercise 12.2.6 (clearly state the size function)
  3. Division with remainder allows us to generalise Euclid's algorithm to find the gcd.
     Use it to find the gcd of \(3+i\) and \(5\) in \(\mathbf{Z}[i]\).

  [[Assignment 1][The solution sketches are here.]]   

- Reading (to be done by 10 Mar) :: 12.5, 15.1, 15.2

- Questions to think about :: 
  1. [Theorem 12.5.2]
     Write down Gauss primes of absolute value up to 5.

  2. [Diagram 12.5.4]
     Spend time really understanding this diagram.
     Convince yourself that this is just the last isomorphism stated in the Correspondence Theorem (Theorem 11.4.3), sometimes called the "third isomorphism theorem" for quotients.

  3. [Diagram 12.5.4]
     What can you say about the ring \(\overline R\) for \(p = 3\)? For \(p = 5\)?

  4. [Section 15.1]
     Convince yourself that \(\mathbf{Z}[i]/3\) is a finite field.
     How many elements does it have?
     What is the multiplicative inverse of 2? Of \(1+i\)?

  5. [Proposition 15.2.3]
     What is the minimal polynomial of \(\sqrt 2\) over \(\mathbf{Q}\)?

  6. [Proposition 15.2.3]
     Let \(\alpha = e^{i\pi/4}\).
     What is the minimal polynomial of \(\alpha\) over \(\mathbf{Q}\)? Over \(\mathbf{Q}[i]\)?

  7. [Proposition 15.2.6]
     1. What is "the canonical map \(F[x]/(f) \to F[\alpha]\)"?
     2. Is \(\mathbf{Q}[\pi] = \mathbf{Q}(\pi)\)?
     3. How does the analogue of Proposition 15.2.6 work with more variables?
     For example, what is the kernel of the map
     \[ \mathbf{Q}[x,y,z] \to \mathbf{Q}[\sqrt 2, \sqrt 3, \sqrt 6]\]
     that sends \(x\) to \(\sqrt 2\) and \(y\) to \(\sqrt 3\) and \(z\) to \(\sqrt 6\)?

  8. [Propositions 15.2.8]
     1. Is there an isomorphism from \(\mathbf{Q}[\sqrt 2]\) to \(\mathbf{Q}[1 + \sqrt 2]\)?
     2. Write down two extensions of \(\mathbf{Q}\) of degree 2 that are not isomorphic.
        How do you know they are not isomorphic?
*** Week 1
- Reading (to be done by 2 Mar) :: 12.2 continued, 12.3, 12.4 (skip the subsection "Estimating the coefficients")
- Questions to think about :: 
  1. [Proposition 12.2.9] Using this proposition, find the maximal ideals of \(\mathbf{Z}\)? \(\mathbf{Q}[x]\).

  2. [Lemma 12.2.10] Last time, you found another \(\mathbf{Z}[\sqrt{-d}]\) for which unique factorisation fails. In this ring, find an irreducible element that is not prime.

  3. [Proposition 12.2.13] Given an example of an integral domain that contains an infinite strictly increasing chain of principal ideals.

  4. [Theorem 12.2.17] Find the gcd of \(x\) and \(y\) in \(\mathbf{Q}[x,y]\).
     Can it be written as a linear combination of \(x\) and \(y\)?

  5. [Theorem 12.2.17] Given \(f, g\), how do we actually find \(d\), \(r\), and \(s\)?
     Where does this process go wrong in \(\mathbf{Z}[x]\)?

  6. [Just before Proposition 12.2.19]  Why does \(\mathbf{R}[x]\) not have irreducible polynomials of degree \(> 2\)?

  7. [Eq 12.3.1]
     1. Convince yourself that \(\psi_p\) is a ring homomorphism (what do you need to check)?
     2. Review the definition of the kernel.
     3. True or false: we have an isomorphism \(\mathbf{Z}[x]/(p) \to \mathbf{F}_p[x]\)?

  8. [Theorem 12.3.6] Find a counter-example to (a) if \(f_0\) is not primitive.
     What can you say about the converse (b)?

  9. [Theorem 12.3.8] Let \(f(x) \in \mathbf{Z}[x]\).
     How does the prime factorisation of \(f(x)\) in \(\mathbf{Z}[x]\) compare with the prime factorisation of \(f(x)\) in \(\mathbf{Q}[x]\)?

  10. [Theorem 12.3.10] How does 12.3.10 follow from what we have done?

  11. [Eq 12.4.4]
      Find the irreducible polynomials of small degrees in \(\mathbf{F}_3[x]\) (until you get bored).
      Use them to write a few irreducible polynomials of small degree in \(\mathbf{Z}[x]\).
      Are these polynomials also irreducible in \(\mathbf{Q}[x]\)?

  12. [Theorem 12.4.9] Is \(x^{n-1}+ \cdots + 1\) irreducible also for composite \(n\)?
      Do some experiments on a computer.
**** Week 0
- Reading (to be done by 25 Feb) :: [[A review of rings][A review of rings]], /Artin/ 12.1 and 12.2, up to 12.2.8
- Questions to think about :: 
  1. [Section 12.1] Although Artin says that the proofs will be reviewed later "in a more general setting," can you supply them in this setting?

  2. [Section 12.2] Prove the equivalence of the statements in Eq 12.2.1 and Eq 12.2.2.

  3. [Eq 12.2.3] How do you see that \(2, 3, 1 + \sqrt{-5}, 1-\sqrt{-5}\) cannot be factored further in \(\mathbf{Z}[\sqrt{-5}]\)?

  4. [Eq 12.2.3] Find one more example of a ring of the form \(\mathbf{Z}[\sqrt{-d}]\) where unique factorisation fails.

  5. [Proposition 12.2.5] Explain why there could be "as many as 4 choices" for division with remainder in \(\mathbf{Z}[i]\).

  6. [Proposition 12.2.8]  Does this proposition say that there always exists a \(d\) such that \(\langle d \rangle = \langle a, b\rangle\)? 
     Find an example of \(a\) and \(b\) in \(\mathbf{Z}[\sqrt{-5}]\) for which there is no such \(d\).  How do you know that there is no such \(d\)?

  7. [Proposition 12.2.8] Let \(R\) be an integral domain and \(a, b \in R\).
     True or false?
     1. If the ideal \((a,b)\) is principal and generated by \(d\), then \(d\) is the gcd of \(a\) and \(b\).
     2. If \(d\) is the gcd of \(a\) and \(b\), then the ideal \((a,b)\) is principal and generated by \(d\).
** Midsemester exam
The midterm exam will be in class in week 7 on Wednesday.  It will cover everything we have done in weeks 1--6.  To prepare, make sure you can do all the homework questions, the workshop questions, and the questions that accompany the reading.  In addition, [[file:midterm_practice.pdf][here are some more practice questions]].  Here is [[file:2023-midterm.pdf][the midterm exam from a couple of years ago.]]  A good way to use it is as a mock exam---take it without referring to any notes or the book in 2 hours and see how you do.
** References and resources
*** On writing mathematics
1. [[file:Conrad.pdf][Keith Conrad]]
2. [[file:Houston.pdf][Kevin Houston]]
3. [[file:Kleiman.pdf][Steve Kleiman]]
4. [[file:Poonen.pdf][Bjorn Poonen]]
* Course information
- Contacts :: 
  - Lecturer and convener :: 
       Anand Deopurkar <anand.deopurkar@anu.edu.au>\\
       Office hours: Wednesday 2pm to 3:30pm in Hanna Neumann 4.56

  - Demonstrator :: 
       Seethalakshmi Kayanattath <seethalakshmi.kayanattath@anu.edu.au>\\
       Office hours: Tuesdays 3pm to 3:3pm in Marie Ray 3.02 and Wednesdays 1pm to 1:30pm in Hanna Neumann 1.57

  - Class representatives :: 
       Xinheng Gong <u8298388@anu.edu.au>

- Textbook :: /Algebra/ (2nd edition) by Michael Artin (Chapters 12, 15, 16).

- Assessment :: 
     | Final exam           | 40 |
     | Midterm exam         | 30 |
     | In-class quizzes     | 20 |
     | Reflective check-ins |  5 |
     | Homework             |  5 |

     The MATH6215 students will, in addition, do a mini-project and give a short oral presentation.  It will count for 5% of the marks; the quizzes will count 5% less.

- Weekly workload :: 
  - Reading :: I will assign roughly 10 pages to read from Artin.  I expect you to read actively--by constantly asking questions, working out examples, and trying to foresee.  I will give some questions to think about while you read; doing so will help you read more actively.
  - Reflective check-in :: By noon on Monday, you will do a reflective check-in on canvas.  It will consist of one question: What part of the reading you found most difficult?  As long as you submit a response, you will get credit (no right or wrong answers).
  - Lectorials and workshops :: The lectorials on Monday and Wednesday and the workshop on Tuesday will be about the assigned reading from the week before.  We will focus on the parts that you found the most difficult.
  - Homework :: There is no other way of learning mathematics than by doing it.  The weekly homework is your chance to do the maths.  It is /essential/ that you do the homework.  By Friday, you will write-up and submit /one homework problem/ of your choice.  As long as your submission reflects a reasonable effort, you will get full credit (/even if your submission has mistakes/).  We will grade it and return it to you with feedback.

       In the past, a good way to emphasise the importance of homework was to ask for you to submit your solutions, and have the submissions count for a significant percentage of the final marks.  With easy availability of solutions on the internet and the rise of synthetic text generators, it has become easy to produce solutions without solving the problems.  So marking submissions has lost its main purpose.

       Homework also serves as a vehicle for feedback.  This is still the case.
       I encourage you to write up and submit the problem you are most unsure about---the problem on which feedback will be the most useful.  As long as you submit a solution in good faith, you receive full credit; it does not have to be perfect.

       Despite having no explicit benefit in terms of marks, solving the homework problems will be directly beneficial for the quizzes (in the immediate future); for the exams (in the intermediate future); and for your learning (in the long run).

  - Quizzes :: The quizzes will be in-class on Monday (at the beginning of the class) starting in week 3.  Out of 10 quizzes, I will only count the top 5.  In exceptional cases (if you have an unavoidable conflict on Monday), I will excuse you from the quizzes and re-distribute the 20% marks to the exams.
* A review of rings
** The ring of integers
Let \(R\) be a ring (always assumed to be associative, commutative, and with a multiplicative identity).

Remember that ring homomorphisms are required to send the additive identity to the additive identity and the multiplicative identity to the multiplicative identity.
As a result, there is a unique ring homomorphism \(\mathbf{Z} \to R\); call it \(i\).
Using this unique homomorphism, we can interpret every integer as an element of \(R\).
For example, by \(2 \in R\), we mean the image of \(2\) under the homomorphism \(i\).
Caution: it may happen that two distinct integers represent the same element in \(R\).
*** Questions
1. Find rings \(R\) such that the homomorphism \(\mathbf{Z} \to R\) is
   - surjective
   - injective
   - injective but not surjective
   - surjective but not injective
   - neither surjective nor injective

2. In cases where the homomorphism is not injective, what is the kernel?
** Ideals and quotient rings
An ideal \(I \subset R\) is a subset that is closed under addition and multiplication by elements of \(R\).
That is, if \(a, b \in I\) then \(a+b \in I\) and if \(a \in I\) then \(ra \in I\) for all \(r \in R\).
Given a ring homomorphism \(\phi \colon R \to S\), the kernel of \(\phi\) is an ideal.

Given elements \(a_1, \dots, a_n \in R\), the notation \(\langle a_1, \dots, a_n \rangle\) represents the smallest ideal of \(R\) that contains \(a_1, \dots, a_n\).  This is the set of elements of \(R\) that can be expressed as
\[ r_1a_1 + \cdots + r_na_n\]
for some \(r_1, \dots, r_n \in R\).
The simplest case of this construction is \(n = 1\).
In this case, the ideal \(\langle a \rangle\) is called a /principal ideal/.

Given an ideal \(I \subset R\), we can form a new ring \(R/I\) together with a ring homomorphism \(R \to R/I\).
To do so, we consider the equivalence relation on \(R\) given by \(a \sim b\) if \(a-b \in I\).
The elements of \(R/I\) are the equivalence classes under this relation; we call them equivalence classes "modulo \(I\)".
The homomorphism \(R \to R/I\) sends an element to its equivalence class.
*** Questions
1. Let \(R\) be the ring of continuous \(\mathbf{R}\)-valued functions on \(\mathbf{R}\).
   Give examples of a few ideals of \(R\).

2. Recall the definition of a /prime ideal/ and a /maximal ideal/.
   Which of your examples are prime ideals? 
   Which are maximal?

3. Let \(I \subset R\) be the subset of functions \(f\) such that \(f(0) = 0\).
   Is \(I\) an ideal?  Is it a prime ideal?  Is it a maximal ideal?  Is it a principal ideal?

4. What are the units in \(R\)?
** Polynomial rings
Let \(R\) be a ring and \(x\) a symbol.
The /polynomial ring \(R[x]\)/ is the set of symbolic expressions
\[ r_0 + r_1 x + \cdots + r_n x^n,\]
where \(r_i \in R\) and \(r_n \neq 0\).
The \(r_i\) are called the /coefficients/ of the expression and the \(n\) is called the /degree/.
We add the symbolic expressions coefficient-wise and multiply them by the usual rule.
We have an injective ring homomorphism \(R \to R[x]\) given by \(r \mapsto r\), considered as a polynomial of degree 0.
Via this homomorphism, we often think of \(R\) as a subring of \(R[x]\).

*Key property of the polynomial ring*: Let \(\phi \colon R \to S\) be a ring homomorphism, and let \(s \in S\) be any element.  Then the rule
\[ r_0 + \cdots + r_n x^n \mapsto \phi(r_0) + \cdots + \phi(r_n) s^n\]
defines a homomorphism \(R[x] \to S\).
This homomorphism sends \(x\) to \(s\), and is the only homomorphism that agrees with \(\phi\) on \(R \subset R[x]\) and sends \(x\) to \(s\).

The construction above with one symbol \(x\) can also be done with more than one symbols, leading to multivariable polynomial rings like \(R[x,y]\), \(R[x,y,z]\), and so on.
*** Questions
1. How many ring homomorphisms are there from \(\mathbf{Z}[x]\) to \(\mathbf{Z}/3 \mathbf{Z}\)?
2. Choose one of the homomorphisms and find its kernel.
3. True or false: if \(R\) is an integral domain, then \(R[x]\) is also an integral domain.
4. Is \(R[x]\) ever a field?
* Assignments
** Assignment 1
Please submit your solution to one of the following problems.

1. Exercise 12.2.4
2. Exercise 12.2.6 (clearly state the size function)
3. Division with remainder allows us to generalise Euclid's algorithm to find the gcd.
   Use it to find the gcd of \(3+i\) and \(5\) in \(\mathbf{Z}[i]\).
*** Solution sketches
1. It is generally advised to avoid proof by contradiction (see https://cohn.mit.edu/contradiction/), so let us do that.

   We prove that given a finite set \(S\) of monic irreducible polynomials in \(F[x]\), there exists a monic irreducible polynomial \(p(x)\) that is not in \(S\).  Then it follows that the set of monic irreducible polynomials is infinite.

   If \(S\) is empty, take \(p(x) = x\).  [Many of you forgot this edge case.]

   Otherwise, write \(S = \{p_1(x),\dots, p_n(x)\}\).
   Let \(f(x) = p_1(x) \cdots p_n(x) + 1\).
   Then \(f(x)\) is of positive degree and monic.
   Since \(f(x)\) is of positive degree, it is not a unit.
   So it has a monic irreducible factor , say \(p(x)\).
   None of the \(p_i(x)\) divide \(f(x)\), so \(p(x)\) is different from the \(p_i(x)\).

   There are a few facts here that we are using about the polynomial ring that may not be true in general, and which can make this argument fail.
   For example, we need that \(f(x)\) is not a unit (for which we use the degree).
   We also use that every non-unit has an irreducible factor. 
   For one variable polynomials, there are many ways to see this; but this fact is not always true.

2. For both, the size function is the complex norm squared. 
   You have to check that this is integer valued by an explicit calculation.
   Having done this, the key point is that every complex number is at a distance of \(< 1\) from at least one of the points in our ring.
   [Ideally, you should be able to prove this rigorously, but if you draw a picture and clearly state what you are using about the picture, I am willing to grant it.]   
   Then, given \(a,b \in R\) with \(b \neq 0\), we let \(q \in R\) be a point such that \(|q-a/b| < 1\) and \(r = a-bq\).

3. In any ring \(R\), we have the equality of ideals \(\langle a,b \rangle = \langle a-bq,b\rangle\) for any \(q \in R\) (do you see why?).

   Suppose \(R\) is a Euclidean domain with a size function \(\sigma\).
   Let \(I = \langle a, b \rangle\).
   Suppose \(b \neq 0\) and \(\sigma(a) \geq \sigma(b)\), we choose \(q\) such that either \(a-bq = 0\) or \(\sigma(a-bq) < \sigma(b)\).  If the former holds, then \(b\) generates \(I\), and hence is our gcd.  If the latter holds, we continue the process with \((b,a-bq)\) in place of \((a,b)\).  The process must terminate because the size of the second argument strictly decreases at each stage.

   Executing the procedure above for \(\mathbf{Z}[i]\) with \(\sigma(a+ib) = a^2+b^2\) gives
   \[ \langle 5, 3+i \rangle = \langle 3+i, 2-i \rangle = \langle 2-i \rangle.\]
    So \(2-i\) is a gcd.
** Assignment 2
Please submit your solution to one of the following problems.
1. Exercise 12.3.1
2. Try to prove or disprove the general statement: The kernel of any homomorphism \(\mathbf{Z}[x] \to \mathbf{C}\) is a principal ideal.
3. Exercise 12.4.9
4. Exercise 12.4.15
*** Solution sketches
1. The key is to find a primitive irreducible polynomial in \(\mathbf{Z}[x]\) satisfied by \(\alpha\).  This polynomial generates the kernel (see below).

2. Suppose \(\phi \colon \mathbf{Z}[x] \to \mathbf{C}\) sends \(x\) to \(\alpha\).
   Extend \(\phi\) to a homomorphism \(\widetilde \phi \colon \mathbf{Q}[x] \to \mathbf{C}\) that sends \(\mathbf{Q} \to \mathbf{C}\) as usual and that sends \(x\) to \(\alpha\).
   Concretely, \(\widetilde \phi\) sends \(f(x) \in \mathbf{Q}[x]\) to \(f(\alpha)\).

   Since \(\mathbf{Q}[x]\) is a PID, \(\ker \widetilde \phi\) is principal. 
   Let \(f(x)\) be a generator.
   If \(f(x) = 0\), then \(\ker \phi = 0\), which is principal.
   Otherwise, choose \(f(x) \in \mathbf{Z}[x]\) to be primitive.

   We claim that \(\ker\phi = \langle f \rangle\).
   Since \(f \in \ker \phi\), we have \((f) \subset \ker \phi\).
   For the reverse equality, suppose \(g \in \ker \phi\).
   Then \(g \in \ker \widetilde \phi\), and so \(g = f h\) for some \(h \in \mathbf{Q}[x]\).
   Since \(f\) is primitive, Gauss's lemma implies that \(h \in \mathbf{Z}[x]\).
   So \(g \in (f)\).

   The key point here is that we could extend the homomorphism from \(\mathbf{Z}[x]\) to \(\mathbf{Q}[x]\) and use \(\mathbf{Q}[x]\) as an intermediary.  In some cases, this may not be possible (for example, if the target is \(\mathbf{F}_p\) instead of \(\mathbf{C}\)).

3. This question is a direct application of Eisenstein's criterion.

4. Suppose \(f = g h\) is a factorisation of \(f\) in \(\mathbf{Z}[x]\) with non-constant \(g\) and \(h\).
   1. If \(\overline f\) is a constant, then both \(\overline g\) and \(\overline h\) must be constant. 
      So all their terms except the constant term, are divisible by \(p\).
   2. If \(\overline f = x^n + b x^{n-1}\), where \(n = \deg f\) and \(b \neq 0 \in \mathbf{F}_p\), then \(\overline g = x^k\) and \(\overline h = x^{n-k}(x+b)\), up to constant multiples, for some \(k \in \{1, \cdots, n\}\).
      That is, except for one, all the terms of \(g\) must be divisible by \(p\), and likewise, except for two consecutive terms, all the terms of \(h\) must be divisible by \(p\).
** Assignment 3
Please submit your solution to one of the following problems.

1. (Adapted from  Exercise 12.5.9)
   Let \(\omega = e^{2\pi i /3} \in \mathbf{C}\) and \(R = \mathbf{Z}[\omega] \subset \mathbf{C}\).
   Let \(p \in \mathbf{Z}\) be a prime number.
   Prove that the following are equivalent:
   1. \(p\) is a prime element of \(R\),
   2. \((p)\) is a maximal ideal of \(R\),
   3. the polynomial \(x^2+x+1\) has no zeros in \(\mathbf{Z}/p \mathbf{Z}\).

2. Exercise 15.2.1

3. Exercise 15.2.3
*** Solution sketches

1. 
   Many of you used that since \(R\) is a PID, \(p\) is prime if and only if \(p\) is irreducible, and \(p\) is irreducible if and only if \((p)\) is maximal.
   This is correct, but the conclusion actually holds more generally than just \(\mathbf{Z}[\omega]\) (for example, also for \(\mathbf{Z}[\sqrt{-5}]\), so I will also give the general argument.

   The first key point is that we have a surjection \(\mathbf{Z}[x] \to \mathbf{Z}[\omega]\) that sends \(x\) to \(\omega\).
   The polynomial \(x^2+x+1\) is in the kernel.
   We claim that this polynomial generates the kernel.
   Let \(f(x) \in \mathbf{Z}[x]\) be in the kernel.  Then \(f(\omega) = 0\).
   Consider the homomorphism \(\mathbf{Q}[x] \to \mathbf{Q}[\omega]\) that sends \(x\) to \(\omega\).
   Since \(x^2+x+1 \in \mathbf{Q}[x]\) is irreducible, it generates the kernel of this homomorphism.
   As a result, \(f(x) = (x^2+x+1)g(x)\) for some \(g(x) \in \mathbf{Q}[x]\).
   Gauss's lemma implies that \(g(x) \in \mathbf{Z}[x]\).

   You cannot say "minimal polynomial" and deduce that \((x^2+x+1)\) is the kernel in \(\mathbf{Z}[x]\).  The notion of minimal polynomial is only defined over a field, not over \(\mathbf{Z}\).

   By the first isomorphism theorem, we have an isomorphism \(\mathbf{Z}[x]/(x^2+x+1) \to \mathbf{Z}[\omega]\).
   Then, \((p) \subset \mathbf{Z}[x]/(x^2+x+1)\) is prime if and only if \(\mathbf{Z}[x]/(x^2+x+1,p)\) is an integral domain and it is maximal if and only if \(\mathbf{Z}[x]/(x^2+x+1,p)\) is a field.  But \(\mathbf{Z}[x]/(x^2+x+1,p) = \mathbf{F}_p[x]/(x^2+x+1)\) is an integral domain if and only if it is a field and that is if and only if \(x^2+x+1 \subset \mathbf{F}_p[x]\) is irreducible.
   Finally, since \(x^2+x+1\) has degree 2, it is irreducible if and only if it has no linear factors, which is if and only if it has no roots in \(\mathbf{F}_p\).

2. The question is equivalent to: In \(\mathbf{Q}[x]/(x^3-3x+4)\), why does \(x^2+x+1\) have a multiplicative inverse, and how does on find it?

   One way is to simply write
   \[ (a + b x + cx^2) \cdot (1 + x + x^2) = 1 \pmod {x^3-3x+4},\]
   and solve the resulting linear equations.
   This certainly does it, but it does not explain why a solution must exist.

   Alternatively, note that \(\gcd(x^2+x+1, x^3-3x+4) = 1\) in \(\mathbf{Q}[x]\).
   So the ideal generated by \(x^2+x+1\) and \(x^3-3x+4\) is \((1)\).
   As a result, we can write
   \[ 1 = (x^2+x+1) a(x) + (x^3-3x+4)b(x).\]
   Then \(a(x)\) is the inverse of \(x^2+x+1\) modulo \(x^3-3x+4\).

   One way to to find the \(a(x)\) and \(b(x)\) in practise is to run Euclid's algorithm to find the gcd and back-substitute.  If someone knows a better way, please let us know!

3. Since \(2^{1/3}\) and \(2^{1/3}\omega\) have the same minimal polynomial over \(\mathbf{Q}\), namely \(x^3-2\), we have an isomorphism
   \[ \phi \colon \mathbf{Q}[2^{1/3}\omega] \to \mathbf{Q}[2^{1/3}]\]
   that sends \(2^{1/3}\omega\) to \(2^{1/3}\).

   Applying \(\phi\) to a solution of \(\sum x_i^2 = -1\) in \(\mathbf{Q}[2^{1/3}\omega]\) gives a solution of the same equation in \(\mathbf{Q}[2^{1/3}]\).
   But the latter is a subfield of \(\mathbf{R}\), and since a sum of squares cannot be negative, we cannot have a solution.

   The key point here is that \(\mathbf{Q}[2^{1/3}\omega]\) and \(\mathbf{Q}[2^{1/3}]\) are isomorphic.
   So, as far as algebraic properties are concerned, there cannot be a difference between them. 
   But there may be "extra-algebraic" properties that may be present in one case but not the other (like positivity), and we may be able to use them to deduce algebraic consequences.

   When I was learning this material, my study group considered invoking any extra-algebraic arguments as cheating.  But now I think that's foolish.  I am a firm believer in the unity of mathematics!
** Assignment 4
Please submit your solution to one of the following problems.
1. Exercise 15.3.5
2. For a complex number \(z\), we use \(\sqrt {z}\) to denote one of the two square roots of \(z\) (will not matter which one). 
   Given \(m, n \in \mathbf{Q}\), when is there an isomorphism of fields \(\mathbf{Q}[\sqrt m] \to \mathbf{Q}[\sqrt n]\)?
   If there is one isomorphism, are the any others?  How many?
3. Exercise 15.3.2.
*** Solution sketches
1. We prove that \(f(x) = x^4+3x+3\) is irreducible over \(\mathbf{Q}[2^{1/3}]\).
   Let \(\alpha \in \mathbf{C}\) be a root of \(f(x)\).
   By Eisenstein's criterion for the prime \(p = 3\), we see that \(f(x)\) is irreducible in \(\mathbf{Q}[x]\).
   So the degree of \(\alpha\) over \(\mathbf{Q}\) is \(4\).

   Consider the extension \(\mathbf{Q} \subset \mathbf{Q}[2^{1/3}, \alpha]\); let its degree by \(d\).
   Since the degree of \(2^{1/3}\) over \(\mathbf{Q}\) is 3, we see that 3 divides \(d\).
   Since the degree of \(\alpha\) over \(\mathbf{Q}\) is 4, we see that 4 divides \(d\).
   So \(12\) divides \(d\), and hence \(d \geq 12\).

   Consider the chain
   \[ \mathbf{Q} \subset \mathbf{Q}[2^{1/3}] \subset \mathbf{Q}[2^{1/3},\alpha].\]
   It follows that the last extension has degree at least 4.
   But \(\alpha\) satisfies the degree 4 polynomial \(f(x) \in \mathbf{Q}[2^{1/3}[x]\).
   So \(f(x)\) must be irreducible in \(\mathbf{Q}[2^{1/3}[x]\).

2. Let us do the case where neither \(\sqrt m\) or \(\sqrt n\) are rational.
   Suppose there is a homomorphism \(\mathbf{Q}[\sqrt m] \to \mathbf{Q}[\sqrt n]\).
   It is easy to check that it must be the identity on \(\mathbf{Q}\).
   Suppose it sends \(\sqrt m\) to \(a + b \sqrt n\), where \(a,b \in \mathbf{Q}\).
   Then \((a+b\sqrt n)^2 = m\).
   By a simple calculation, we conclude that \(a = 0\), and hence \(m = b^2n\).

   Conversely, suppose \(m = b^2n\).
   We claim that there is an isomorphism \(\mathbf{Q}[\sqrt m] \to \mathbf{Q}[\sqrt n]\) that is the identity on \(\mathbf{Q}\) and sends \(\sqrt m\) to \(b \sqrt n\).
   (This needs justification.  You can't decide to send the generators to any elements you want and claim that this defines a homomorphism/isomorphism.)
   There are two ways to justify this.
   One is to recall that there is an isomorphism \(\mathbf{Q}[\alpha] \to \mathbf{Q}[\beta]\) sending \(\alpha\) to \(\beta\) if and only if \(\alpha\) and \(\beta\) have the same minimal polynomial.
   Apply this to \(\alpha = \sqrt m\) and \(\beta = \pm b \sqrt n\).
   Another is to observe that we have an isomorphism \(\mathbf{Q}[x]/(x^2-m) \to \mathbf{Q}[\sqrt m]\) that sends \(x\) to \(\sqrt m\).
   To define a homomorphism \(\mathbf{Q}[x]/(x^2-m) \to \mathbf{Q}[\sqrt n]\), we may choose to send \(x\) to any root of \(x^2-m\) in \(\mathbf{Q}[\sqrt n]\).
   The two roots are \(\pm b \sqrt n\).

3. If \(n\) is prime, then \(x^{n-1}+ \dots + 1\) is the irreducible polynomial of \(\zeta_n\).
   So \(\deg \zeta_n = n-1\).
   So the only \(\zeta_n\) of degree at most 3 and \(n\) prime are for \(n = 2, 3\).

   If \(p\) is a prime factor of \(n\), then \(\zeta_p = \zeta_n^{n/p}\).
   So \(\mathbf{Q}(\zeta_p) \subset \mathbf{Q}(\zeta_n)\).
   It follows that \(p = 2, 3\).

   So the only possible \(n\) are of the form \(2^k 3^l\).

   Now, you argue that \(\deg \zeta_8 = 4\).
   So \(8\) cannot be a factor of \(n\).
   And \(\deg \zeta_9 \geq 6\), so \(9\) cannot be a factor of \(n\).
   (Neither claim is obvious).
   This leaves \(n = 4, 6, 12\).
   The first two actually do give numbers of degree \(2\).
   For the last, we have \(\zeta_4 = i \in \mathbf{Q}(\zeta_{12})\) and \(\zeta_3 = -1/2 + \sqrt 3/2 i \in \mathbf{Q}(\zeta_{12})\), which gives \(\sqrt 3 \in \mathbf{Q}(\zeta_{12})\).
   Therefore, \(\mathbf{Q}[i,\sqrt 3] \subset \mathbf{Q}[\zeta_{12}]\), which implies that \(\zeta_{12}\) has degree at least 4.

   So the only \(n\) are \(\{1,2,3,4,6\}\).
** Assignment 5
Please submit your solution to one of the following problems.

1. Let \(m,n\) be integers. 
   Choose complex square roots \(\sqrt m\) and \(\sqrt n\) of \(m\) and \(n\), respectively.
   Consider the unique ring homomorphism \(\phi \colon \mathbf{Q}[x,y]/(x^2-m, y^2-n) \to \mathbf{Q}[\sqrt m, \sqrt n]\) that sends \(x\) to \(\sqrt m\) and \(y\) to \(\sqrt n\).
   For which \(m\) and \(n\) is \(\phi\) an isomorphism?

2. Determine the number of irreducible polynomials of degree \(6\) over \(\mathbf{F}_p\).
   (As a warm-up, you may want to do degrees \(2\), \(3\), \(5\), and \(4\)).

3. Exercise 15.7.8.
*** Solution sketches

1. It is easy to see that the map is surjective.  When is it an isomorphism?  An efficient way to determine this is when the domain and codomain have the same dimension as a vector space over \(\mathbf{Q}\).  The domain has dimension 4 (do you see why).  The codomain has dimension 4 precisely when it is a degree 4 extension of \(\mathbf{Q}\).  This happens when \(m\) is not a square, \(n\) is not a square, and \(m/n\) is not a square in \(\mathbf{Q}\).

2. Count the number of degree 6 elements in a field of size \(p^6\) and divide by 6.  You have to exclude elements of degree 2, 3, and 1.
   The answer comes out to \((p^6-p^3-p^2+p)/6\).

3. We first find a homomorphism \(K \to L\).  Any homomorphism must be an isomorphism (do you see why).
   To find a homomorphism, we replace the domain by a presentation \(\mathbf{F}_2[x]/(f(x)) \cong K\).

   A homomorphism \(\mathbf{F}_2[x]/(f(x))\) is determined by the image of \(x\), which must be a root of \(f(x)\) in \(L\).
   Conversely, any element of \(L\) that is a root of \(f(x)\) gives a homomorphism \(\mathbf{F}_2[x]/(f(x)) \to L\) that sends \(x\) to that root.

   Since \(f(x) \in \mathbf{F}_2[x]\) is a cubic and \(L\) is a degree 3 extension of \(\mathbf{F}_2\), it has precisely 3 roots in \(L\).
   So there must be 3 homomorphisms.
   I don't know any other way of finding a root other than trial and error.
   The element \(\beta + 1\) turns out to be one root.
   Once we have one root, we can find the others by applying the Frobenius: \(\beta+1 \leadsto \beta^2+1 \leadsto \beta^4+1\).
   (Applying the Frobenius once more gives \(\beta^8+1 = \beta+1\); back to the original.)
** Assignment 6
Please submit your solution to one of the following problems.

1. Exercise 15.10.1.  Recall that an algebraic number in \(\mathbf{C}\) is one that is algebraic over \(\mathbf{Q}\).

2. Exercise 15.M.3.  For simplicity, feel free to assume that \(F \subset K \subset \mathbf{C}\).

   Let us make this question a bit more precise.
   What are the possible degrees of the irreducible factors of \(f\) in \(K[x]\)?
   That is, for each \(d \in \{1,\cdots, 6\}\), determine whether \(d\) is possible as a degree of an irreducible factor of \(f \in K[x]\).
   If you say that a degree \(d\) is possible, please give an example of an \(F\), a \(K\), and an \(f\) such that \(f \in K[x]\) has an irreducible factor of degree \(d\).
   If you say that a degree \(d\) is not possible, please explain why.

   We can ask for a refinement of this question (but you do not have to do this).
   The factorisation of \(f \in K[x]\) gives a partition of 6.
   For example, if \(f\) factors into two linear factors and two quadratic factors, we have the partition \(6 = 1 + 1 + 2 + 2\).
   What are the possible partitions of 6?
** Assignment 7
Please submit your solution to one of the following problems.
In your solution to each problem, you may use the result of the previous problems.

1. Let \(p\) be a prime number.
   Find the degree of the field extension \(\mathbf{Q} \subset \mathbf{Q}[\zeta_p, 2^{1/p}]\).

2. Prove that we have an isomorphism
   \[ \mathbf{Q}[x,y]/(x^{p-1} + \dots + 1, y^p-2) \to \mathbf{Q}[\zeta_p, 2^{1/p}] \]
   that sends \(x\) to \(\zeta_p\) and \(y\) to \(2^{1/p}\).

3. Let \(K = \mathbf{Q}[\zeta_p, 2^{1/p}]\).
   Using the presentation of \(K\) above, describe all elements of \(\operatorname{Aut}_{\mathbf{Q}}(K)\).

4. (Do not submit this one) What kind of group is \(G = \operatorname{Aut}_{\mathbf{Q}}(K)\)?  Try various compositions and convince yourselves that it is not abelian.  What is the subgroup of automorphisms that fix \(2^{1/p}\)?  What is the subgroup of automorphisms that fix \(\zeta_p\)?
** Assignment 8
Please submit your solution to one of the following problems.

1. Exercise 16.3.2 (b) and (c)

2. Let \(\alpha_1, \alpha_2, \alpha_3, \alpha_4\) be the four complex roots of the irreducible polynomial
   \(x^4-4x+2 \in \mathbf{Q}[x]\).
   Find the minimal polynomial of \(\alpha_1\alpha_2+\alpha_3\alpha_4\) over \(\mathbf{Q}\).

   For this problem, you may need to rewrite symmetric functions in terms of elementary symmetric functions.  Feel free to use a computer to do this.  In your write-up, you may assert the resulting equality and say that you found it using a computer.

3. Let \(F \subset K\) be a finite extension of fields.  Prove that there exists a finite extension \(K \subset L\) such that \(F \subset L\) is a splitting field (of some polynomial in \(F[x]\)).  (Slogan: every finite extension can be enlarged to a splitting field.)

   For simplicity, you may assume that the characteristic is zero.  But the statement is true in all characteristics.

   Do not assume that \(F\) and \(K\) are subfields of the complex numbers!
** Assignment 9
Please submit your solution to one of the following problems.
In each problem, you may assume the results of the previous ones.

Let \(p\) be a prime number and let \(\zeta = e^{2\pi i /p}\).

1. Let \(F = \mathbf{Q}[\zeta]\).
   Let \(K\) be the splitting field of \(x^p-2\) over \(F\).
   Describe all elements of \(\operatorname{Aut}(K/F)\).
   Describe a group isomorphism  \(\mathbf{Z}/p \mathbf{Z} \to \operatorname{Aut}(K/F)\).

2. Let \(K\) be the splitting field of \(x^p-2\) over \(\mathbf{Q}\).
   Let \(G\) be the group of invertible upper triangular matrices of the form
   \[ \begin{pmatrix} 1 & b \\ & c\end{pmatrix},\]
   where \(b,c \in \mathbf{Z}/p \mathbf{Z}\) and \(c \neq 0\).
   Construct an isomorphism \(G \to \operatorname{Aut}_{\mathbf{Q}}(K)\).
   What is the pre-image of \(\operatorname{Aut}_F(K)\) under this isomorphism?

3. For each \(j \in \mathbf{Z}/ p \mathbf{Z}\), we have the intermediate subfield \(\mathbf{Q} \subset \mathbf{Q}(2^{1/p} \zeta^j) \subset K\).
   Describe the corresponding subgroup of \(G\) in terms of matrices.

4. (Challenge)
   Prove the following two (equivalent) statements.
   1. \(G\) has exactly \(p\) subgroups of index \(p\).
   2. \(K\) has exactly \(p\) subfields of degree \(p\) over \(\mathbf{Q}\).
** Assignment 10
Please submit your solution to one of the following problems.

TBA.
** Assignment 11
Please submit your solution to one of the following problems.

TBA.
* Workshops
*** Workshop 1
**** Warm-up
1. Recall the definitions of:
   - an irreducible element,
   - a prime element,
   - a gcd of two elements \(a\) and \(b\).
2. Give an example of an irreducible element in a ring \(R\) that is not prime.
3. If \(d\) generates the ideal \(\langle a,b \rangle\), must \(d\) be a gcd of \(a\) and \(b\)?
   Is the converse true?
4. What are the prime ideals of \(\mathbf{Z}\)?
5. Give an example of a UFD that is not a PID.
6. Construct a ring homomorphism \(\mathbf{Z}[x] \to \mathbf{Z}/p \mathbf{Z}[y]\) that sends \(x\) to \(y\).
   How many such homomorphisms are there?
   What do you have to check that the map you defined is a homomorphism?
   How do you prove that there are no more?
**** Factorisation in exotic number rings

Let \(\omega = e^{2\pi i /3}\) and set \(R = \mathbf{Z}[\omega]\).
This is the subset of \(\mathbf{C}\) consisting of numbers of the form \(a + b \omega\), where \(a, b \in \mathbf{Z}\).
The elements of \(R\) are sometimes called /Eisenstein integers/.

1. Check that \(R\) is a sub-ring of \(\mathbf{C}\).

2. What are the units of \(\mathbf{Z}[\omega]\)?

3. Factor \(3\) into irreducibles in \(\mathbf{Z}[\omega]\).
   If you have time, also factor \(7\).
   How do you know that your factors are irreducible?

4. Since \(\mathbf{Z}[\sqrt{-5}]\) is not a UFD, there must exist an irreducible element that is not prime.
   Find one.

5. We have seen that  \(\mathbf{Z}[\sqrt{-5}]\) is not a UFD.
   This means that it cannot be a PID.
   Find an ideal that is not principal.
**** Ideals in polynomial rings


1. Let \(\mathbf{Q}[x] \to \mathbf{C}\) be the unique homomorphism that sends \(x\) to \(\sqrt 2\).
   Why is there a unique homomorphism like this?
   What is its kernel?

2. Let \(\mathbf{Q}[x] \to \mathbf{C}\) be the unique homomorphism that sends \(x\) to \(1/2\).
   What is its kernel?

3. In both questions above, replace \(\mathbf{Q}[x]\) by \(\mathbf{Z}[x]\).
   Must the kernel be principal?  Can you find it in these examples?
**** Factorisation of polynomials
Do this only if you have time.  It uses ideas from the readings this week. 

1. Find the cubic irreducible polynomials in \(\mathbf{F}_2[x]\).
   Use them to write down cubic irreducible polynomials in \(\mathbf{Z}[x]\).

2. Factor \(x^4+2x^3-x^2+2x-1\) in \(\mathbf{F}_2[x]\) and \(\mathbf{F}_3[x]\).
   What does the factorisation imply about the factorisation in \(\mathbf{Z}[x]\).
*** Workshop 2
You must be able to justify (prove) every claim you make, no matter how "trivial" it seems.  If you cannot justify it, please ask me or your demonstrator.  If you can justify it but are not satisfied with the proof (too long, too messy, or something else), please ask.  It is possible that there is a better way, and you will benefit from knowing it.
**** Warm-up

1. True or false?
   1. The element \(x\) is a prime element of \(\mathbf{Q}[x,y]\).
   2. The element \(x\) is an irreducible element of \(\mathbf{Q}[x,y]\).
   3. The element \(2x+1\) is a prime element of \(\mathbf{Z}[x]\).
   4. The element \(2x+1\) is an irreducible element of \(\mathbf{Z}[x]\).

2. Recall the definitions of ring homomorphism, kernel, image, and the first isomorphism theorem.

3. Let \(R = \mathbf{Z}/p \mathbf{Z}\).
   Show that the polynomial \(x^p-x\) evaluates to zero for all \(x \in R\).
   Is \(x^p-x = 0\) in \(R[x]\)?
**** Irreducibility

1. Consider \(z - xy \in \mathbf{C}[x,y,z]\).
   Show that it is irreducible in two ways: 
   1. Identify the quotient \(\mathbf{C}[x,y,z]/(z-xy)\) and conclude that \(z-xy\) is prime.
   2. Show that it is primitive as an element of \(\mathbf{C}[x,y] [z]\) and irreducible in \(\mathbf{C}(x,y)[z]\).

2. Suppose \(f(x) \in \mathbf{Z}[x]\) is irreducible.
   Does this imply that \(f(x) \in \mathbf{Q}[x]\) is also irreducible?
   Is the converse true?

3. Suppose \(f(x) \in \mathbf{Z}[x]\) is irreducible.
   Does this imply that the image of \(f(x)\) in \(\mathbf{Z}/p \mathbf{Z} [x]\) is also irreducible?
   Is the converse true?
   (Be careful!)

4. (Carried over from last week)
   Factor \(x^4+2x^3-x^2+2x-1\) in \(\mathbf{F}_2[x]\) and \(\mathbf{F}_3[x]\).
   What does the factorisation imply about the factorisation in \(\mathbf{Z}[x]\)?
   In \(\mathbf{Q}[x]\)?

5. Fill in the gaps in the following argument.

   \noindent
   *Theorem*. The polynomial \(f(x,y) = y^2-x^3 \in \mathbf{C}[x,y]\) is irreducible.

   \noindent
   /Proof/. It suffices to show that \(f(x,y) \in \mathbf{C}(x)[y]\) is irreducible (why?).
   We may make a change of variables and show that \(g(x,y) = f(x,xy) \in \mathbf{C}(x)[y]\) is irreducible (why?).
   Showing \(g(x,y) = x^2(y^2-x)\) is irreducible in \(\mathbf{C}(x)[y]\) is equivalent to showing \(h(x,y) = y^2-x\) is irreducible in \(\mathbf{C}(x)[y]\) (why?), and this is in turn equivalent to showing that \(y^2-x\) is irreducible in \(\mathbf{C}[x,y]\) (why?).
   But \(y^2-x\) is prime and hence irreducible in \(\mathbf{C}[x,y]\) (why?).

6. Generalise the argument above to prove that if \(\gcd(m,n) = 1\), then \(y^m-x^n \in \mathbf{C}[x,y]\) is irreducible.
*** Workshop 3
You must be able to justify (prove) every claim you make, no matter how "trivial" it seems.  If you cannot justify it, please ask me or your demonstrator.  If you can justify it but are not satisfied with the proof (too long, too messy, or something else), please ask.  It is possible that there is a better way, and you will benefit from knowing it.
**** Warm-up
1. Is \(\mathbf{Z}[i]/(11)\) an integral domain? A field?
2. Find primes \(p \in \mathbf{Z}\) which do and do not remain primes in \(\mathbf{Z}[\sqrt 2]\).
3. Let \(F \subset K\) be fields and \(\alpha \in K\). 
   Recall the definition of the irreducible polynomial (also called /minimal polynomial/) of \(\alpha\) over \(F\).
   Given any \(f(x) \in F[x] \) such that \(f(\alpha) = 0\), how will you find the minimal polynomial?
**** Field extensions and irreducible polynomials

1. Let \(F = \mathbf{Q}[2^{1/6}]\).
   1. Find the kernel of the map \(\mathbf{Q}[x] \to F\) that sends \(x\) to \(2^{1/6}\).
   2. What is the irreducible (= minimal) polynomial of \(2^{1/6}\) over \(\mathbf{Q}\)?
   3. Write a basis of \(F\) as a \(\mathbf{Q}\)-vector space.

2. Let \(L = \mathbf{Q}[\sqrt 2]\) and \(F = \mathbf{Q}[2^{1/6}]\) as above.
   1. Find the kernel of the map \(\mathbf{L}[x] \to F\) that sends \(x\) to \(2^{1/6}\).
   2. What is the irreducible (= minimal) polynomial of \(2^{1/6}\) over \(L\)?
   3. Write a basis of \(F\) as an \(L\)-vector space.

3. Let \(\zeta = e^{2\pi i / 6}\).
   Let \(L = \mathbf{Q}[2^{1/6}\zeta]\) and \(F  = \mathbf{Q}[2^{1/6}]\) as above.
   We consider both as subfields of \(\mathbf{C}\).
   1. Is \(F = L\)?
   2. Is there an isomorphism \(F \to L\)?  Are there multiple isomorphisms?  How many?
   3. Observe that \(K = \mathbf{Q}[\sqrt 2]\) is contained in both \(F\) and \(L\).
      How many isomorphisms \(F \to L\) are \(K\)-isomorphisms?
   4. Find the degrees of \(F\) over \(\mathbf{Q}\); of \(L\) over \(\mathbf{Q}\); of \(F\) over \(K\); and of \(L\) over \(K\).

4. Let \(\alpha, \beta \in \mathbf{C}\) be algebraic over \(\mathbf{Q}\).
   Consider the map \(\mathbf{Q}[x,y] \to \mathbf{C}\) that sends \(x \to \alpha\) and \(y \to \beta\).
   Let \(I \subset \mathbf{Q}[x,y]\) be the kernel of this map.

   1. Let \(f(x) \in \mathbf{Q}[x]\) be the irreducible polynomial of \(\alpha\).
      Show that \(f(x) \in I\).
      Similarly, for the irreducible polynomial \(g(y) \in \mathbf{Q}[y]\), we have \(g(y) \in I\).
      Conclude that \(I\) cannot be principal.

   2. Is \(I\) generated by \(f(x)\) and \(g(y)\)?
      Find examples where it is not.

5. Let \(F \subset K\) be fields and let \(\alpha \in K\) be algebraic over \(F\) with irreducible polynomial \(f(x) \in F[x]\).
   Find a bijection between the following two sets:
   1. \(F\)-homomorphisms \(F[\alpha] \to K\) (ring homomorphisms that restrict to the identity on \(F\))
   2. solutions to \(f(x) = 0\) in \(K\).
*** Workshop 4
**** Warm-up
1. Recall the notion of the degree of a field extension.
2. What are the degrees of the following extensions: \(\mathbf{R} \subset \mathbf{C}\); \(\mathbf{Q} \subset \mathbf{Q}[\zeta_5]\).
3. In each case, write a basis of the bigger field as a vector space over the smaller field.
4. Let \(F\) and \(K\) be fields and let \(\phi \colon F \to K\) be a ring homomorphism.  
   Prove that \(\phi\) must be injective.
   (It is a requirement that in a field, we have \(0 \neq 1\).)
**** Degree of a field extension
1. Let \(\gamma = \sqrt 2 + \sqrt 3\).
   Prove that \(\mathbf{Q}[\gamma] = \mathbf{Q}[\sqrt 2, \sqrt 3]\).
   Call this field \(K\).

2. Prove that \(1, \gamma, \gamma^2, \gamma^3\) and \(1, \sqrt 2, \sqrt 3, \sqrt 6\) are both bases of \(K\) as a \(\mathbf{Q}\)-vector space.
   Write down the change-of-basis matrix.

3. Suppose \(\alpha, \beta \in \mathbf{C}\) have degrees \(m\) and \(n\) over \(\mathbf{Q}\).
   Is the degree of the field extension \(\mathbf{Q} \subset \mathbf{Q}[\alpha,\beta]\)
   1. ... equal to \(mn\)?
   2. ... divisor of \(mn\)?
   3. ... less than or equal to \(mn\)?

   /Hint/: Consider the example \(\alpha = 2^{1/3}\) and \(\beta = 2^{1/3} e^{2\pi i /3}\).

4. Let \(\alpha = 2^{1/3}\) and \(\beta = 2^{1/3}e^{2\pi i/3}\).
   Consider the map \(\phi \colon \mathbf{Q}[x,y] \to \mathbf{Q}[\alpha,\beta]\) that sends \(x\) to \(\alpha\) and \(y\) to \(\beta\).
   Find the kernel of the map.

   \noindent
   /Hint/: First find the degree of \(\mathbf{Q}[\alpha,\beta]\) over \(\mathbf{Q}\).
**** Ruler and compass constructions
Let us prove that an angle whose cosine and sine are transcendental cannot be trisected.

1. Let \(\theta\) be a real number.
   Prove that \(\cos \theta\) is transcendental over \(\mathbf{Q}\) if and only if \(\sin(\theta)\) is transcendental over \(\mathbf{Q}\).

2. Let \(\theta\) be an angle such that \(\cos \theta\) is transcendental over \(\mathbf{Q}\).
   Suppose we are given the points \((0,0), (0,1),\) and \((\cos(\theta), \sin(\theta))\) in the plane.
   Prove that it is impossible to construct \((\cos(\theta/3), \sin(\theta/3))\) using only ruler and compass.

   \noindent
   /Hints/:  Let \(F \subset \mathbf{C}\) be the field \(\mathbf{Q}(\cos(\theta))\).  Construct an isomorphism \(\mathbf{Q}(t) \to F\) (the first one is the field of rational functions in one variable \(t\)).  Prove that the field extension \(F \subset \mathbf{Q}(\cos(\theta/3))\) has degree 3 by explicitly constructing the minimal polynomial for \(\cos(\theta/3)\) over \(F\).  Carefully justify why the polynomial you found is irreducible.
*** Workshop 5
**** Warm-up with finite fields
Let \(K\) be a finite field of size \(q = 7^{12}\).

1. What is the characteristic of \(K\)? What is the degree of the extension \(\mathbf{F}_p \subset K\)?
2. Suppose \(K\) contains a subfield \(F\) of size \(7^m\). 
   Prove that \(m\) must divide 12.

   /Hint/: Consider the extension \(F \subset K\).

3. Conversely, suppose \(m\) divides \(12\).
   Does \(K\) have a subfield of size \(7^m\)?
   How many?
   How do we find them?

4. How many elements of \(K\) have degree 12 over \(\mathbf{F}_p\)?

   This is a bit tricky.  Warm-up by looking at fields of smaller size like \(7^2, 7^3, 7^4,\) and \(7^6\).
**** Finite fields and bit strings
Let \(F = \mathbf{F}_2[a]/(a^4+a+1)\).
Note that \(1, a, a^2, a^3\) is a basis of \(F\) as an \(\mathbf{F}_2\) vector space.
So we can represent every element of \(F\) uniquely as \(b_0 + b_1 a + b_2 a^2 + b_3 a^3\), where \(b_0,\dots, b_3 \in \mathbf{F}_2\).

1. We abbreviate \(b_0 + b_1 a + b_2 a^2 + b_3 a^3\) by the bit-string \(b_0b_1b_2b_3\).
   Then the elements of \(F\) are represented by the 16 strings \(0000,0001,0010,\dots, 1111\).
   Explain the addition law of \(F\) in terms of bit-strings.
2. Describe multiplication by \(a\) in terms of bit-strings.
3. Sometimes, instead of writing the 4 bit-strings, people write the integer they represent in binary notation, for exmaple, writing "14" for the bit-string "1110".
   Then the elements of \(F\) become the more familiar symbols \(0, \cdots, 15\) (for example, \(a^3 + a^2 + a\) will be "14").
   1. Show that this representation conflicts with our convention that the integer symbol \(n\) represents the image of \(n\) under the unique homomorphism from \(\mathbf{Z}\).
   2. Show that this representation respects neither the addition nor the multiplication law.
**** The Frobenius
1. Let \(R\) be any ring of characteristic \(p\).
   Prove that the map \(R \to R\) that raises every element to the \(p\)-th power is a ring homomorphism.
   This homomorphism is called the Frobenius homomorphism.
   On \(\mathbf{F}_p\), what does the Frobenius do?

2. Let \(K\) be a finite field of size \(p^r\).
   Prove that \(\alpha \in K\) lies in \(\mathbf{F}_p \subset K\) if and only if
   \( \operatorname{Frob}(\alpha) = \alpha\).

3. With \(K\) as above, prove that \(\operatorname{Frob}\) applied \(r\) times is the identity on \(K\) and \(r\) is the smallest with this property.

4. With \(K\) as above,  prove that \(\alpha\) and \(\operatorname{Frob}(\alpha)\) have the same minimal polynomial over \(\mathbf{F}_p\).

   In fact, let \(\{\alpha_1, \alpha_2, \dots, \alpha_n\}\) be the orbit of the Frobenius applied to \(\alpha\) (the set of elements that we get if we repeatedly apply \(\operatorname{Frob}\) to \(\alpha\); this set will have at most \(r\) elements, but possibly fewer; in fact, its size will be a factor of \(r\)).
   Show that the minimal polynomial of \(\alpha\) over \(\mathbf{F}_p\) is
   \[ (x-\alpha_1) \cdots (x-\alpha_n).\]
*** Workshop 6
**** Review
Here is a brief list of the main concepts we have seen so far.
If you have any questions about any of them, please ask each other or your demonstrator.

- Factorisation :: 
  1. Euclidean domains, principal ideal domains, unique factorisation domains.
  2. Prime and irreducible elements
  3. Factorisation in \(\mathbf{Z}[x]\) versus \(\mathbf{Q}[x]\), or more generally \(R[x]\) and \((\operatorname{frac} R) [x]\).
  4. Examples of \(\mathbf{Z}[i]\) and \(\mathbf{Z}[\omega]\).
- Fields :: 
  1. Algebraic and transcendental elements; the irreducible/minimal polynomial.
  2. Degree of a field extension; multiplicativity; application to constructions.
  3. Constructing extensions by formally adjoining roots.
  4. Finite fields: existence, uniqueness, containments, isomorphisms, Frobenius.
  5. The primitive element theorem.
**** Field automorphisms
Let \(\alpha_1, \dots, \alpha_4 \in \mathbf{C}\) be the roots of \(x^4-2 = 0\).
Let \(K = \mathbf{Q}[\alpha_1, \dots, \alpha_4]\).

1. Prove that any \(\mathbf{Q}\)-automorphism of \(K\) must permute \(\{\alpha_1, \dots, \alpha_4\}\).
2. Conclude that we have an injective map \(\operatorname{Aut}_{\mathbf{Q}}(K) \to S_4\).
3. What is the image of this map?  That is, which permutations of the roots arise from automorphisms of the field?
   We will defer this question, but let us first observe that the answer is closely tied to /polynomial relations among the roots/.
   Suppose
   \[\alpha_1 = 2^{1/4}, \quad \alpha_2 = 2^{1/4} i, \quad \alpha_3 = -2^{1/4}, \quad \alpha_4 = -2^{1/4}i.\]
   Observe that we have the relation \(\alpha_1 + \alpha_3 = 0\) but not the relation \(\alpha_1 + \alpha_{4} = 0\).
   Conclude that the permutation \((34)\) cannot be in the image.

4. Observe that \(K = \mathbf{Q}[2^{1/4},i]\) and we have a \(\mathbf{Q}\)-isomorphism \(\mathbf{Q}[x,y]/(x^4-2,y^2+1) \to K\) that sends \(x\) to \(2^{1/4}\) and \(y\) to \(i\).
   Use this presentation to enumerate all \(\mathbf{Q}\)-isomorphisms \(K \to K\).

5. Now that you know the elements of \(\operatorname{Aut}_{\mathbf{Q}}(K)\), describe the image of \(\operatorname{Aut}_{\mathbf{Q}}(K) \to S_4\).
*** Workshop 7
**** Symmetric polynomials
1. Write the following polynomials in terms of elementary symmetric polynomials: \(x^2 + y^2\), \(x^3+y^3\), and \(x^2+y^2+z^2\).

2. Most computer algebra systems have in-build algorithms to rewrite symmetric polynomials in terms of elementary symmetric polynomials.
   For example, the following ~sage~ code 
   #+begin_src sage :exports both :session a
     S.<x,y,z> = PolynomialRing(QQ, 3)
     E = SymmetricFunctions(QQ).elementary()
     E.from_polynomial((x*y-z)*(x*z-y)*(y*z-x))  #Modify for your polynomial.
   #+end_src
   outputs
   #+results: 
   : e[2, 2] - e[3] - 2*e[3, 1] - e[3, 1, 1] + 2*e[3, 2] + e[3, 3] +
   : 2*e[4] + e[4, 1] - 2*e[4, 2] - 5*e[5] + 2*e[5, 1] - 2*e[6]


   Explanation of notation:
   - \(e[i]\) is the \(i\)-th elementary symmetric polynomial \(e_i\).
   - \(e[i,j]\) is \(e_i \cdot e_j\), and so on.
   - Since we only have 3 variables, \(e_{4}\) and above are zero.
     So, the expression ~sage~ gave reduces to
     \[e_2^2 - e_3 - 2 e_3e_1 + e_3e_1^2 +  2 e_3e_2 + e_3^2.\]

1. Try the code above with other symmetric polynomials.
   You can evaluate ~sage~ code online at  https://sagecell.sagemath.org/.
**** Splitting fields
1. Let \(F \subset K\) be a field extension and \(f(x) \in F[x]\) a polynomial.
   When is \(K\) called a "splitting field" of \(f(x)\)?

2. The following extensions are splitting fields for some \(f(x)\).
   Give an example of such an \(f(x)\) (there may be more than one).
   1. \(\mathbf{Q} \subset \mathbf{Q}[\sqrt 2]\)

   2. \(\mathbf{Q} \subset \mathbf{Q}[\sqrt 2, \sqrt 3]\)

   3. \(\mathbf{C}(t^n) \subset \mathbf{C}(t)\)

   4. \(F_3 \subset \mathbf{Z}[i]/3\)

3. Let \(f(x)\) be the minimal polynomial of \(\sqrt 2 + \sqrt 3\).
   Is \(\mathbf{Q} \subset \mathbf{Q}[\sqrt 2, \sqrt 3]\) a splitting field for \(f(x)\)?
**** Evaluating expressions in terms of roots

Suppose \(f(x) = x^3+2x-2\) and let \(\alpha_1,\alpha_2,\alpha_3 \in \mathbf{C}\) be the roots of \(f(x)\).

1. We can evaluate a symmetric expression in \(\alpha_i\) by re-writing it in terms of the coefficients.
   For example, evaluate
   \[ (\alpha_1+\alpha_2-\alpha_3)(\alpha_1+\alpha_3-\alpha_2)(\alpha_2+\alpha_3-\alpha_1).\]

2. How do we evaluate asymmetric expressions?
   We cannot, exactly, but we can pin them down up to a finite ambiguity.
   For example, consider \(\alpha = \alpha_1\alpha_2-\alpha_3\).
   The \(S_3\) orbit of the expression \(x_1x_2-x_3\) contains 2 other expressions: \(x_1x_3-x_2\) and \(x_2x_3-x_1\).
   Let \(\beta = \alpha_1\alpha_3 - \alpha_2\) and \(\gamma = \alpha_2\alpha_3-\alpha_1\).

   1. Prove that \((x-\alpha)(x-\beta)(x-\gamma)\) has coefficients in \(\mathbf{Q}\).
   2. Find these coefficients.  You have then narrowed down \(\alpha\) to 3 possible values, namely the roots of this polynomial.
      To do this, you will have to rewrite symmetric polynomials in terms of elementary symmetric polynomials.
      Do this using the ~sage~ code above.
*** Workshop 8
The goal of the workshop is to see the main theorem of Galois theory in action in a moderately complicated example.

Let \(K = \mathbf{Q}[3^{1/4},i]\).
This is the splitting field of \(x^4-3\), and has the presentation
\[ \mathbf{Q}[x,y]/(x^4-3, y^2+1) \to K,\]
where the map above sends \(x\) to \(3^{1/4}\) and \(y\) to \(i\).
You should be able to prove these facts, but for now please proceed assuming them.

1. Use the presentation above to find \(\operatorname{Aut}(K/ \mathbf{Q})\).
2. Find an isomorphism from the dihedral group \(D_4\) to \(\operatorname{Aut}(K / \mathbf{Q})\).
3. Write the subgroup diagram for \(D_4\): a vertex for each subgroup and an arrow for each inclusion.
4. For each group in the subgroup diagram, find the fixed field.

The main theorem of Galois theory says that these are all the fields containing \(\mathbf{Q}\) and contained in \(K\).
*** Workshop 9
The goal of this workshop is to use Galois theory to settle the question of ruler/compass constructions.
We say that \(x \in \mathbf{C}\) is /constructible/ if it lies in a tower of quadratic extensions.
That is, if there exist fields
\[ \mathbf{Q} \subset K_1 \subset K_2 \subset \cdots \subset K_n,\]
where each \(K_i \subset K_{i+1}\) is a degree 2 extension and \(\alpha \in K_n\).
Let us prove the following.

\bigskip

\noindent
*Theorem*. A number \(x \in \mathbf{C}\) is constructible if and only if its Galois group (= the Galois group of the splitting field of its minimal polynomial) has order \(2^m\) for some \(m\).

\bigskip

Let us prove the if part.
Suppose \(z\) is constructible.
It is enough to construct a Galois extension (= splitting field) that contains \(z\) and whose degree over \(\mathbf{Q}\) is a power of 2.

1. Suppose \(z = \sqrt {2 + \sqrt 3}\).
   Construct a Galois extension (= splitting field) that contains \(z\) and whose degree over \(\mathbf{Q}\) is a power of 2.
2. Do the same for \(\sqrt{2 + \sqrt {3 + \sqrt 5}}\).
3. Try to formalise the pattern you see.
   This is a bit tricky.  
   One clean way is to prove the following by induction: there exists field \(K'_i\) containing \(K_i\) such that (a) \(K'_i/ \mathbf{Q}\) is Galois and (b) the degree of \(K'_i / \mathbf{Q}\) is a power of 2.


Let us now try the converse.
Suppose \(z\) lies in a Galois extension of degree \(2^{m}\) over \(\mathbf{Q}\).
Let \(G\) be the Galois group.

1. Here is a fact from group theory: a group of order \(2^m\) has a subgroup of order \(2^{m-1}\).  Use it to produce a chain of subgroups of size \(1,2,\cdots, 2^m\).
2. Apply the main theorem of Galois theory.
* Discussions/announcements
** Welcome to Algebra 2!
Welcome to algebra 2!  

I will introduce the course today, and then we will dive in.  The reading is section 12.1 and the beginning of 12.2 from Artin, and [[A review of rings][a short note about rings]] that I wrote (if you need a refresher).

Because this is the first week, a few things are different.  

I do not expect you to have done the reading by today (from next week, I do expect you to have done the reading by Monday).  The check-in for this week is due on Wednesday (from next week, it will be due on Monday).  I hope you will get a chance to at least skim through the reading by Wednesday.

There is no quiz today (quizzes will start in week 3); no workshops (start in week 2); no homework for Friday (starts in week 2).

See you in class!
** Week 3 in Algebra 2
This week, we will discuss factorisation in the ring of Gaussian integers and then move to fields and field extensions.

In parallel, you will read about the degree of a field extension, its connection with the minimal polynomial, and applications to ruler and compass constructions (Artin 15.3, 15.4, 15.5).  We will talk about this in class next week.

We will also have our first quiz at the beginning of the lecture on Wednesday.  Workshops will happen as scheduled on Tuesday and Wednesday.

See you in class!
** Week 4 in Algebra 2
We will talk about field extensions, their degrees, and applications to ruler and compass constructions.  

In parallel, you will read how to construct field extensions synthetically, without access to an ambient field like \(\mathbf{C}\), and use this knowledge to construct exotic finite fields. 

We will have an in-class quiz at the beginning of Monday's class based on the ideas in the second assignment.

See you in class!
** Week 5 in Algebra 2
This week, we will construct all finite fields and learn (pretty much) everything there is to learn about them.  In your readings, you will read about the primitive element theorem and the fundamental theorem of algebra.

We will have an in-class quiz at the beginning of Monday's class based on the ideas in the third assignment.

See you in class!
** Week 6 in Algebra 2
This week, we will talk about the primitive element theorem and the fundamental theorem of algebra.

As usual, we will have an in-class quiz at the beginning of Monday's class based on the ideas in the fourth assignment.

See you in class!
** Week 7 in Algebra 2
There is no reading to do for this week.  On Monday, I will give an overview of Galois theory.  You may want to watch the video titled "Overview of Galois theory" in the [[https://login.echo360.org][class recordings.]] (Use your anu id u......@anu.edu.au to log in).

Despite the midterm on Wednesday, we will have a quiz on Monday based on the ideas in the fifth assignment.

See you in class!
** Week 8 in Algebra 2
We don't have class today (Monday) because of ANZAC day.  The quiz and the check-in are postponed to Wednesday. 

This week reading was on symmetric functions and splitting fields, which is what we will talk about in class on Wednesday.
Next week's reading will be about automorphisms and fixed fields.

See you in class!
** Week 9 in Algebra 2
In class, we will talk about automorphism groups of field extension and fixed fields.  The reading is about the main theorem of Galois theory.  

With the main theorem, we will have the tools to know precisely the intermediate extensions for any given field extension.  The next goal is to characterise the extensions that arise from adjoining n-th roots (this is called "Kummer theory").  We will use this knowledge to exhibit extensions that cannot arise as a tower of n-th root extensions.    

As usual, we have a quiz on Monday based on the most recent submitted homework.

See you in class!
** Week 10 in Algebra 2
This week, we will see the main theorem of Galois theory in its full glory (with lots of examples). 

The next week has applications of the main theory to cubics and quartics.  Then, we will do Kummer theory and prove that a quintic is not solvable by radicals.  

A topic I would like to squeeze in is the n-th roots of unity where n is not a prime.  This is not in the book, but I felt like you all really liked the fact that this extension had degree phi(n).        

As usual, we have a quiz on Monday based on the most recent submitted homework.

See you in class!
** No class on Monday; Quiz on Wednesday; HW due tomorrow
Homework 1 is due tomorrow on canvas.  Remember that you only have to submit one problem and it is only for feedback.

We don't have class on Monday because of Canberra day.  So our first quiz will have to be on Wednesday.  It will be 10 minutes long at the beginning of class.

Have a good long weekend!
** Exam and office hours today
Good luck for the exam today.  Please arrive in time --- we will start at 3:35 sharp and end at 5:00.

Unfortunately, I can't come in to work today.  My colleague Tanisha will administer the exam.

If you have any last minute questions, I will hold office hours by zoom from 1:30pm to 3:00pm.  Here are the details:

URL: https://anu.zoom.us/j/85129975712?pwd=EDhxn9J1KIuaqgSAbwDx4SXTuzxRBX.1
Meeting id: 85129975712
Password: frobenius    
** Course representative
We need a course representative.  Please volunteer (by sending me an email).  You know you want to!
** Recording for 25 March
I am sorry that the video was not captured on 25 March.  As an alternative, I have uploaded a previous year's recording that covers the same topic.  
** Clarification of Proposition 15.2.8
Artin's Proposition 15.2.8 is easy to misread; so here is some clarification.

Let \(F \subset K\) be fields (think of \(\mathbf{Q} \subset \mathbf{C}\) as a concrete example).
Let \(\alpha, \beta \in K\) be two elements algebraic over \(F\). 
We can ask three questions:

1. Is \(F[\alpha] = F[\beta]\)? (Literal equality).
2. Is there an \(F\)-isomorphism \(F[\alpha] \to F[\beta]\)? (An \(F\)-isomorphism is an isomorphism that is the identity when restricted to \(F\)).
3. Is there an \(F\)-isomorphism \(F[\alpha] \to F[\beta]\) that sends \(\alpha\) to \(\beta\).

Proposition 15.2.8 addresses the third question.  
The answer is "Yes" if and only if \(\alpha\) and \(\beta\) have the same irreducible polynomial over \(F\).

Here is what we can say about the first two questions. 

1. We have \(F[\alpha] = F[\beta]\) if and only if \(\alpha \in F[\beta]\) and \(\beta \in F[\alpha]\).  Whether this is case, however, can be difficult to determine.  For example, it is not obvious whether \(\mathbf{Q}[\sqrt 2 + \sqrt 3] = \mathbf{Q}[\sqrt 2 - \sqrt 3]\).  What do you think?

2. If \(F[\alpha] = F[\beta]\), then certainly there is an \(F\)-isomorphism \(F[\alpha] \to F[\beta]\), namely the identity isomorphism.  But if \(\alpha \neq \beta\), then the identity will not take \(\alpha\) to \(\beta\).

   Even if \(F[\alpha] \neq F[\beta]\), there can be still be an \(F\)-isomorphism \(F[\alpha] \to F[\beta]\).  For example, we have an isomorphism \(\mathbf{Q}[2^{1/3}] \to \mathbf{Q}[2^{1/3}\omega]\) that sends \(2^{1/3}\) to \(2^{1/3}\omega\).
   This kind of isomorphism---one that sends \(\alpha\) to \(\beta\)---exists if and only if \(\alpha\) and \(\beta\) have the same irreducible polynomial.

   Still in the case \(F[\alpha] \neq F[\beta]\), there can be an \(F\)-isomorphism \(F[\alpha] \to F[\beta]\) that does not take \(\alpha\) to \(\beta\).  It can be difficult to determine whether such an isomorphism exists.  But if it does, then the image of \(\alpha\) in \(F[\beta]\) will necessarily have the same irreducible polynomial as \(\alpha\).

There is a separate question: is there an isomorphism \(F[\alpha] \to F[\beta]\) that does not necessarily act as the identity on \(F\)?  There can be, but it takes some effort to construct examples.  Indeed, if \(F = \mathbf{Q}\), then any isomorphism \(\mathbf{Q}[\alpha] \to \mathbf{Q}[\beta]\) will have to act as the identity on \(\mathbf{Q}\) (do you see why?).  So such examples only exist where the base field \(F\) is different from \(\mathbf{Q}\).
** Assignment 1 "marked"; Assignment 2 due today
I just finished "marking" assignment 1.  Some of my comments are about general principles of mathematical writing.  I have uploaded four articles about writing mathematics and linked them from the course homepage (scroll all the way down, under "References and resources").  Some of my comments refer to these articles.  For example, if I wrote "See [Poonen, item 27]", I would like you to look at item number 27 in Poonen's article about mathematical writing.

Also, I have posted [[Assignment 1][solution sketches]]. 
** Mid-semester examination
The mid-semester exam will be in-class on Wednesday in Week 7 (22 April).  It will cover everything that we have seen until week 6.  I will upload practice questions/exams shortly.

We will use the entire hour and half for the exam.  So we will start at 3:30 sharp and end at 5:00.  
** Office hours in teaching break
Instead of the regular office hours, this week I will have office hours on Thursday (16 April) 1pm-3pm.  If you want to meet at some other time, please feel free to email me and we can set a time. 
* Mini projects
Choose one of the topics below and write a 2-5 page article on it.  Please submit your write-up latest by the Friday of Week 12 (29 May) by email.  After your submission, we will schedule a short presentation (10 minutes, followed by 5-10 minutes for questions).  You will present the topic to me and one of my colleagues.  

Your project will be judged on
1. the quality of your writing (correctness, clarity, and readibility)
2. your understanding as demonstrated in the writing and presentation.

You may use any sources as reference, but you must cite them appropriately.  Every source that you use must be accessible to others.  So a published paper, a website, or a book is fine.  Conversation with a text generator (like ChatGPT) or another person is not a valid source.  You are free to get help from other people or use a text generator, but everything you submit must be written by yourself in your own words.  You should also be prepared to present it to others and answer questions about it.  You should also acknowledge all the sources of help in your write-up.

I am happy to talk about the project at any time.  Send me an email and we will set up a time.    
** Possible topics
1. Let \(G = \operatorname{Aut}_{\mathbf{C}}(\mathbf{C}(t))\).
   It turns out that \(G\) is isomorphic to the group of \(2 \times 2\) complex valued matrices, modulo scaling.  The matrix \(\begin{pmatrix} a& b \\ c & d \end{pmatrix}\) corresponds to the isomorphism
   \[ t \mapsto \frac{a + bt}{c + dt}.\]
   Describe all finite subgroups of \(G\).

2. Let \(G \subset \operatorname{Aut}_{\mathbf{C}}(\mathbf{C}(t))\) be a finite group.
   Let \(t_1, \dots, t_n\) be the orbit of \(t\).
   Let \(e_1, \dots, e_n\) be the elementary symmetric polynomials in \(t_1, \dots, t_n\).
   Prove that \(\mathbf{C}(e_1, \dots, e_n) \subset \mathbf{C}(t)\) is the fixed field of \(G\).
   Illustrate with some examples.

3. Let \(\ell\) be a prime number.
   What is the degree of the splitting field of \(x^{\ell}-1\) over \(\mathbf{F}_p\) for other primes \(p\)?
   Do some experiments to find an answer.
   If possible, formulate a conjecture, prove it or find it in the literature.

4. Fix a positive integer \(n\).
   Make the following statement precise: "most polynomials of degree \(n\) in \(\mathbf{Q}[x]\) have Galois group \(S_n\)."
   Give experimental evidence to support or refute it.

5. Look up the "Kronecker--Weber theorem". 
   Explain its statement and illustrate it with some examples.

6. Find out what is the "inverse Galois problem".
   Explain some partial results.

7. If you have other ideas, please feel free!  But first talk to me.
