- what: Refereed for the Journal of the EMS, Algebra and Number Theory, Crelle, Manuscripta mathematica, and Advances in geometry.

- what: Co-organized the workshop ``Stability and moduli spaces'' at the American Institute of Mathematics.
  when: January 2017

- what: Co-organized the Summer Workshop in Algebraic Geometry at the University of Georgia.
  when: August 2016

- what: Organized the Fairly Informal Reading Seminar and Tea (FIRST) at the University of Georgia.
  when: Fall 2016  

- what: Co-organized the graduate student algebraic geometry seminar at Columbia.
  when: Spring 2016  

- what: Conducted Putnam preparation sessions at Columbia.
  when: Fall 2015

- what: Supervised an undergraduate independent reading course (``Generatingfunctionology'') at Columbia.
  when: Fall 2015  

- what: Gave expository sessions for graduate students in the ``Workshop on birational geometry and stability of moduli stacks and spaces of curves'' in Hanoi, Vietnam.
  when: January 2014

- what: Served on the thesis defense committees of Natasha Potashnik, Zachary Maddock, and Xuanyu Pan at Columbia.

- what: Co-organized the poster session at AGNES at Boston College.
  when: 2013  

- what: Organized the student algebraic geometry seminar at Harvard/MIT.  
  when: 2010, 2011
