- what: Referee for the *Journal of the EMS*, *Journal of Differenital Geometry*, *Journal of Algebraic Geometry*, *Annales scientifiques de l'École normale supérieure*, *Algebra and Number Theory*, *Journal für die reine und angewandte Mathematik*, *Manuscripta mathematica*, *Advances in geometry*, *Mathematical Research Letters*.

- what: Reviewer for American Mathematical Society's *Mathematical Reviews*.

- what: Co-organizer of the algebra and topology special year at the MSI at ANU.
  when: 2022

- what: Co-organizer for the workshop *Trends in the classification of algebraic varieties and their sheaves* at the Banff International Research Station, Oaxaca, Mexico
  when: 2021

- what: Member of the thesis committee of Abhishek Bharadwaj at ANU.
  when: 2020

- what: Member of the *Future research talent* selection committee at the MSI at ANU.
  when: 2019

- what: Member of the director search committee at the MSI at ANU.
  when: 2019

- what: Member of the formal liaison committee at the MSI at ANU.
  when: 2019

- what: Member of the award committee for the *BH Neumann Prize* for best student talk in AustMS.
  when: 2019

- what: Co-organizer of the workshop *Stability and moduli spaces* at the American Institute of Mathematics.
  when: 2017

- what: Co-organizer of the *Summer workshop in algebraic geometry* at the University of Georgia.
  when: 2016

- what: Organizer of the *Fairly informal reading seminar and tea (FIRST)* at the University of Georgia.
  when: 2016  

- what: Co-organizer of the graduate student algebraic geometry seminar at Columbia University.
  when: 2016  

- what: Organizer and lecturer for the Putnam competition preparation sessions at Columbia University.
  when: 2015

- what: Lecturer in the *Workshop on birational geometry and stability of moduli stacks and spaces of curves* in Hanoi, Vietnam.
  when: 2014

- what: On the thesis committees of Natasha Potashnik, Zachary Maddock, and Xuanyu Pan at Columbia University.
  when: 2012--2016

- what: Co-organizer of the poster session at the *Algebraic Geometry North-Eastern Series (AGNES)* conference in Boston College.
  when: 2013  

- what: Organizer of the student algebraic geometry seminar at Harvard/MIT.  
  when: 2010--2011

