- what: Refereed for the *Journal of the European Mathematical Society*, *Journal of Differential Geometry*, *Journal of Algebraic Geometry*, *Annales Scientifiques de l'École Normale Supérieure*, *Algebra and Number Theory*, *Journal für die reine und angewandte Mathematik*, *manuscripta mathematica*, *Advances in Geometry*, *Mathematical Research Letters*

- what: Reviewed for American Mathematical Society's *Mathematical Reviews*

- what: Co-organizing the algebra and topology special year at the MSI at ANU (with James Borger, Martin Helmer, and Amnon Neeman)
  when: 2022

- what: Co-organizing the workshop *Trends in the classification of algebraic varieties and their sheaves* at the Banff International Research Station, Oaxaca, Mexico (with Jarod Alper and Cesar Lozano Huerta)
  when: 2021

- what: Served on the thesis committee of Abhishek Bharadwaj at ANU
  when: 2020

- what: Served on the *Future research talent* selection committee at the MSI at ANU
  when: 2019

- what: Served on the director search committee at the MSI at ANU
  when: 2019

- what: Served on the formal liaison committee at the MSI at ANU
  when: 2019

- what: Served on the award committee for the *BH Neumann Prize* for best student talk in AustMS
  when: 2018

- what: Co-organised the workshop *Polynomial Algebraic Developments in Optimisation and Computation* at ANU (with Markus Hegland)
  when: 2018
  
- what: Conducted training sessions in algebraic geometry at the *D21 Workshop* at the Australian Signals Directorate
  when: 2018

- what: Co-organised the workshop *Stability and moduli spaces* at the American Institute of Mathematics (with Maksym Fedorchuk, Ian Morrison, and Xiaowei Wang)
  when: 2017

- what: Co-organised the *Summer workshop in algebraic geometry* at the University of Georgia (with Angela Gibney and Nicola Tarasca)
  when: 2016

- what: Organised the *Fairly informal reading seminar and tea (FIRST)* at the University of Georgia
  when: 2016  

- what: Co-organised the graduate student algebraic geometry seminar at Columbia University (with Johan de Jong)
  when: 2016  

- what: Conducted the Putnam competition preparation sessions at Columbia University
  when: 2015

- what: Lectured in the *Workshop on birational geometry and stability of moduli stacks and spaces of curves* in Hanoi, Vietnam
  when: 2014

- what: Served on the thesis committees of Natasha Potashnik, Zachary Maddock, and Xuanyu Pan at Columbia University
  when: 2012--2016

- what: Co-organised the poster session at the *Algebraic Geometry North-Eastern Series (AGNES)* conference in Boston College (with Anand Patel)
  when: 2013  

- what: Organised the student algebraic geometry seminar at Harvard/MIT  
  when: 2010--2011

