- what: Refereed for the *Journal of the EMS*, *Journal of Differenital Geometry*, *Journal of Algebraic Geometry*, *Annales scientifiques de l'Écolge normale supérieure*, *Algebra and Number Theory*, *Journal für die reine und angewandte Mathematik*, *Manuscripta mathematica*, *Advances in geometry*, *Mathematical Research Letters*.

- what: Review periodically for American Mathematical Society's *Mathematical Reviews*.

- what: Co-organizing the algebra and topology special year at the MSI at ANU
  when: 2022

- what: Co-organizing the workshop *Trends in the classification of algebraic varieties and their sheaves* at the Banff International Research Station, Oaxaca, Mexico
  when: 2021

- what: Serving on the thesis committee of Abhishek Bharadwaj at ANU
  when: 2020

- what: Served on the *Future research talent* selection committee at the MSI at ANU
  when: 2019

- what: Served on the director search committee at the MSI at ANU
  when: 2019

- what: Served on the formal liaison committee at the MSI at ANU
  when: 2019

- what: Served on the award committee for the *BH Neumann Prize* for best student talk in AustMS
  when: 2019

- what: Co-organized the workshop *Stability and moduli spaces* at the American Institute of Mathematics
  when: 2017

- what: Co-organized the *Summer workshop in algebraic geometry* at the University of Georgia
  when: 2016

- what: Organized the *Fairly informal reading seminar and tea (FIRST)* at the University of Georgia
  when: 2016  

- what: Co-organized the graduate student algebraic geometry seminar at Columbia University
  when: 2016  

- what: Conducted the Putnam competition preparation sessions at Columbia University
  when: 2015

- what: Lectured in the *Workshop on birational geometry and stability of moduli stacks and spaces of curves* in Hanoi, Vietnam
  when: 2014

- what: Served on the thesis committees of Natasha Potashnik, Zachary Maddock, and Xuanyu Pan at Columbia University
  when: 2012--2016

- what: Co-organized the poster session at the *Algebraic Geometry North-Eastern Series (AGNES)* conference in Boston College
  when: 2013  

- what: Organized the student algebraic geometry seminar at Harvard/MIT  
  when: 2010--2011

