#+TITLE: Curriculum Vitae | Anand Deopurkar
#+AUTHOR: [[mailto:anand.deopurkar@anu.edu.au][~anand.deopurkar@anu.edu.au~]]
#+options: -:t broken-links:mark num:nil toc:nil date:nil
#+LATEX_HEADER: \usepackage[margin=3cm]{geometry}
#+LATEX_HEADER_EXTRA: \hypersetup{colorlinks=true,urlcolor=black}
#+LATEX_HEADER_EXTRA: \usepackage{Baskervaldx}
#+HTML_HEAD_EXTRA: <script src="js/collapsibility.js"></script>


* Positions
:PROPERTIES:
:html_headline_class: collapsible
:END:
#+RESULTS:
:results:
- 2021-- :: Senior lecturer\\
      Australian National University, Canberra, Australia.
- 2018--2020 :: Lecturer\\
      Australian National University, Canberra, Australia.
- 2016--2017 :: Assistant professor (limited term)\\
      University of Georgia, Athens, Georgia, USA.
- 2012--2016 :: J. F. Ritt assistant professor\\
      Columbia University, New York City, New York, USA.
- 2008 :: Summer intern\\
      Microsoft Research, Bangalore, India.
:end:

* Education
:PROPERTIES:
:html_headline_class: collapsible
:END:
#+RESULTS:
:results:
- 2012 :: Ph.D.\\
 Harvard University, Cambridge, Massachusetts, USA.\\
       /Alternate compactifications of Hurwitz spaces/, advisor: Joseph Harris.
- 2008 :: Bachelor of Science (S.B.)\\
 Massachusetts Institute of Technology, Cambridge, Massachusetts, USA.\\
       Mathematics with computer science.
:end:

* Grants and awards
:PROPERTIES:
:html_headline_class: collapsible
:END:
#+begin_src elisp :exports results :results value raw drawer
  ;; Our pretty-printing function
  (defun pretty-print ()
    (let ((title (org-entry-get nil "ITEM"))
          (org (org-entry-get nil "org"))
          (year (org-entry-get nil "year")))
      (format "- %s :: %s, %s."
              year
              title
              org)))
  (string-join (org-map-entries 'pretty-print nil '("#awards.org")) "\n")
#+end_src

#+RESULTS:
:results:
- 2018 :: Discovery early career researcher award (DECRA), Australian Research Council.
- 2016 :: AMS-Simons travel grant, American Mathematical Society and Simons Foundation.
- 2016 :: Workshop funding, American Institute of Mathematics.
- 2014 :: Award for excellence in teaching, Columbia University, Mathematics department.
- 2006 :: Jon A. Bucsela prize for the top undergraduate, Massachusetts Institute of Technology, Mathematics department.
- 2006 :: Rogers family prize for undergraduate summer research, Massachusetts Institute of Technology, Mathematics department.
- 2007, 2005, 2004 :: Honorable mention (2004) , honorable mention (2005), rank 16--25 (2004), William Lowell Putnam competition.
- 2004, 2003 :: Silver medal (2004), bronze medal (2003), International mathematical olympiad.
:end:

* Publications 
:PROPERTIES:
:html_headline_class: collapsible
:END:
#+begin_src elisp :exports results :results value raw drawer :lexical t
  ;; Our pretty-printing function
  (let ((previous ""))
    (defun pretty-print ()
      (let ((title (org-entry-get nil "ITEM"))
            (year (org-entry-get nil "year"))
            (journal (org-entry-get nil "journal"))
            (coauthors (org-entry-get nil "with"))
            (comment (org-entry-get nil "comment"))
            (link (org-entry-get nil "link")))
        (format "- %s :: %s.\\\\\n          /%s/%s%s%s."
                (if (equal previous year)
                    "---"
                  (setq previous year))
                journal
                title
                (if comment
                    (format " (%s)" comment)
                  "")
                (if coauthors
                    (format ", with %s" coauthors)
                  "")
                (if (and link cv-include-links)
                    (format " (%s)" link)
                  "")))))
  (string-join (org-map-entries 'pretty-print "-pp-expository-thesis" '("#papers.org")) "\n")
#+end_src

#+RESULTS:
:results:
- 2022 :: Forum of Mathematics, Sigma (accepted).\\
          /Vector bundles and finite covers/, with [[https://sites.google.com/view/anand-patel][Anand Patel]].
- 2021 :: Transactions of the Americal Mathematical Society 374, No. 1, 589-641 (2021).\\
          /Stable log surfaces, admissible covers, and canonical curves of genus 4/, with Changho Han.
- 2020 :: Documenta Mathematica 25, 1917--1952 (2020).\\
          /Ramification divisors of general projections/, with [[https://eduryev.weebly.com/][Eduard Duryev]], [[https://sites.google.com/view/anand-patel][Anand Patel]].
- 2019 :: Transactions of the Americal Mathematical Society, 371, 549--588 (2019).\\
          /Covers of stacky curves and limits of plane quintics/.
- 2018 :: Contemporary Mathematics 703, 209--222 (2018).\\
          /Syzygy divisors on Hurwitz spaces/, with [[https://sites.google.com/view/anand-patel][Anand Patel]].
- --- :: Mathematische Zeitschrift 288, No. 3-4, 1157--1164 (2018).\\
          /The canonical syzygy conjecture for ribbons/.
- 2016 :: Algebraic Geometry 3, No. 1, 1--22 (2016).\\
          /Toward GIT stability of syzygies of canonical curves/, with [[https://www2.bc.edu/maksym-fedorchuk/][Maksym Fedorchuk]], [[http://faculty.fordham.edu/dswinarski/][David Swinarski]].
- 2015 :: Algebra & Number Theory 9, No. 2, 459--492 (2015).\\
          /The Picard rank conjecture for the Hurwitz spaces of degree up to five/, with [[https://www2.bc.edu/anand-p-patel/][Anand Patel]].
- 2014 :: Albanian Journal of Mathematics 8, No. 2, 55--70 (2014).\\
          /Groebner techniques for ribbons/, with [[https://www2.bc.edu/maksym-fedorchuk/][Maksym Fedorchuk]], [[http://faculty.fordham.edu/dswinarski/][David Swinarski]].
- --- :: International Mathematics Research Notices 2014, No. 14, 3863--3911 (2014).\\
          /Compactifications of Hurwitz spaces/.
- 2013 :: Mathematical Research Letters 20, No. 5, 869--884 (2013).\\
          /Sharp slope bounds for sweeping families of trigonal curves/, with [[https://sites.google.com/view/anand-patel][Anand Patel]].
- --- :: Advances in Mathematics 248, 96--154 (2013).\\
          /Modular compactifications of the space of marked trigonal curves/.
:end:

- Pre-prints ::
#+begin_src elisp :exports results :results value raw drawer
  (string-join (org-map-entries 'pretty-print "+pp" '("#papers.org")) "\n")
#+end_src

#+RESULTS:
:results:
- 2021 :: Pre-print, arxiv:2109.12672.\\
          /A universal formula for counting cubic surfaces/, with [[https://sites.google.com/view/anand-patel][Anand Patel]], [[https://sites.google.com/view/dennis-tseng][Dennis Tseng]].
- --- :: Pre-print, arXiv:2108.09155.\\
          /Spherical objects and stability conditions on CY2 quiver categories/, with [[https://asilata.github.io/][Asilata Bapat]], [[https://maths-people.anu.edu.au/~licatat/][Anthony Licata]].
- 2020 :: Pre-print, arXiv:2011.07908.\\
          /A Thurston compactification of the space of stability conditions/, with [[https://asilata.github.io/][Asilata Bapat]], [[https://maths-people.anu.edu.au/~licatat/][Anthony Licata]].
- 2019 :: Pre-print, arXiv:1906.08196.\\
          /Anticanonical tropical cubic del Pezzos contain exactly 27 lines/, with [[https://people.math.osu.edu/cueto.5/][María Angélica Cueto]].
- 2013 :: Pre-print, appendix to [[https://drive.google.com/file/d/1wq-Fh3DiqODc51t-J0phIexVF7B4lxsY/view][/Cyclic covering morphisms on \(\overline M_{0,n}\)/]] by [[https://www2.bc.edu/maksym-fedorchuk/][Maksym Fedorchuk]].\\
          /Class of the Hodge eigenbundle using orbifold Riemann-Roch/.
:end:

- Expository ::
#+begin_src elisp :exports results :results value raw drawer
  (string-join (org-map-entries 'pretty-print "+expository" '("#papers.org")) "\n")
#+end_src

#+RESULTS:
:results:
- 2010 :: Minor thesis, Harvard, 2010.\\
          /An introduction to intersection homology/ (expository) ([[file:papers/anandrd_minor_thesis.pdf][pdf]]).
- 2008 :: MIT Undergruate Journal of Mathematics.\\
          /Normalization of algebraic varieties/ (expository) ([[file:papers/anandrd_ug_thesis.pdf][pdf]]).
:end:

* Supervision
:PROPERTIES:
:html_headline_class: collapsible
:END:
#+begin_src elisp :exports results :results value raw drawer :lexical t
  ;; Our pretty-printing function
  (let ((previous ""))
    (defun pretty-print ()
      (let ((name (org-entry-get nil "ITEM"))
            (year (org-entry-get nil "year"))
            (level (org-entry-get nil "level"))
            (coadvisors (org-entry-get nil "with"))
            (comment (org-entry-get nil "comment")))
        (format "- %s :: %s, %s%s%s."
                (if (equal previous year)
                    "---"
                  (setq previous year))
                name
                level
                (if coadvisors
                    (concat ", with " coadvisors)
                  "")
                (if comment
                    (format " (%s)" comment)
                  "")
                ))))
  (string-join (org-map-entries 'pretty-print nil '("#supervision.org")) "\n")
#+end_src

#+RESULTS:
:results:
- 2021 :: Zongpu Zhang, Honours.
- 2020 :: Ben Leedom, Honours.
- 2019 :: Diclehan Erdal, Masters.
- --- :: Adwait Sengar, Masters, with Uri Onn.
- --- :: Dhruva Kelkar, Future Research Scholar.
- --- :: Sridhar Venkatesh, Future Research Scholar.
- 2018 :: Sean Carroll, Summer Research Scholar, with Asilata Bapat.
- --- :: Kyle Broder, Honours, with Alex Isaev.
- --- :: Likun Yao, Honours, with Amnon Neeman.
:end:

* Talks and presentations
:PROPERTIES:
:html_headline_class: collapsible
:END:
#+begin_src elisp :exports results :results value raw drawer :lexical t
  ;; Our pretty-printing function
  (let ((previous ""))
    (defun pretty-print ()
      (let ((year (org-entry-get nil "year"))
            (place (org-entry-get nil "place"))
            (meet (org-entry-get nil "meet"))
            (institute (org-entry-get nil "institute"))
            (comment (org-entry-get nil "comment"))
            (type (org-entry-get nil "type"))
            (title (org-entry-get nil "ITEM"))
            (link (org-entry-get nil "link")))
        (format "- %s :: %s. /%s/%s%s."
                (if (equal previous year)
                    "---"
                  (setq previous year))
                (string-join (remove nil `(,institute ,place, meet)) ", ")
                title
                (if comment
                    (format " (%s)" comment)
                  "")
                (if (and link cv-include-links)
                    (format " (%s)" link)
                  "")))))
  (string-join (org-map-entries 'pretty-print nil '("#talks.org")) "\n")
#+end_src

#+RESULTS:
:results:
- 2022 :: Harvard University, Cambridge, Massachusetts. /How to count using equivariant cohomology?/.
- --- :: Brown University, Providence, Rhode Island. /Apparent boundaries of projective varieties/.
- --- :: Institute for Computational and Experimental Research in Mathematics, Providence, Rhode Island, Braids in representation theory and algebraic combinatorics. /The geometry and combinatorics of Harder--Narasimhan filtrations/.
- --- :: Bhaskaracharya Pratishthana, Pune, India, Trimester program on triangle groups, Belyi uniformization, and modularity. /The geometry of Fermat-like equations/ (expository).
- 2021 :: Bhaskaracharya Pratishthana, Pune, India, Trimester program on triangle groups, Belyi uniformization, and modularity. /Algebraic curves and Belyi's theorem/ (expository).
- --- :: Canberra, Australia, ANU Mathematics Extension Program. /Error correcting codes/ (expository).
- --- :: Max Planck institute für Mathematics, Bonn, Germany, Workshop on compactifications of stability manifolds (Online). /A Thurston compactification of the space of stability conditions/.
- --- :: Tata Institute of Fundamental Research (Online), Mumbai, India. /A Thurston compactification of the space of stability conditions/.
- --- :: Jagiellonian University (Online), Kraków, Poland. /A Thurston compactification of the space of stability conditions/.
- 2020 :: University of New England, Amidale, Australia, Topology session, AustMS (Online). /A Thurston compactification for categories/.
- --- :: Mexico, Seminario nacional de geometria algebraica (Online joint seminar of multiple universities in Mexico). /Apparent boundaries of projective varieties/.
- --- :: University of California (Online), San Diego, California. /Apparent boundaries of projective varieties/.
- 2019 :: University of Sydney, Sydney, Australia, Workshop on triangulated categories in geometry and representation theory. /Groups, spherical twists, and stability conditions/ (part of a series with Asilata Bapat and Anthony Licata).
- --- :: University of Sydney, Sydney, Australia, Birational geometry and moduli spaces. /Log surfaces of almost K3 type and curves of genus 4/.
- --- :: Australian National University, Canberra, Australia, Women in mathematics day. /The work of Claire Voisin/ (expository).
- 2018 :: University of Auckland, Auckland, New Zealand, Character varieties and topological quantum field theory. /Geometry of Hurwitz spaces/.
- --- :: Number theory session,  AustMS, Adelaide, Australia. /On the geometric Steinitz problem/.
- --- :: Australian National University, Canberra, Australia, Colloquium. /The work of Caucher Birkar/ (expository).
- --- :: Xiamen University, Xiamen, China, Algebraic surfaces and related topics. /Moduli of almost K3 log surfaces and curves of genus 4/.
- --- :: Tata Institute of Fundamental Research, Mumbai, India. /How to count using (co)homology/ (expository).
- --- :: Indian Institute of Science, Bengaluru, India. /What are ribbons and what do they tell us about Riemann surfaces/.
- --- :: Monash University, Melbourne, Australia. /What are ribbons and what do they tell us about Riemann surfaces/.
- --- :: Australian National University, Canberra, Australia. /On the critical loci of finite maps/.
- --- :: MATRIX, Creswick, Victoria, Australia, Workshop on algebraic geometry approximation, and optimization. /Quadrature and algebraic geometry/.
- 2017 :: University of North Carolina, Chapel Hill, North Carolina, Workshop on topics in algebraic geometry. /Vector bundles and finite covers/.
- --- :: University of Georgia, Athens, Georgia. /Vector bundles and finite covers/.
- --- :: Canada/USA Mathcamp, Tacoma, WA. /How to count using topology/ (expository).
- --- :: Indian Institute of Science Education and Research, Pune, India. /Quivers and their representations/.
- --- :: Emory University, Atlanta, Georgia. /Vector bundles and finite covers/.
- 2016 :: Australian National University, Canberra, Australia. /Geometry of moduli spaces/.
- --- :: Jeju Island, South Korea, Conference on moduli and birational geometry. /Vector bundles and finite covers/.
- --- :: Indian Institute of Science Education and Research, Pune. /Vector bundles and finite covers/.
- --- :: University of South Carolina, Columbia, South Carolina. /Ribbons and Green's conjecture/.
- --- :: University of Georgia, Athens, Georgia. /Ribbons and Green's conjecture/.
- --- :: Institute for Computational and Experimental Research in Mathematics, Providence, Rhode Island, Workshop on cycles on moduli spaces, geometric invariant theory, and dynamics. /Cycles on Hurwitz spaces/.
- --- :: University of Georgia, Athens, Georgia. /The algebra of canonical curves and the geometry of their moduli space/.
- --- :: Seattle, Washington, Higher genus curves and fibrations of higher genus curves in mathematical physics and arithmetic geometry II, AMS joint mathematics meetings. /Picard groups of Hurwitz spaces/.
- --- :: Seattle, Washington, Moduli spaces in algebraic geometry I, AMS joint mathematics meetings. /Limits of plane quintics via covers of stacky curves/.
- 2015 :: Northeastern University, Boston, Massachusetts, Boston College--Northeastern algebraic geometry conference. /Limits of plane quintics via covers of stacky curves/.
- --- :: University of Utah, Salt Lake City, Utah, Summer institute in algebraic geometry. /Limits of plane quintics via covers of stacky curves/ (poster).
- --- :: Daejeon, South Korea, SIAM applied algebraic geometry conference. /Syzygies of canonical curves and the geometry of \(\overline M_g\)/.
- --- :: Mathematisches Forschungsinstitut Oberwolfach, Oberwolfach, Germany. /GIT stability of syzygies of curves/ (mini talk).
- --- :: Purdue University, West Lafayette, Indiana. /Syzygies, GIT, and the moduli space of curves/.
- --- :: Ohio State University, Columbus, Ohio. /Limits of plane curves via stacky branched covers/.
- --- :: Harvard University, Cambridge, Massachusetts. /Syzygies, GIT, and the log minimal model program for \(\overline{M}_g\)/.
- --- :: Courant Institute, New York University, New York City, New York. /Picard groups of Hurwitz spaces/.
- --- :: Indian Institute for Science Research and Education, Pune, India. /The birational geometry of \(\overline M_g\)/.
- --- :: Stony Brook University, Stony Brook, New York. /Syzygies of canonical curves and birational geometry of \(\overline M_g\)/.
- 2014 :: University of Michigan, Ann Arbor, Michigan. /GIT stability of syzygies of canonical curves/.
- --- :: Yale University, New Haven, Connecticut. /GIT stability of syzygies of canonical curves/.
- --- :: Boston College, Boston, Massachusetts. /Towards GIT stability of syzygies of canonical curves/.
- 2013 :: Postech, Pohang, Korea. /Towards GIT stability of syzygies of canonical curves/.
- --- :: Philadelphia, Pennsylvania, Geometry of algebraic varieties, AMS sectional meeting. /Towards GIT stability of syzygies of canonical curves/.
- --- :: Boston College, Boston, Massachusetts, Algebraic geometry northeastern series. /Sharp slope bounds for sweeping families of trigonal curves/ (poster).
- --- :: Stanford University, Palo Alto, California. /Alternate compactifications of Hurwitz spaces/.
- --- :: Princeton University, Princeton, New Jersey. /Compactifying spaces of branched covers/.
- 2012 :: Rice University, Houston, Texas. /Alternate compactifications of Hurwitz spaces/.
- 2011 :: Massachusetts Institute of Technology, Cambridge, Massachusetts. /Compactifications of Hurwitz spaces/.
- --- :: Columbia University, New York City, New York. /Compactifications of Hurwitz spaces/.
- --- :: Stony Brook University, Stony Brook, New York. /Compactifications of Hurwitz spaces/.
- --- :: Brown University, Providence, Rhode Island. /Compactifications of Hurwitz spaces/.
- --- :: Harvard University, Cambridge, Massachusetts, A celebration of algebraic geometry (conference for the 60th birthday of Joe Harris). /Birational geometry of the space of marked trigonal curves/ (poster).
:end:

* Service
:PROPERTIES:
:html_headline_class: collapsible
:END:
#+begin_src elisp :exports results :results value raw drawer :lexical t
  ;; Our pretty-printing function
  (let ((previous ""))
    (defun pretty-print ()
      (let ((title (org-entry-get nil "ITEM"))
            (year (org-entry-get nil "year"))
            (with (org-entry-get nil "with"))
            (institute (org-entry-get nil "institute")))
        (format "- %s :: %s%s%s."
                (if year
                    (if (equal previous year)
                        "---"
                      (setq previous year))
                  "*")
                title
                (if with
                    (format " %s" with)
                  "")
                (if institute
                    (format ", %s" institute)
                  "")
                ))))
  (string-join (org-map-entries 'pretty-print nil '("#service.org")) "\n")
#+end_src

#+RESULTS:
:results:
- * :: Refereed for Journal of the European Mathematical Society, Journal of Differential Geometry, Journal of Algebraic Geometry, Annales Scientifiques de l'École Normale Supérieure, Mathematische Annalen, Algebra and Number Theory, Journal für die reine und angewandte Mathematik, manuscripta mathematica, Advances in Geometry, Mathematical Research Letters, European Journal of Mathematics.
- * :: Reviewed for Mathematical Reviews, American Mathematical Society.
- 2021-- :: Convener for the Masters program, Mathematical Sciences Institute, Australian National University.
- 2022 :: Co-organised the workshop /Braids in Symplectic and Algebraic Geometry/ Inanc Baykur, Benson Farb, Anthony Licata, and Ailsa Keating., Institute for Computational and Experimental Research in Mathematics (ICERM), Brown University.
- 2021 :: Served on the award committee for the /BH Neumann prize/ for the best student talk, AustMS meeting.
- 2020 :: Served on the thesis committee of Abhishek Bharadwaj, Mathematical Sciences Institute, Australian National University.
- 2019 :: Served on the selection committee for the /Future research talent fellowship/, Mathematical Sciences Institute, Australian National University.
- --- :: Served on the director search committee, Mathematical Sciences Institute, Australian National University.
- --- :: Served on the formal liaison committee, Mathematical Sciences Institute, Australian National University.
- 2018 :: Served on the award committee for the /BH Neumann prize/ for the best student talk, AustMS meeting.
- --- :: Co-organised the workshop /Polynomial Algebraic Developments in Optimisation and Computation/ Markus Hegland.
- --- :: Conducted training sessions in algebraic geometry at the /D21 Workshop/, Australian Signals Directorate.
- 2017 :: Co-organised the workshop /Stability and moduli spaces/ Maksym Fedorchuk, Ian Morrison, Xiaowei Wang, American Institute of Matheatics, Palo Alto, California.
- 2016 :: Co-organised the /Summer workshop in algebraic geometry/ Angela Gibney, Nicola Tarasca, University of Georgia, Athens, Georgia.
- --- :: Organised the /Fairly informal reading seminar and tea (FIRST)/, University of Georgia, Athens, Georgia.
- --- :: Co-organised the graduate student algebraic geometry seminar Johan de Jong, Columbia University.
- 2015 :: Conducted preparation sessions for the Putnam competition, Columbia University.
- 2014 :: Lectured in the /Workshop on birational geometry and stability of moduli stacks and spaces of curves/, Vietnam Institute for Advanced Studies in Mathematics, Hanoi, Vietnam.
- 2016 :: Served on the thesis committee of Natasha Potashnik, Columbia University, New York City, New York.
- 2013 :: Served on the thesis committee of Zachary Maddock, Columbia University, New York City, New York.
- 2014 :: Served on the thesis committee of Xuanyu Pan, Columbia University, New York City, New York.
- 2013 :: Co-organised the poster session at the /Algebraic geometry north-eastern series (AGNES)/ conference Anand Patel, Boston College.
- 2011, 2010 :: Organised the student algebraic geometry seminar, Harvard/MIT.
:end:
