:PROPERTIES:
:skip-in-backlinks:   t
:END:
#+TITLE: Anand Deopurkar | CV
#+AUTHOR: [[mailto:anand.deopurkar@anu.edu.au][~anand.deopurkar@anu.edu.au~]] \(\quad\) [[https://www.ananddeopurkar.org][~ananddeopurkar.org~]]
#+DESCRIPTION: Curriculum vitae of Anand Deopurkar, a mathematician specialising in algebraic geometry at the Australian National University.  Read about my academic history, publications, supervision, students, talks, teaching, and service activities. 
#+KEYWORDS: Curriculum vitae, CV, Anand Deopurkar, ANU, MSI
#+options: -:t num:nil toc:nil date:nil
#+LATEX_HEADER: \usepackage[margin=3cm]{geometry}
#+LATEX_HEADER_EXTRA: \hypersetup{hidelinks,colorlinks=false,urlcolor=black}
#+LATEX_HEADER_EXTRA: \usepackage{Baskervaldx}
#+LATEX_HEADER_EXTRA: \usepackage{marvosym}
#+HTML_HEAD_EXTRA: <script src="js/collapsibility.js"></script>
#+setupfile: #setup.org

* Positions
#+RESULTS:
:results:
- 2021-- :: Senior lecturer\\
      Australian National University, Canberra, Australia.
- 2018--2020 :: Lecturer\\
      Australian National University, Canberra, Australia.
- 2016--2017 :: Assistant professor (limited term)\\
      University of Georgia, Athens, Georgia, USA.
- 2012--2016 :: J. F. Ritt assistant professor\\
      Columbia University, New York City, New York, USA.
- 2008 :: Summer intern\\
      Microsoft Research, Bangalore, India.
:end:

* Education

#+RESULTS:
:results:
- 2012 :: Ph.D.\\
 Harvard University, Cambridge, Massachusetts, USA.\\
       /Alternate compactifications of Hurwitz spaces/, advisor: Joseph Harris.
- 2008 :: Bachelor of Science (S.B.)\\
 Massachusetts Institute of Technology, Cambridge, Massachusetts, USA.\\
       Mathematics with computer science.
:end:

* Grants and awards
#+begin_src elisp :exports results :results value raw drawer
    ;; Our pretty-printing function
    (defun pretty-print-grant ()
      (let ((title (org-entry-get nil "ITEM"))
    	(org (org-entry-get nil "org"))
    	(collaborators (org-entry-get nil "with"))
    	(year (org-entry-get nil "year")))
        (cons
         year
         (format
          "%s, %s%s."
          title
          org
          (if collaborators
    	  (format " (with %s)" collaborators)
    	"")
          ))))
  (strip-links-from-string
   (string-join
    (collate-from-string-pairs
     (org-map-entries 'pretty-print-grant "-nocv" '("#awards.org"))) "\n"))
#+end_src

#+RESULTS:
:results:
- 2024 :: Discovery project award (DP), Australian Research Council (with Asilata Bapat, Anthony Licata).
- 2018 :: Discovery early career researcher award (DECRA), Australian Research Council.
- 2016 :: AMS-Simons travel grant, American Mathematical Society and Simons Foundation.

          Workshop funding, American Institute of Mathematics (with Maksym Fedorchuk, Ian Morrison, Xiaowei Wang).
- 2014 :: Award for excellence in teaching, Columbia University, Mathematics department.
- 2006 :: Jon A. Bucsela prize for the top undergraduate, Massachusetts Institute of Technology, Mathematics department.

          Rogers family prize for undergraduate summer research, Massachusetts Institute of Technology, Mathematics department.
- 2007, 2005, 2004 :: Honorable mention (2004) , honorable mention (2005), rank 16--25 (2004), William Lowell Putnam competition.
:end:

* Publications 

#+begin_src elisp :exports results :results value raw drawer :lexical t
  ;; Our pretty-printing function
    (defun pretty-print-paper ()
      (let ((id (org-id-get-create))
  	  (title (org-entry-get nil "ITEM"))
            (year
  	   (format-time-string
  	    "%Y"
  	    (date-to-time (org-entry-get nil "when"))))
            (journal (org-entry-get nil "where"))
            (coauthors (org-entry-get nil "with"))
            (comment (org-entry-get nil "comments")))
        (cons
         year
         (format 
  	"/[[id:%s][%s]]/.\\\\\n          %s%s%s."
  	id
  	title
  	journal
          (if comment
              (format " (%s)" comment)
            "")
          (if coauthors
              (format " (with %s)" coauthors)
            "")
          ))))
  (strip-links-from-string
   (string-join
    (collate-from-string-pairs
     (org-map-entries 'pretty-print-paper "-preprint-expository-thesis" '("papers/index.org")))
    "\n"))
#+end_src



#+RESULTS:
:results:
- 2026 :: /The Thurston compactification of the stability manifold of a generic analytic K3 surface/.\\
          Mathematical Research Letters (accepted).

          /Equivariant classes of orbits in GL(2)-representations/.\\
          Selecta Mathematica (accepted).
- 2024 :: /Orbits of linear series on the projective line/.\\
          International Mathematics Research Notices (with Anand Patel).

          /A universal formula for counting cubic surfaces/.\\
          Algebraic Geometry (to appear) (with Anand Patel, Dennis Tseng).
- 2022 :: /Spherical objects and stability conditions on 2-Calabi--Yau quiver categories/.\\
          Mathematische Zeitschrift (with Asilata Bapat, Anthony Licata).

          /Vector bundles and finite covers/.\\
          Forum of Mathematics, Sigma (with Anand Patel).
- 2021 :: /Stable log surfaces, admissible covers, and canonical curves of genus 4/.\\
          Transactions of the Americal Mathematical Society (with Changho Han).
- 2020 :: /Ramification divisors of general projections/.\\
          Documenta Mathematica (with Eduard Duryev, Anand Patel).
- 2019 :: /Covers of stacky curves and limits of plane quintics/.\\
          Transactions of the Americal Mathematical Society.
- 2018 :: /Syzygy divisors on Hurwitz spaces/.\\
          Contemporary Mathematics (with Anand Patel).

          /The canonical syzygy conjecture for ribbons/.\\
          Mathematische Zeitschrift.
- 2016 :: /Toward GIT stability of syzygies of canonical curves/.\\
          Algebraic Geometry (with Maksym Fedorchuk, David Swinarski).
- 2015 :: /The Picard rank conjecture for the Hurwitz spaces of degree up to five/.\\
          Algebra & Number Theory (with Anand Patel).
- 2014 :: /Groebner techniques for ribbons/.\\
          Albanian Journal of Mathematics (with Maksym Fedorchuk, David Swinarski).

          /Compactifications of Hurwitz spaces/.\\
          International Mathematics Research Notices.
- 2013 :: /Sharp slope bounds for sweeping families of trigonal curves/.\\
          Mathematical Research Letters (with Anand Patel).

          /Modular compactifications of the space of marked trigonal curves/.\\
          Advances in Mathematics.
:end:

** Pre-prints
#+begin_src elisp :exports results :results value raw drawer
  (strip-links-from-string
   (string-join
    (collate-from-string-pairs
     (org-map-entries 'pretty-print-paper "+preprint" '("papers/index.org"))) "\n"))
#+end_src

#+RESULTS:
:results:
- 2025 :: /A sphere of spherical objects/.\\
          Pre-print (with Asilata Bapat, Anthony Licata).
- 2024 :: /Compactifications of moduli spaces of K3 surfaces with a higher-order nonsymplectic automorphism/.\\
          Pre-print (with Valery Alexeev, Changho Han).

          /Syzygies of canonical ribbons on higher genus curves/.\\
          Pre-print (with Jayan Mukherjee).

          /Counting 3-uple Veronese surfaces/.\\
          Pre-print (with Anand Patel).
- 2020 :: /A Thurston compactification of the space of stability conditions/.\\
          Pre-print (with Asilata Bapat, Anthony Licata).
- 2019 :: /Anticanonical tropical cubic del Pezzos contain exactly 27 lines/.\\
          Pre-print (with María Angélica Cueto).
- 2013 :: /Class of the Hodge eigenbundle using orbifold Riemann-Roch/.\\
          Pre-print, appendix to /Cyclic covering morphisms on \(\overline M_{0,n}\)/ by Maksym Fedorchuk.
:end:

** Expository
#+begin_src elisp :exports results :results value raw drawer
  (strip-links-from-string
   (string-join
    (collate-from-string-pairs
     (org-map-entries 'pretty-print-paper "+paper+expository" '("papers/index.org"))) "\n"))
#+end_src

#+RESULTS:
:results:
- 2025 :: /[[id:9efcc78f-db58-4c06-a73a-405566487ca4][The arithmetic and geometry of branched coverings: theorems of Belyi and Darmon--Granville]]/.\\
          Pre-print.
- 2010 :: /[[id:0f97be8d-e4d3-4515-bf1f-981c9e8380a0][An introduction to intersection homology]]/.\\
          Minor thesis (Harvard).
- 2008 :: /[[id:97f6df09-0591-49b7-97d0-e79b606af653][Normalization of algebraic varieties]]/.\\
          MIT Undergruate Journal of Mathematics.
:end:

* Supervision

#+begin_src elisp :exports results :results value raw drawer :lexical t
    ;; Our pretty-printing function
    (defun pretty-print-student ()
      (let ((name (org-entry-get nil "ITEM"))
            (year (format-time-string
    	       "%Y"
    	       (date-to-time
    		(org-entry-get nil "when"))))
            (level (org-entry-get nil "level"))
            (coadvisors (org-entry-get nil "with"))
            (comment (org-entry-get nil "comments")))
        (cons year
    	  (format
    	   "%s, %s%s%s."
               name
               level
               (if coadvisors
                   (concat " (with " coadvisors ")")
                 "")
               (if comment
                   (format " (%s)" comment)
                 "")))))

  (strip-links-from-string
   (string-join
    (collate-from-string-pairs
     (org-map-entries 'pretty-print-student t '("#supervision.org"))) "\n"))
#+end_src

#+RESULTS:
:results:
- 2026 :: Liam Murray, Honours (with [[sveta:][Sveta Makarova]]).
- ---- :: Frey Boulton, Honours.
- ---- :: James Porteous, Masters.
- 2025 :: Jialu Wang, Masters.
- 2024 :: Luke Doherty, Honours.
- ---- :: Charlotte Sherratt, Honours.
- 2023 :: Benedict Bawagan, Honours.
- ---- :: Leyao Zha, Honours.
- ---- :: Charles McIntosh, Honours.
- ---- :: Alex Huang, Summer Research Scholar (with Noah White).
- ---- :: Charlotte Sherratt, Summer Research Scholar (with Noah White).
- ---- :: Thomas Whitley, Summer Research Scholar (with Noah White).
- ---- :: Jia En Toh, Summer Research Scholar (with Noah White).
- 2022 :: Oliver Bradley, Honours.
- 2021 :: Zongpu Zhang, Honours.
- 2020 :: Ben Leedom, Honours.
- 2019 :: Diclehan Erdal, Masters.
- ---- :: Adwait Sengar, Masters (with Uri Onn).
- ---- :: Dhruva Kelkar, Future Research Scholar.
- ---- :: Sridhar Venkatesh, Future Research Scholar.
- 2018 :: Sean Carroll, Summer Research Scholar (with Asilata Bapat).
- ---- :: Kyle Broder, Honours (with Alex Isaev).
- ---- :: Likun Yao, Honours (with Amnon Neeman).
:end:

* Talks and presentations

#+begin_src elisp :exports results :results value raw drawer :lexical t
     ;; Our pretty-printing function
       (defun pretty-print-talk ()
         (let ((id (org-id-get-create))
     	     (year
     	      (format-time-string
     	       "%Y"
     	       (date-to-time
     		(org-entry-get nil "when"))))
  	     (venue (org-entry-get nil "venue"))
               (where (org-entry-get nil "where"))
               (comment (org-entry-get nil "comments"))
               (title (org-entry-get nil "ITEM")))
           (cons year
     	       (format "/[[id:%s][%s]]/.\n          %s, %s%s."
     		       id
     		       title
  		       venue
     		       where
     		       (if comment
     			   (format " (%s)" comment)
                           "")))))
  (strip-links-from-string
   (string-join
    (collate-from-string-pairs
     (org-map-entries 'pretty-print-talk nil '("#talks.org")))
    "\n"))
#+end_src

#+RESULTS:
:results:
- 2026 :: /[[id:nil][Be wise, equivariantise!]]/.
          Workshop in algebraic geometry, University of Sydney, Sydney, Australia.
- ---- :: /[[id:nil][How to count using equivariant cohomology]]/.
          Geometric and category-theoretic approaches to conformal field theory, Banff International Research Institute/Chennai Mathematical Institute, Chennai, India.
- 2025 :: /[[id:nil][A Thurston compactification of the space of stability conditions]]/.
          Teichmuller theory and flat structures, MATRIX, Creswick, Australia.
- ---- :: /[[id:nil][The enumerative geometry of orbit closures]]/.
          Pure mathematics seminar, University of Melbourne, Melbourne, Australia.
- 2024 :: /[[id:nil][How twisty is that orbit?]]/.
          Computations and applications of commutative algebra and algebraic geometry, NZMS-AustMS-AMS, Auckland, New Zealand.
- ---- :: /[[id:nil][The work of Maryam Mirzakhani]]/.
          Women in maths day, Australian National University, Canberra, Australia.
- ---- :: /[[id:nil][Papercraft]]/.
          ANU Mathematics Extension Program, Canberra, Australia.
- ---- :: /[[id:nil][The geometry of stability conditions]]/.
          Artin groups meet triangulated categories, Mathematisches Forschungsinstitut Oberwolfach, Oberwolfach, Germany.
- ---- :: /[[id:nil][How to count using equivariant cohomology]]/.
          Workshop on computational and applied algebraic geometry, Isaac Newton Institute, Cambridge, UK.
- ---- :: /[[id:nil][How to count using equivariant cohomology]]/.
          Imperial College, London, UK.
- ---- :: /[[id:nil][Stability conditions, metrics, and compactifications]]/.
          School of Mathematics, Edinburgh, UK.
- 2023 :: /[[id:nil][Stability conditions, metrics, and compactifications (lecture series)]]/.
          Summer school 2023 on algebraic geometry: derived categories, stability conditions, and moduli, Technion, Haifa, Israel.
- ---- :: /[[id:nil][Braids, automata, and the PL-sphere]]/.
          Braids: algebra and geometry, Australian National University, Canberra, Australia.
- 2022 :: /[[id:nil][Carpentry, geometry, and category theory]]/.
          Chennai Mathematical Institute, Chennai, India.
- ---- :: /[[id:nil][Error correcting codes]]/.
          ANU Mathematics Extension Program, Canberra, Australia.
- ---- :: /[[id:nil][How to count using equivariant cohomology]]/.
          Australian National University, Canberra, Australia.
- ---- :: /[[id:nil][Combinatorics and dynamics of Harder-Narasimhan filtrations]]/.
          Tsinghua University (Online), Beijing, China.
- ---- :: /[[id:nil][Braids and monodromy in algebraic geometry]]/.
          Braids in Symplectic and Algebraic Geometry, ICERM, Brown University, Providence, Rhode Island.
- ---- :: /[[id:nil][How to count using equivariant cohomology]]/.
          Harvard University, Cambridge, Massachusetts.
- ---- :: /[[id:nil][Apparent boundaries of projective varieties]]/.
          Brown University, Providence, Rhode Island.
- ---- :: /[[id:nil][The geometry and combinatorics of Harder--Narasimhan filtrations]]/.
          Braids in representation theory and algebraic combinatorics, Institute for Computational and Experimental Research in Mathematics, Providence, Rhode Island.
- ---- :: /[[id:nil][The geometry of Fermat-like equations]]/.
          Trimester program on triangle groups, Belyi uniformization, and modularity, Bhaskaracharya Pratishthana, Pune, India.
- 2021 :: /[[id:nil][Algebraic curves and Belyi's theorem]]/.
          Trimester program on triangle groups, Belyi uniformization, and modularity, Bhaskaracharya Pratishthana, Pune, India.
- ---- :: /[[id:nil][Error correcting codes]]/.
          ANU Mathematics Extension Program, Canberra, Australia.
- ---- :: /[[id:nil][A Thurston compactification of the space of stability conditions]]/.
          Workshop on compactifications of stability manifolds (Online), Max Planck institute für Mathematics, Bonn, Germany.
- ---- :: /[[id:nil][A Thurston compactification of the space of stability conditions]]/.
          Tata Institute of Fundamental Research (Online), Mumbai, India.
- ---- :: /[[id:nil][A Thurston compactification of the space of stability conditions]]/.
          Jagiellonian University (Online), Kraków, Poland.
- 2020 :: /[[id:nil][A Thurston compactification for categories]]/.
          Topology session, AustMS (Online), University of New England, Amidale, Australia.
- ---- :: /[[id:nil][Apparent boundaries of projective varieties]]/.
          Seminario nacional de geometria algebraica (Online joint seminar of multiple universities in Mexico), Oaxaca.
- ---- :: /[[id:nil][Apparent boundaries of projective varieties]]/.
          University of California (Online), San Diego, California.
- 2019 :: /[[id:nil][Groups, spherical twists, and stability conditions]]/.
          Workshop on triangulated categories in geometry and representation theory, University of Sydney, Sydney, Australia.
- ---- :: /[[id:nil][Log surfaces of almost K3 type and curves of genus 4]]/.
          Birational geometry and moduli spaces, University of Sydney, Sydney, Australia.
- ---- :: /[[id:nil][The work of Claire Voisin]]/.
          Women in mathematics day, Australian National University, Canberra, Australia.
- 2018 :: /[[id:nil][Geometry of Hurwitz spaces]]/.
          Character varieties and topological quantum field theory, University of Auckland, Auckland, New Zealand.
- ---- :: /[[id:nil][On the geometric Steinitz problem]]/.
          Number theory session,  AustMS, University of South Australia, Adelaide, Australia.
- ---- :: /[[id:nil][The work of Caucher Birkar]]/.
          Australian National University, Canberra, Australia.
- ---- :: /[[id:nil][Moduli of almost K3 log surfaces and curves of genus 4]]/.
          Algebraic surfaces and related topics, Xiamen University, Xiamen, China.
- ---- :: /[[id:nil][How to count using (co)homology]]/.
          Tata Institute of Fundamental Research, Mumbai, India.
- ---- :: /[[id:nil][What are ribbons and what do they tell us about Riemann surfaces]]/.
          Indian Institute of Science, Bengaluru, India.
- ---- :: /[[id:nil][What are ribbons and what do they tell us about Riemann surfaces]]/.
          Monash University, Melbourne, Australia.
- ---- :: /[[id:nil][On the critical loci of finite maps]]/.
          Australian National University, Canberra, Australia.
- ---- :: /[[id:nil][Quadrature and algebraic geometry]]/.
          Workshop on algebraic geometry approximation, and optimization, MATRIX, Creswick, Victoria, Australia.
- 2017 :: /[[id:nil][Vector bundles and finite covers]]/.
          Workshop on topics in algebraic geometry, University of North Carolina, Chapel Hill, North Carolina.
- ---- :: /[[id:nil][Vector bundles and finite covers]]/.
          University of Georgia, Athens, Georgia.
- ---- :: /[[id:nil][How to count using topology]]/.
          Canada/USA Mathcamp, Tacoma, WA.
- ---- :: /[[id:nil][Quivers and their representations]]/.
          Indian Institute of Science Education and Research, Pune, India.
- ---- :: /[[id:nil][Vector bundles and finite covers]]/.
          Emory University, Atlanta, Georgia.
- 2016 :: /[[id:nil][Geometry of moduli spaces]]/.
          Australian National University, Canberra, Australia.
- ---- :: /[[id:nil][Vector bundles and finite covers]]/.
          Conference on moduli and birational geometry, Jeju Island, South Korea.
- ---- :: /[[id:nil][Vector bundles and finite covers]]/.
          Indian Institute of Science Education and Research, Pune.
- ---- :: /[[id:nil][Ribbons and Green's conjecture]]/.
          University of South Carolina, Columbia, South Carolina.
- ---- :: /[[id:nil][Ribbons and Green's conjecture]]/.
          University of Georgia, Athens, Georgia.
- ---- :: /[[id:nil][Cycles on Hurwitz spaces]]/.
          Workshop on cycles on moduli spaces, geometric invariant theory, and dynamics, Institute for Computational and Experimental Research in Mathematics, Providence, Rhode Island.
- ---- :: /[[id:nil][The algebra of canonical curves and the geometry of their moduli space]]/.
          University of Georgia, Athens, Georgia.
- ---- :: /[[id:nil][Picard groups of Hurwitz spaces]]/.
          Higher genus curves and fibrations of higher genus curves in mathematical physics and arithmetic geometry II, AMS joint mathematics meetings, Seattle, Washington.
- ---- :: /[[id:nil][Limits of plane quintics via covers of stacky curves]]/.
          Moduli spaces in algebraic geometry I, AMS joint mathematics meetings, Seattle, Washington.
- 2015 :: /[[id:nil][Limits of plane quintics via covers of stacky curves]]/.
          Boston College--Northeastern algebraic geometry conference, Northeastern University, Boston, Massachusetts.
- ---- :: /[[id:nil][Limits of plane quintics via covers of stacky curves]]/.
          Summer institute in algebraic geometry, University of Utah, Salt Lake City, Utah.
- ---- :: /[[id:nil][Syzygies of canonical curves and the geometry of \(\overline M_g\)]]/.
          SIAM applied algebraic geometry conference, Daejeon, South Korea.
- ---- :: /[[id:nil][GIT stability of syzygies of curves]]/.
          Classical Algebraic Geometry, Mathematisches Forschungsinstitut Oberwolfach, Oberwolfach, Germany.
- ---- :: /[[id:nil][Syzygies, GIT, and the moduli space of curves]]/.
          Purdue University, West Lafayette, Indiana.
- ---- :: /[[id:nil][Limits of plane curves via stacky branched covers]]/.
          Ohio State University, Columbus, Ohio.
- ---- :: /[[id:nil][Syzygies, GIT, and the log minimal model program for \(\overline{M}_g\)]]/.
          Harvard University, Cambridge, Massachusetts.
- ---- :: /[[id:nil][Picard groups of Hurwitz spaces]]/.
          Courant Institute, New York University, New York City, New York.
- ---- :: /[[id:nil][The birational geometry of \(\overline M_g\)]]/.
          Indian Institute for Science Research and Education, Pune, India.
- ---- :: /[[id:nil][Syzygies of canonical curves and birational geometry of \(\overline M_g\)]]/.
          Stony Brook University, Stony Brook, New York.
- 2014 :: /[[id:nil][GIT stability of syzygies of canonical curves]]/.
          University of Michigan, Ann Arbor, Michigan.
- ---- :: /[[id:nil][GIT stability of syzygies of canonical curves]]/.
          Yale University, New Haven, Connecticut.
- ---- :: /[[id:nil][Towards GIT stability of syzygies of canonical curves]]/.
          Boston College, Boston, Massachusetts.
- 2013 :: /[[id:nil][Towards GIT stability of syzygies of canonical curves]]/.
          Postech, Pohang, Korea.
- ---- :: /[[id:nil][Towards GIT stability of syzygies of canonical curves]]/.
          Geometry of algebraic varieties, AMS sectional meeting, Philadelphia, Pennsylvania.
- ---- :: /[[id:nil][Sharp slope bounds for sweeping families of trigonal curves]]/.
          Algebraic geometry northeastern series, Boston College, Boston, Massachusetts.
- ---- :: /[[id:nil][Alternate compactifications of Hurwitz spaces]]/.
          Stanford University, Palo Alto, California.
- ---- :: /[[id:nil][Compactifying spaces of branched covers]]/.
          Princeton University, Princeton, New Jersey.
- 2012 :: /[[id:nil][Alternate compactifications of Hurwitz spaces]]/.
          Rice University, Houston, Texas.
- 2011 :: /[[id:nil][Compactifications of Hurwitz spaces]]/.
          Massachusetts Institute of Technology, Cambridge, Massachusetts.
- ---- :: /[[id:nil][Compactifications of Hurwitz spaces]]/.
          Columbia University, New York City, New York.
- ---- :: /[[id:nil][Compactifications of Hurwitz spaces]]/.
          Stony Brook University, Stony Brook, New York.
- ---- :: /[[id:nil][Compactifications of Hurwitz spaces]]/.
          Brown University, Providence, Rhode Island.
- ---- :: /[[id:nil][Birational geometry of the space of marked trigonal curves]]/.
          A celebration of algebraic geometry: a conference for the 60th birthday of Joe Harris, Harvard University, Cambridge, Massachusetts.
:end:

* Service

#+begin_src elisp :exports results :results value raw drawer :lexical t
  ;; Our pretty-printing function
  (defun pretty-print-service ()
    (let ((title (org-entry-get nil "ITEM"))
          (year (org-entry-get nil "when"))
          (with (org-entry-get nil "with"))
          (where (org-entry-get nil "where")))
      (cons
       (or year "Ongoing")
       (format "%s%s%s"
       title
       (if with
           (format " %s" with)
         "")
       (if where
           (format ", %s" where)
         "")
       ))))
  (strip-links-from-string
   (string-join
    (collate-from-string-pairs
     (org-map-entries 'pretty-print-service nil '("#service.org")))
    "\n"))
#+end_src

#+RESULTS:
:results:
- Ongoing :: Refereed for Journal of the European Mathematical Society, Journal of Differential Geometry, Journal of Algebraic Geometry, Annales Scientifiques de l'École Normale Supérieure, Mathematische Annalen, Algebra and Number Theory, Journal für die reine und angewandte Mathematik, manuscripta mathematica, Advances in Geometry, Mathematical Research Letters, European Journal of Mathematics, Journal de l'École polytechnique — Mathématiques, Experimental mathematics

             Reviewed for Mathematical Reviews, American Mathematical Society
- 2021 onwards :: Convener for the Masters program, Mathematical Sciences Institute, Australian National University
- 2025 :: Served on the PhD thesis committee of Snehinh Sen, Mathematical Sciences Institute, Australian National University

          Served on the PhD thesis committee of Alexander Lai De Oliveira, Mathematical Sciences Institute, Australian National University

          Served on the PhD thesis committee of Seethalakshmi Kayanattath, Mathematical Sciences Institute, Australian National University

          Served on the PhD thesis committee of Lucas Allen, Mathematical Sciences Institute, Australian National University

          Headed the selection committee for the /Future research talent fellowship/, Australian National University

          Served on the PhD thesis committee of Kabeer Manali Rahul, Australian National University
- 2024 :: Co-organised the session /Computations and applications of commutative algebra and algebraic geometry/ at the joint /NZMS-AustMS-AMS/ meeting John Cobb, Sione Ma'u, and Hal Schenk, University of Auckland
- 2022 :: Co-organised the workshop /Braids in Symplectic and Algebraic Geometry/ Inanc Baykur, Benson Farb, Anthony Licata, and Ailsa Keating, Institute for Computational and Experimental Research in Mathematics (ICERM), Brown University
- 2021 :: Served on the award committee for the /BH Neumann prize/ for the best student talk, AustMS meeting
- 2020 :: Served on the PhD thesis committee of Abhishek Bharadwaj, Mathematical Sciences Institute, Australian National University

          Served on the MPhil thesis committee of Ivan Zelich, Mathematical Sciences Institute, Australian National University
- 2019 :: Served on the selection committee for the /Future research talent fellowship/, Mathematical Sciences Institute, Australian National University

          Served on the director search committee, Mathematical Sciences Institute, Australian National University

          Served on the formal liaison committee, Mathematical Sciences Institute, Australian National University
- 2018 :: Served on the PhD thesis committee of Edmund Heng, Mathematical Sciences Institute, Australian National University

          Served on the award committee for the /BH Neumann prize/ for the best student talk, AustMS meeting

          Co-organised the workshop /Polynomial Algebraic Developments in Optimisation and Computation/ Markus Hegland

          Conducted training sessions in algebraic geometry at the /D21 Workshop/, Australian Signals Directorate
- 2017 :: Co-organised the workshop /Stability and moduli spaces/ Maksym Fedorchuk, Ian Morrison, Xiaowei Wang, American Institute of Matheatics, Palo Alto, California
- 2016 :: Co-organised the /Summer workshop in algebraic geometry/ Angela Gibney, Nicola Tarasca, University of Georgia, Athens, Georgia

          Organised the /Fairly informal reading seminar and tea (FIRST)/, University of Georgia, Athens, Georgia

          Co-organised the graduate student algebraic geometry seminar Johan de Jong, Columbia University
- 2015 :: Conducted preparation sessions for the Putnam competition, Columbia University
- 2014 :: Lectured in the /Workshop on birational geometry and stability of moduli stacks and spaces of curves/, Vietnam Institute for Advanced Studies in Mathematics, Hanoi, Vietnam
- 2016 :: Served on the PhD thesis committee of Natasha Potashnik, Columbia University, New York City, New York
- 2013 :: Served on the PhD thesis committee of Zachary Maddock, Columbia University, New York City, New York
- 2014 :: Served on the PhD thesis committee of Xuanyu Pan, Columbia University, New York City, New York
- 2013 :: Co-organised the poster session at the /Algebraic geometry north-eastern series (AGNES)/ conference Anand Patel, Boston College
- 2011, 2010 :: Organised the student algebraic geometry seminar, Harvard/MIT
:end:
