#+setupfile: #setup.org
#+title: Anand Deopurkar | Papers and preprints
#+DESCRIPTION: Papers and preprints of Anand Deopurkar, a mathematician specialising in algebraic geometry at the Australian National University.  Read about my papers and preprints, including abstracts.
#+KEYWORDS: Papers, preprints, Anand Deopurkar, ANU, MSI
#+options: H:1 num:0 toc:nil

* A sphere of spherical objects :preprint:
:PROPERTIES:
:where:    Pre-print
:with:     [[asilata:][Asilata Bapat]], [[tony:][Anthony Licata]]
:when:     2025
:links:    [[file:papers/spherical-sphere.pdf][pdf,]] [[https://arxiv.org/abs/2509.13912][arxiv]]
:ID:       1245acba-aa78-4ab6-ad92-fb1c2c46b5c6
:END:

* The arithmetic and geometry of branched coverings: theorems of Belyi and Darmon--Granville :expository:paper:
:PROPERTIES:
:where: Pre-print
:when:     2025
:links: [[file:papers/arithmetic_covers.pdf][pdf]]
:ID:       9efcc78f-db58-4c06-a73a-405566487ca4
:END:

* The Thurston compactification of the stability manifold of a generic analytic K3 surface :paper:
:PROPERTIES:
:where:  Mathematical Research Letters (accepted)
:when:     2026
:links: [[file:papers/CompStabGenK3.pdf][pdf]], [[https://github.com/deopurkar/CompStabGenK3][repository]]
:ID:       991da63b-3869-43c6-ae34-3cfb65a88e1e
:END:

* Compactifications of moduli spaces of K3 surfaces with a higher-order nonsymplectic automorphism :preprint:
:PROPERTIES:
:with: [[valery:][Valery Alexeev]], [[changho:][Changho Han]]
:where:  Pre-print
:when:     2024
:links: [[file:papers/k3z3.pdf][pdf]], [[https://arxiv.org/abs/2412.11256][arxiv]]
:ID:       fe485808-abd5-47a3-8989-33302bddd1f1
:END:


* Syzygies of canonical ribbons on higher genus curves :preprint:
:PROPERTIES:
:with: [[jayan:][Jayan Mukherjee]]
:where:  Pre-print
:when:     2024
:links: [[file:papers/highergenusribbons.pdf][pdf]], [[https://arxiv.org/abs/2412.05500][arxiv]]
:ID:       c6c78ad7-7a03-4b03-95d8-ab4cd5450fb8
:END:

* Counting 3-uple Veronese surfaces :preprint:
:PROPERTIES:
:with: [[anandpatel:][Anand Patel]]
:where:  Pre-print
:when: 2024
:links: [[file:papers/3veroneseP2.pdf][pdf]], [[https://arxiv.org/abs/2411.14232][arxiv]]
:ID:       83eab6f9-e798-499b-bff5-cdea76b092c8
:END:

* Equivariant classes of orbits in GL(2)-representations              :paper:
:PROPERTIES:
:where:  Selecta Mathematica (accepted)
:when:     2026
:links: [[file:papers/gl2orbits.pdf][pdf]], [[https://arxiv.org/abs/2405.09849][arxiv]], [[https://github.com/deopurkar/equivariant-classes-of-gl2-orbits/][repository]]
:ID:       b1ba9384-4b6a-47b1-888c-61cc0c828493
:END:
#+begin_abstract
We compute equivariant fundamental classes of orbits in GL(2)-representations. As applications, we find degrees of the orbit closures corresponding to elliptic fibrations and self-maps of the projective line.
#+end_abstract

* Orbits of linear series on the projective line                      :paper:
:PROPERTIES:
:with:     [[anandpatel:][Anand Patel]]
:where:  International Mathematics Research Notices
:when:     2024
:links: [[file:papers/erc.pdf][pdf]],[[https://arxiv.org/abs/2211.16603][ arxiv]], [[https://doi.org/10.1093/imrn/rnae169][journal]]
:ID:       e4f6d1ab-1a2b-4def-bbbd-092960a347f1
:END:
We compute the equivariant fundamental class of the orbit closure of a linear series on the projective line.  We also describe the boundary of the orbit closure and how the orbits specialise in one parameter families.

* A universal formula for counting cubic surfaces                     :paper:
:PROPERTIES:
:with:     [[anandpatel:][Anand Patel]], [[dennistseng:][Dennis Tseng]]
:where:  Algebraic Geometry (to appear)
:when:     2024
:links: [[file:papers/countingcubics.pdf][pdf]], [[https://arxiv.org/abs/2109.12672][arxiv]]
:ID:       aa908035-6504-4bd7-8a1d-aecf14f07383
:END:
Using equivariant geometry, we find a universal formula that computes the number of times a general cubic surface arises in a family. As applications, we show that the PGL(4) orbit closure of a generic cubic surface has degree 96120, and that a general cubic surface arises 42120 times as a hyperplane section of a general cubic 3-fold.

* Spherical objects and stability conditions on 2-Calabi--Yau quiver categories :paper:
:PROPERTIES:
:with:     [[asilata:][Asilata Bapat]], [[tony:][Anthony Licata]]
:where:  Mathematische Zeitschrift
:when:     2022
:links: [[file:papers/2cy-algorithm.pdf][pdf]],[[https://arxiv.org/abs/2108.09155][ arxiv]], [[https://link.springer.com/article/10.1007/s00209-022-03172-8][journal]]
:ID:       8c1b044d-82a9-4cbc-986e-a07f93dc93d1
:END:
Consider a 2-Calabi--Yau triangulated category with a Bridgeland stability condition. We devise an effective procedure to reduce the phase spread of an object by applying spherical twists. Using this, we give new proofs of the following theorems for 2-Calabi--Yau categories associated to ADE quivers: (1) all spherical objects lie in a single orbit of the braid group, and (2) the space of Bridgeland stability conditions is connected.

* Vector bundles and finite covers                                    :paper:
:PROPERTIES:
:with:     [[anandpatel:][Anand Patel]]
:where:  Forum of Mathematics, Sigma
:when:     2022
:links: [[file:papers/ebundle.pdf][pdf]], [[https://arxiv.org/abs/1608.01711/][arXiv]], [[https://www.cambridge.org/core/services/aop-cambridge-core/content/view/21EB07C62F7A142F5CC39EF3950C2231/S2050509422000196a.pdf/vector_bundles_and_finite_covers.pdf][journal]]
:ID:       4b773769-0ca6-42a8-a8e6-309dd23ffa5c
:END:
Motivated by the problem of finding algebraic constructions of finite coverings in commutative algebra, the Steinitz realization problem in number theory, and the study of Hurwitz spaces in algebraic geometry, we investigate the vector bundles underlying the structure sheaf of a finite flat branched covering. We prove that, up to a twist, every vector bundle on a smooth projective curve arises from the direct image of the structure sheaf of a smooth, connected branched cover.

* Stable log surfaces, admissible covers, and canonical curves of genus 4 :paper:
:PROPERTIES:
:with:     [[changho:][Changho Han]]
:where:  Transactions of the Americal Mathematical Society
:when:     2021
:links: [[file:papers/TrigonalKSBA.pdf][pdf]],[[https://arxiv.org/abs/1807.08413/][ arxiv]], [[https://www.ams.org/journals/tran/2021-374-01/S0002-9947-2020-08225-7/?active=current][journal]]
:ID:       f7400180-00b7-4b54-a902-8941b3bd3823
:END: 
We describe a compactification of the moduli space of pairs (S,C) where S is a smooth quadric surface in 3-space and C is a smooth divisor on S of class (3,3). We show that the compactified moduli space is a smooth Deligne-Mumford stack with 4 boundary components. We relate our compactification with compactifications of the moduli space of genus 4 curves. In particular, we show that our space compactifies the blow-up of the hyperelliptic locus. We also relate our compactification to a compactification of the Hurwitz space of triple coverings of the projective line by genus 4 curves.

* A Thurston compactification of the space of stability conditions       :preprint:
:PROPERTIES:
:with:     [[asilata:][Asilata Bapat]], [[tony:][Anthony Licata]]
:where:  Pre-print
:when:     2020
:links: [[file:papers/a2-compactification.pdf][pdf]], [[https://arxiv.org/abs/2011.07908][arxiv]]
:ID:       7ee039fe-461d-41bb-8a73-116bc7f196e0
:END:
  We propose compactifications of the moduli space of Bridgeland stability conditions of a triangulated category.
  Our construction arises from a viewing a stability condition as a metric on the underlying category and is inspired by the Thurston compactification of the Teichm\"uller space of hyperbolic metrics on a surface.
  The key ingredient in the construction are maps from the stability manifold to an infinite projective space.
  We prove that, under suitable hypotheses, these maps are injective and their image has a compact closure.
  We identify a family of points in the boundary that are categorical analogous to the intersection functionals in Teichm\"uller theory.

  We study in detail the geometry of the resulting compactification for the 2-Calabi--Yau categories of quivers, and fully work out the cases of the \(A_2\) and \(\widehat{A_1}\) quivers.
  To do so, we carefully examine the dynamics of Harder--Narasimhan multiplicities under auto-equivalences of the category.
  We introduce a finite automaton to study this dynamics and employ it in our analysis of the \(A_{2}\) and \(\widehat{A_1}\) categories.


* Ramification divisors of general projections                        :paper:
:PROPERTIES:
:with:     [[eduardduryev:][Eduard Duryev]], [[anandpatel:][Anand Patel]]
:where:  Documenta Mathematica
:when:     2020
:links: [[file:papers/PR.pdf][pdf]], [[http://arxiv.org/abs/1901.01513/][arxiv]], [[https://ems.press/journals/dm/articles/8965720][journal]]
:ID:       82e9302f-6674-41b8-97cd-6733ac7edf89
:END:
We study the ramification divisors of projections of a smooth projective variety onto a linear subspace of the same dimension. We prove that the ramification divisors vary in a maximal dimensional family for a large class of varieties. Going further, we study the map that associates to a linear projection its ramification divisor. We show that this map is dominant for most (but not all!) varieties of minimal degree, using (linked) limit linear series of higher rank. We find the degree of this map in some cases, extending the classical appearance of Catalan numbers in the geometry of rational normal curves, and give a geometric explanation of its fibers in terms of torsion points of naturally occurring elliptic curves in the case of the Veronese surface and the quartic rational surface scroll.

* Anticanonical tropical cubic del Pezzos contain exactly 27 lines       :preprint:
:PROPERTIES:
:with:     [[mariacueto:][María Angélica Cueto]]
:where:  Pre-print
:when:     2019
:links: [[file:papers/lines_on_tropical_cubics.pdf][pdf]], [[https://arxiv.org/abs/1906.08196][arxiv]]
:ID:       931c8753-71af-4498-89fe-5823ae74d1e9
:END:
The classical statement of Cayley-Salmon that there are 27 lines on every smooth cubic surface in P^3 fails to hold under tropicalization: a tropical cubic surface in TP^3 often contains infinitely many tropical lines. Under mild genericity assumptions, we show that when embedded using the Eckardt triangles in the anticanonical system, tropical cubic del Pezzo surfaces contain exactly 27 tropical lines. In the non-generic case, which we identify explicitly, we find up to 27 extra lines, no multiple of which lifts to a curve on the cubic surface. We realize the moduli space of stable anticanonical tropical cubics as a four-dimensional fan in R^40 with an action of the Weyl group W(E_6). In the absence of Eckardt points, we show the combinatorial types of these tropical surfaces are determined by the boundary arrangement of 27 metric trees corresponding to the tropicalization of the classical 27 lines on the smooth algebraic cubic surfaces. Tropical convexity and the combinatorics of the root system E_6 play a central role in our analysis.

* Covers of stacky curves and limits of plane quintics                :paper:
:PROPERTIES:
:where:  Transactions of the Americal Mathematical Society
:when:     2019
:links: [[file:papers/StackyAdmissibleCovers.pdf][pdf]], [[http://arxiv.org/abs/1507.03252/][arxiv]], [[https://www.ams.org/journals/tran/2019-371-01/S0002-9947-2018-07301-9/home.html][journal]]
:ID:       1d0dda32-8233-4fd8-8303-a6d7e16dc0cc
:END:
We construct a well-behaved compactification of the space of finite covers of a stacky curve using admissible cover degenerations. Using our construction, we compactify the space of tetragonal curves on Hirzebruch surfaces. As an application, we explicitly describe the boundary divisors of the closure in \(\overline{M}_6\) of the locus of smooth plane quintic curves.

* Syzygy divisors on Hurwitz spaces                                   :paper:
:PROPERTIES:
:with:     [[anandpatel:][Anand Patel]]
:where:  Contemporary Mathematics
:when:     2018
:links: [[file:papers/HigherMaroni.pdf][pdf]], [[https://arxiv.org/abs/1805.00648][arxiv]], [[https://www.ams.org/books/conm/703/14139][journal]]
:ID:       e4a32e17-c28b-45a2-bfb1-8622e151af99
:END:
We describe a sequence of effective divisors on the Hurwitz space H(d,g) for d dividing g-1 and compute their cycle classes on a partial compactification. These divisors arise from vector bundles of syzygies canonically associated to a branched cover. We find that the cycle classes are all proportional to each other.

* The canonical syzygy conjecture for ribbons                         :paper:
:PROPERTIES:
:where:  Mathematische Zeitschrift
:when:     2018
:links: [[file:papers/RibbonGreen.pdf][pdf]], [[http://arxiv.org/abs/1510.07755/][arxiv]]
:ID:       c399a596-99cb-41bc-945b-a2846c40757e
:END:
We prove the analogue for ribbons of Green\'s canonical syzygy conjecture, formulated by Bayer and Eisenbud. Our proof uses the results of Voisin and Hirschowitz-Ramanan on Green\'s conjecture for general smooth curves.

* Toward GIT stability of syzygies of canonical curves                :paper:
:PROPERTIES:
:with:     [[maksym:][Maksym Fedorchuk]], [[davidswinarski:][David Swinarski]]
:where:  Algebraic Geometry
:when:     2016
:links: [[file:papers/gitsyzygy.pdf][pdf]], [[http://arxiv.org/abs/1401.6101/][arxiv]], [[http://www.algebraicgeometry.nl/2016-1/2016-1-001.pdf][journal]]
:ID:       800287ce-183c-42d7-ad07-0f73202dc7c3
:END:
We introduce the problem of GIT stability for syzygy points of canonical curves with a view toward a GIT construction of the canonical model of the moduli space of stable curves. As the first step in this direction, we prove semi-stability of the first syzygy point for a general canonical curve of odd genus. 

* The Picard rank conjecture for the Hurwitz spaces of degree up to five :paper:
:PROPERTIES:
:with:     [[anandpatel:][Anand Patel]]
:where:  Algebra & Number Theory
:when:     2015
:links: [[file:papers/PicH345.pdf][pdf]], [[http://arxiv.org/abs/1401.6101/][arxiv]], [[http://msp.org/ant/2015/9-2/p05.xhtml][journal]]
:ID:       e0e0aebf-32c6-4041-95d5-16574e6c0513
:END:
We prove that the rational Picard group of the simple Hurwitz space H_{d,g} is trivial for d up to five. We also relate the rational Picard groups of the Hurwitz spaces to the rational Picard groups of the Severi varieties of nodal curves on Hirzebruch surfaces.

* Groebner techniques for ribbons                                     :paper:
:PROPERTIES:
:with:     [[maksym:][Maksym Fedorchuk]], [[davidswinarski:][David Swinarski]]
:where:  Albanian Journal of Mathematics
:when:     2014
:links: [[file:papers/groebner.pdf][pdf]], [[https://sites.google.com/site/albjmath/archives/vol-8/2014-6][journal]]
:ID:       b355cfa4-8d4b-4110-93f7-f85699fe3e36
:END:
We use Groebner basis techniques to study the balanced canonical ribbon in each odd genus g \geq 5. We obtain equations and syzygies of the ribbon, give a Groebner interpretation of part of Alper, Fedorchuk, and Smyth\'s proof of finite Hilbert stability for canonical curves, and discuss the obstacles in using ribbons to give a new proof of Generic Green\'s Conjecture (Voisin\'s Theorem).

* Compactifications of Hurwitz spaces                                 :paper:
:PROPERTIES:
:where:  International Mathematics Research Notices
:when:     2014
:links: [[file:papers/CompHurwitz.pdf][pdf]], [[http://arxiv.org/abs/1206.4535/][arxiv]], [[http://imrn.oxfordjournals.org/content/early/2013/04/08/imrn.rnt060.abstract][journal]]
:ID:       504645b5-633e-42dd-9727-2c83fd1bb8d3
:END:

* Class of the Hodge eigenbundle using orbifold Riemann-Roch            :preprint:
:PROPERTIES:
:where:  Pre-print, appendix to [[https://drive.google.com/file/d/1wq-Fh3DiqODc51t-J0phIexVF7B4lxsY/view][/Cyclic covering morphisms on \(\overline M_{0,n}\)/]] by [[https://www2.bc.edu/maksym-fedorchuk/][Maksym Fedorchuk]]
:when:     2013
:links: [[file:papers/CyclicAppendix.pdf][pdf]]
:ID:       3b6a466e-3eef-4ba3-9515-07dcf2a34e83
:END:
We algebraically compute the class of the Hodge eigenbundles in the cyclic covering construction using Grothendieck-Riemann-Roch for stacks.

* Sharp slope bounds for sweeping families of trigonal curves         :paper:
:PROPERTIES:
:with:     [[anandpatel:][Anand Patel]]
:where:  Mathematical Research Letters
:when:     2013
:links: [[file:papers/TrigonalSlopes.pdf][pdf]], [[http://arxiv.org/abs/1211.2827/][arxiv]], [[http://www.intlpress.com/site/pub/pages/journals/items/mrl/content/vols/0020/0005/a005/][journal]]
:ID:       75d3ebc0-1174-40e1-9ec5-a949bad877de
:END:
We establish sharp bounds for the slopes of curves in \(\overline{M}_g\) that sweep the locus of trigonal curves, proving Stankova-Frenkel\'s conjectured bound of 7+6/g for even g and obtaining the bound 7+20/(3g+1) for odd g. For even g, we find an explicit expression of the so-called Maroni divisor in the Picard group of the space of admissible triple covers. For odd g, we describe the analogous extremal effective divisor and give a similar explicit expression. 

* Modular compactifications of the space of marked trigonal curves    :paper:
:PROPERTIES:
:where:  Advances in Mathematics
:when:     2013
:links: [[file:papers/MarkedTrigonal.pdf][pdf]], [[http://arxiv.org/abs/1206.4503/][arxiv]], [[https://www.sciencedirect.com/science/article/pii/S0001870813002776][journal]]
:ID:       833f39b4-0d38-4903-8356-aac9fc2b16d0
:END:
We construct a sequence of modular compactifications of the space of marked trigonal curves by allowing the branch points to coincide to a given extent. Beginning with the standard admissible cover compactification, the sequence first proceeds through contractions of the boundary divisors and then through flips of the so-called Maroni strata, culminating in a Fano model for even genera and a Fano fibration for odd genera. While the sequence of divisorial contractions arises from a more general construction, the sequence of flips uses the particular geometry of triple covers. We explicitly describe the Mori chamber decomposition given by this sequence of flips.

* Alternate compactifications of Hurwitz spaces                      :thesis:
:PROPERTIES:
:where:  PhD Thesis (Harvard)
:when:     2012
:links: [[file:papers/thesis.pdf][pdf]]
:ID:       5da2ae43-0723-4518-87a0-08743399185a
:END:

* An introduction to intersection homology                 :expository:paper:
:properties:
:where:  Minor thesis (Harvard)
:when:     2010
:links: [[file:papers/anandrd_minor_thesis.pdf][pdf]]
:ID:       0f97be8d-e4d3-4515-bf1f-981c9e8380a0
:end:

* Normalization of algebraic varieties                     :expository:paper:
:properties:
:where:  MIT Undergruate Journal of Mathematics
:when:     2008
:links: [[file:papers/anandrd_ug_thesis.pdf][pdf]]
:ID:       97f6df09-0591-49b7-97d0-e79b606af653
:end:

