:PROPERTIES:
:ID:       a6749683-bec2-4679-b454-ef4c1ebcde5e
:END:
#+setupfile:#setup.org
#+title: Papers and preprints
#+DESCRIPTION: Papers and preprints of Anand Deopurkar, a mathematician specialising in algebraic geometry at the Australian National University.  Read about my papers and preprints, including abstracts.
#+KEYWORDS: Papers, preprints, Anand Deopurkar, ANU, MSI
#+options: H:1 num:0 toc:nil

Below is a roughly reverse chronological list of my papers and pre-prints, together with abstracts and sometimes other commentary. 

* A sphere of spherical objects :preprint:
:PROPERTIES:
:where:    Pre-print
:with:     [[asilata:][Asilata Bapat]], [[tony:][Anthony Licata]]
:when:     2025
:links:    [[file:papers/spherical-sphere.pdf][pdf,]] [[https://arxiv.org/abs/2509.13912][arxiv]]
:ID:       1245acba-aa78-4ab6-ad92-fb1c2c46b5c6
:END:
#+begin_abstract
  Given a Bridgeland stability condition on a 2-Calabi--Yau category, we define a simplicial complex that encodes the Harder--Narasimhan filtrations of spherical objects.
  For 2-Calabi--Yau categories of type \(A\), we relate this complex to the complex of pointed pseudo-triangulations on configurations of points on the plane.
  Using this connection, we prove that the complex undergoes piecewise-linear wall-crossings as we vary the stability condition, and is piecewise-linearly homeomorphic to a sphere.

  Additionally, we prove that for a generic stability condition on a 2-Calabi--Yau category, a spherical object is determined by the ordered list of its Harder--Narasimhan factors.
#+end_abstract

In other words, the Harder--Narasimhan multiplicities act as coordinates for spherical objects.  These coordinates reveal that the set of all spherical objects has an underlying geometry.  

This phenomenon is very much related to our construction in the [[id:7ee039fe-461d-41bb-8a73-116bc7f196e0][Thurston compactification paper]].  Indeed, the spherical objects appear on the boundary of the projectivised stability manifold.  So it's no surprise that they have a geometric structure.  But from a pure homological algebra point-of-view, it does seems surprising.

The key question is---how general is this phenomenon?  We expect something similar for 2-CY categories of more general graphs.  But should we expect something even beyond?   

* The arithmetic and geometry of branched coverings: theorems of Belyi and Darmon--Granville :expository:preprint:highlight:
:PROPERTIES:
:where: Pre-print
:when:     2025
:links: [[file:papers/arithmetic_covers.pdf][pdf]]
:ID:       9efcc78f-db58-4c06-a73a-405566487ca4
:comments: expository
:labels: [[id:05f9493f-833e-4f64-a2b5-321a11c91a3b][expository]]
:END:

This is an exposition of two talks I gave (online) at the /Year long Trimester Programme on Triangle Group, Belyi Uniformisation and Modularity/ at the Bhaskaracharya Pratishthana in Pune (India).  

* The Thurston compactification of the stability manifold of a generic analytic K3 surface :paper:
:PROPERTIES:
:where:  Mathematical Research Letters (accepted)
:when:     2026
:links: [[file:papers/CompStabGenK3.pdf][pdf]], [[https://github.com/deopurkar/CompStabGenK3][repository]]
:ID:       991da63b-3869-43c6-ae34-3cfb65a88e1e
:END:

#+begin_abstract
Let \(X\) be an analytic K3 surface with \(\operatorname{Pic} X = 0\).
We describe the closure of the Bridgeland stability manifold of \(X\) obtained using the masses of semi-rigid objects.
#+end_abstract

The picture is very clean: the projectivised stability manifold is an open disk and the boundary is a circle.  As expected from our [[id:7ee039fe-461d-41bb-8a73-116bc7f196e0][Thurston compactifications paper]], the unique spherical object \(O_X\) appears on the boundary.  The \(q\)-analogous picture is a little bit more involved.

* Compactifications of moduli spaces of K3 surfaces with a higher-order nonsymplectic automorphism :preprint:
:PROPERTIES:
:with: [[valery:][Valery Alexeev]], [[changho:][Changho Han]]
:where:  Pre-print
:when:     2024
:links: [[file:papers/k3z3.pdf][pdf]], [[https://arxiv.org/abs/2412.11256][arxiv]]
:ID:       fe485808-abd5-47a3-8989-33302bddd1f1
:END:
#+begin_abstract
   We describe Baily-Borel, toroidal, and geometric --- using the KSBA stable pairs --- compactifications of some moduli spaces of K3 surfaces with a nonsymplectic automorphism of order $3$ and $4$ for which the fixed locus of the automorphism contains a curve of genus $\ge2$. For order $3$, we treat all the maximal-dimensional such families.  We show that the toroidal and the KSBA compactifications in these cases admit simple descriptions in terms of certain $ADE$ root lattices.
#+end_abstract

We had been working on this paper on zoom for quite a while.  But in 2024, Valery visited the ANU for just a week, and we made massive progress!  A few months of typing followed, and then I met Changho at AustMS in New Zealand, and we finished the paper. 

* Syzygies of canonical ribbons on higher genus curves :preprint:
:PROPERTIES:
:with: [[jayan:][Jayan Mukherjee]]
:where:  Pre-print
:when:     2024
:links: [[file:papers/highergenusribbons.pdf][pdf]], [[https://arxiv.org/abs/2412.05500][arxiv]]
:ID:       c6c78ad7-7a03-4b03-95d8-ab4cd5450fb8
:END:
#+begin_abstract
We study the syzygies of the canonical embedding of a ribbon $\widetilde{C}$ on a curve $C$ of genus $g \geq 1$.  We show that the linear series Clifford index and the resolution Clifford index are equal for a general ribbon of arithmetic genus $p_a$ on a general curve of genus $g$ with $p_{a} \geq \operatorname{max}\{3g+7, 6g-4\}$. Among non-general ribbons, the case of split ribbons is particularly interesting.  

Equality of the two Clifford indices for a split ribbon is related to the gonality conjecture for $C$ and it implies Green's conjecture for all double covers $C'$ of $C$ with $g(C') \geq \textrm{max}\{3g+2, 6g-4\}$.  We reduce it to the vanishing of certain Koszul cohomology groups of an auxiliary module of syzygies associated to $C$, which may be of independent interest.
#+end_abstract

Jayan and I started thinking about these things when I visited ICERM for a semester in 2022.  We made a lot of progress when he visited me in 2024.

* Counting 3-uple Veronese surfaces :preprint:
:PROPERTIES:
:with: [[anandpatel:][Anand Patel]]
:where:  Pre-print
:when: 2024
:links: [[file:papers/3veroneseP2.pdf][pdf]], [[https://arxiv.org/abs/2411.14232][arxiv]]
:ID:       83eab6f9-e798-499b-bff5-cdea76b092c8
:END:
#+begin_abstract
This paper culminates in the count of the number of 3-Veronese surfaces passing through 13 general points. This follows the case of 2-Veronese surfaces discovered by Coble in the 1920's. One important element of the calculation is a direct construction of a space of "complete triangles." Our construction is different from the classical ordered constructions of Schubert, Collino and Fulton, as it occurs directly on the Hilbert scheme of length 3 subschemes of the plane. We transport the enumerative problem into a 26-dimensional Grassmannian bundle over our space of complete triangles, where we perform Atiyah-Bott localization. Several important questions arise, which we collect at the end of the paper. 
#+end_abstract

Although the basic idea behind the computation is simple, the details are quite involved.  Multiple blow-ups are necessary to remove excess intersections.  For a long time, we had no independent check on the correctness of our calculation, so we were hesitating to put this up.  But we finally did.  Shortly afterwards,  [[timduff:][Timothy Duff]] successfully verified this numerically!  So the number of 3-Veronese planes through 13 points in 9-dimensional space is undoubtedly 4246! (exclamation mark, not factorial).

* Equivariant classes of orbits in GL(2)-representations              :paper:
:PROPERTIES:
:where:  Selecta Mathematica (accepted)
:when:     2026
:links: [[file:papers/gl2orbits.pdf][pdf]], [[https://arxiv.org/abs/2405.09849][arxiv]], [[https://github.com/deopurkar/equivariant-classes-of-gl2-orbits/][repository]]
:ID:       b1ba9384-4b6a-47b1-888c-61cc0c828493
:END:
#+begin_abstract
We compute equivariant fundamental classes of orbits in GL(2)-representations. As applications, we find degrees of the orbit closures corresponding to elliptic fibrations and self-maps of the projective line.
#+end_abstract

The idea is simple: resolve the rational map from the projective space of \(2 \times 2\) matrices to the orbit closure.  The key observation that makes things work very cleanly is that the scheme theoretic base locus is toroidal.  So a toroidal stacky blow-up resolves the map in one fell swoop.  What remains is the involved but straightforward application of the localisation formula. 

I knew basically how this was going to work before I went on parental leave.  This was the first project I finished when I came back to work.  

* Orbits of linear series on the projective line                      :paper:
:PROPERTIES:
:with:     [[anandpatel:][Anand Patel]]
:where:  International Mathematics Research Notices
:when:     2024
:links: [[file:papers/erc.pdf][pdf]],[[https://arxiv.org/abs/2211.16603][ arxiv]], [[https://doi.org/10.1093/imrn/rnae169][journal]]
:ID:       e4f6d1ab-1a2b-4def-bbbd-092960a347f1
:END:
#+begin_abstract
We compute the equivariant fundamental class of the orbit closure of a linear series on the projective line.  We also describe the boundary of the orbit closure and how the orbits specialise in one parameter families.
#+end_abstract

What's fun here is finding a class on the equivariant Grassmannian, instead of the more usual projective space.  This involves pinning down equivariant vector bundles instead of just line bundles.  We had a sketch of this in the week Anand P. visited me at ICERM in 2022.  Afterwards, I came up with a horribly complicated argument for identifying the equivariant vector bundles.  But the answer turned out to be so simple that there had to be a better way.  And there was (it's in the paper)! 

* A universal formula for counting cubic surfaces                     :paper:
:PROPERTIES:
:with:     [[anandpatel:][Anand Patel]], [[dennistseng:][Dennis Tseng]]
:where:  Algebraic Geometry (to appear)
:when:     2024
:links: [[file:papers/countingcubics.pdf][pdf]], [[https://arxiv.org/abs/2109.12672][arxiv]]
:ID:       aa908035-6504-4bd7-8a1d-aecf14f07383
:END:
#+begin_abstract
Using equivariant geometry, we find a universal formula that computes the number of times a general cubic surface arises in a family. As applications, we show that the PGL(4) orbit closure of a generic cubic surface has degree 96120, and that a general cubic surface arises 42120 times as a hyperplane section of a general cubic 3-fold.
#+end_abstract

The question of finding the degree of the orbit of a cubic surface had been open for a while;  it is one of the "[[https://arxiv.org/abs/1912.07347][Twenty-seven questions about the cubic surface]]" by Sturfels and Ranestad.  Counterintuitively, solving the harder problem (finding the equivariant degree) turns out to be easier!  I do not know any other solution that circumvents equivariant geometry.

This project convinced me that one should be looking for answers to enumerative questions on non-separated moduli stacks!    

* Spherical objects and stability conditions on 2-Calabi--Yau quiver categories :paper:
:PROPERTIES:
:with:     [[asilata:][Asilata Bapat]], [[tony:][Anthony Licata]]
:where:  Mathematische Zeitschrift
:when:     2022
:links: [[file:papers/2cy-algorithm.pdf][pdf]],[[https://arxiv.org/abs/2108.09155][ arxiv]], [[https://link.springer.com/article/10.1007/s00209-022-03172-8][journal]]
:ID:       8c1b044d-82a9-4cbc-986e-a07f93dc93d1
:END:
#+begin_abstract
Consider a 2-Calabi--Yau triangulated category with a Bridgeland stability condition. We devise an effective procedure to reduce the phase spread of an object by applying spherical twists. Using this, we give new proofs of the following theorems for 2-Calabi--Yau categories associated to ADE quivers: (1) all spherical objects lie in a single orbit of the braid group, and (2) the space of Bridgeland stability conditions is connected.
#+end_abstract

We came up with all of these arguments while working on the [[id:7ee039fe-461d-41bb-8a73-116bc7f196e0][Thurston compactification project]].  But then we realised that there is quite a bit of interest in classifying spherical objects!  So we wrote them up nicely as a self-contained paper.

The idea is that if you apply the correct twist (positive or negative) in the top or bottom HN piece of a spherical object, then the object shrinks.  By repeating this procedure, we can then hope to arrive at an object of spread zero.  The frustrating part is that we can't give a lower bound on the shrinkage.  So we cannot guarantee that the process terminates (although it has never failed to terminate in any of the examples we have computed).  In the presence of simplifying hypotheses (finite type), termination is automatic. 

* Vector bundles and finite covers                                    :paper:
:PROPERTIES:
:with:     [[anandpatel:][Anand Patel]]
:where:  Forum of Mathematics, Sigma
:when:     2022
:links: [[file:papers/ebundle.pdf][pdf]], [[https://arxiv.org/abs/1608.01711/][arXiv]], [[https://www.cambridge.org/core/services/aop-cambridge-core/content/view/21EB07C62F7A142F5CC39EF3950C2231/S2050509422000196a.pdf/vector_bundles_and_finite_covers.pdf][journal]]
:ID:       4b773769-0ca6-42a8-a8e6-309dd23ffa5c
:END:
#+begin_abstract
Motivated by the problem of finding algebraic constructions of finite coverings in commutative algebra, the Steinitz realization problem in number theory, and the study of Hurwitz spaces in algebraic geometry, we investigate the vector bundles underlying the structure sheaf of a finite flat branched covering. We prove that, up to a twist, every vector bundle on a smooth projective curve arises from the direct image of the structure sheaf of a smooth, connected branched cover.
#+end_abstract

A long time ago, Rob Lazarsfeld asked me if we could classify Tschirnhausen bundles asymptotically.  This question remained at the back of my mind.  When Anand P. and I met at Oberwolfach, he came up with the idea of attaching rational normal curves to make the cover more flexible.  And it works!  

There is a bit more work to get it to work in an affine bundle rather than a projective bundle.  I tried to give an overly smart and short argument, which ended up being wrong (thanks, referee!)  But some honest but longer analysis rescues it.

The origin of the idea is that a cover is a map to \(BS_d\).  We know that maps become flexible if we attach lots of rational tails to the domain.  For maps to \(BS_d\), one can translate this into attaching rational normal curves in fibers.
 
* Stable log surfaces, admissible covers, and canonical curves of genus 4 :paper:
:PROPERTIES:
:with:     [[changho:][Changho Han]]
:where:  Transactions of the Americal Mathematical Society
:when:     2021
:links: [[file:papers/TrigonalKSBA.pdf][pdf]],[[https://arxiv.org/abs/1807.08413/][ arxiv]], [[https://www.ams.org/journals/tran/2021-374-01/S0002-9947-2020-08225-7/?active=current][journal]]
:ID:       f7400180-00b7-4b54-a902-8941b3bd3823
:END: 
#+begin_abstract
We describe a compactification of the moduli space of pairs (S,C) where S is a smooth quadric surface in 3-space and C is a smooth divisor on S of class (3,3). We show that the compactified moduli space is a smooth Deligne-Mumford stack with 4 boundary components. We relate our compactification with compactifications of the moduli space of genus 4 curves. In particular, we show that our space compactifies the blow-up of the hyperelliptic locus. We also relate our compactification to a compactification of the Hurwitz space of triple coverings of the projective line by genus 4 curves.
#+end_abstract

There aren't many cases where we can completely described a KSBA compactification, but this is one of them!  Mostly because we know trigonal curves a bit too well.  But it seems likely that there will be results in the future that don't rely on this knowledge. 

* A Thurston compactification of the space of stability conditions       :preprint:
:PROPERTIES:
:with:     [[asilata:][Asilata Bapat]], [[tony:][Anthony Licata]]
:where:  Pre-print
:when:     2020
:links: [[file:papers/a2-compactification.pdf][pdf]], [[https://arxiv.org/abs/2011.07908][arxiv]]
:ID:       7ee039fe-461d-41bb-8a73-116bc7f196e0
:END:
  #+begin_abstract
  We propose compactifications of the moduli space of Bridgeland stability conditions of a triangulated category.
  Our construction arises from a viewing a stability condition as a metric on the underlying category and is inspired by the Thurston compactification of the Teichm\"uller space of hyperbolic metrics on a surface.
  The key ingredient in the construction are maps from the stability manifold to an infinite projective space.
  We prove that, under suitable hypotheses, these maps are injective and their image has a compact closure.
  We identify a family of points in the boundary that are categorical analogous to the intersection functionals in Teichm\"uller theory.
  
  We study in detail the geometry of the resulting compactification for the 2-Calabi--Yau categories of quivers, and fully work out the cases of the \(A_2\) and \(\widehat{A_1}\) quivers.
  To do so, we carefully examine the dynamics of Harder--Narasimhan multiplicities under auto-equivalences of the category.
  We introduce a finite automaton to study this dynamics and employ it in our analysis of the \(A_{2}\) and \(\widehat{A_1}\) categories.
  #+end_abstract

We take seriously the idea that the stability manifold is like the Teichmüller space.
This suggests fascinating new ways to study stability conditions.  The Thurston compactification is one of them!

This paper contains many results beyond the headlines.  We have an appendix that discusses when an arbitrary filtration of an object can be straightened out to the HN filtration.  We also have some technology (automata) to encode the "piecewise-linear" nature of categorical group actions.  This piecewise linearity also features prominently in [[id:1245acba-aa78-4ab6-ad92-fb1c2c46b5c6]["A sphere of spherical objects]]".

* Ramification divisors of general projections                        :paper:
:PROPERTIES:
:with:     [[eduardduryev:][Eduard Duryev]], [[anandpatel:][Anand Patel]]
:where:  Documenta Mathematica
:when:     2020
:links: [[file:papers/PR.pdf][pdf]], [[http://arxiv.org/abs/1901.01513/][arxiv]], [[https://ems.press/journals/dm/articles/8965720][journal]]
:ID:       82e9302f-6674-41b8-97cd-6733ac7edf89
:END:
#+begin_abstract
We study the ramification divisors of projections of a smooth projective variety onto a linear subspace of the same dimension. We prove that the ramification divisors vary in a maximal dimensional family for a large class of varieties. Going further, we study the map that associates to a linear projection its ramification divisor. We show that this map is dominant for most (but not all!) varieties of minimal degree, using (linked) limit linear series of higher rank. We find the degree of this map in some cases, extending the classical appearance of Catalan numbers in the geometry of rational normal curves, and give a geometric explanation of its fibers in terms of torsion points of naturally occurring elliptic curves in the case of the Veronese surface and the quartic rational surface scroll.
#+end_abstract

The most intriguing part of this project is what lies beyond!  We discover a delightful array of enumerative questions.  The answers to the first line in this array are the famous Catalan numbers.  This is the dimension one case.  There is a whole world of higher dimensions whose answers are completely unknown (barring a handful of exceptions).  In small cases, we can find the answers using a computer.  Curiously, various slices of the answer array uniquely match certain known combinatorial sequences on [[https://oeis.org/][OEIS]].  We hope there is an overarching pattern that connects all of them!  

For surface scrolls, Anand Patel's most recent computation reveals the following.
Let us write the scroll \(F_{a,b}\) by its degree \(d = a+b\) and eccentricity \(e = \lfloor (a-b)/2 \rfloor\) (this is 0 for the generic scrolls and increases as the scrolls get more special).  

| e\d | 2 | 3 | 4 | 5 |  6 |  7 |   8 |    9 |    10 |    11 |     12 |      13 |       14 |
|-----+---+---+---+---+----+----+-----+------+-------+-------+--------+---------+----------|
|   0 | 1 | 1 | 2 | 6 | 22 | 92 | 422 | 2074 | 10754 | 58202 | 326240 | 1882960 | 11140560 |
|   1 |   |   | 1 | 1 | 17 | 43 | 380 | 1444 | 10292 | 48764 | 215129 |         |          |
|   2 |   |   |   |   |  1 |  1 | 100 |  220 |  5012 | 16094 |        |         |          |
|   3 |   |   |   |   |    |    |   1 |    1 |   467 |       |        |         |          |




* Anticanonical tropical cubic del Pezzos contain exactly 27 lines       :preprint:
:PROPERTIES:
:with:     [[mariacueto:][María Angélica Cueto]]
:where:  Pre-print
:when:     2019
:links: [[file:papers/lines_on_tropical_cubics.pdf][pdf]], [[https://arxiv.org/abs/1906.08196][arxiv]]
:ID:       931c8753-71af-4498-89fe-5823ae74d1e9
:END:
#+begin_abstract
The classical statement of Cayley-Salmon that there are 27 lines on every smooth cubic surface in \(\mathbf{P}^3\) fails to hold under tropicalization: a tropical cubic surface in \(T\mathbf{P}^3\) often contains infinitely many tropical lines. Under mild genericity assumptions, we show that when embedded using the Eckardt triangles in the anticanonical system, tropical cubic del Pezzo surfaces contain exactly 27 tropical lines. In the non-generic case, which we identify explicitly, we find up to 27 extra lines, no multiple of which lifts to a curve on the cubic surface. We realize the moduli space of stable anticanonical tropical cubics as a four-dimensional fan in \(\mathbf{R}^40\) with an action of the Weyl group \(W(E_6)\). In the absence of Eckardt points, we show the combinatorial types of these tropical surfaces are determined by the boundary arrangement of 27 metric trees corresponding to the tropicalization of the classical 27 lines on the smooth algebraic cubic surfaces. Tropical convexity and the combinatorics of the root system \(E_6\) play a central role in our analysis.
#+end_abstract

The tropical geometry here is mostly thanks to María.  The key point is that embedding a cubic surface in its anti-canonical linear series \(\mathbf{P}^3\) does not necessarily lead to a nice tropicalization.  Roughly speaking, this is because the tropicalization is sensitive to the basis, and there is no canonical basis of the anti-canonical series.  However, there is a canonical spanning set of the anti-canonical series, corresponding to the 45 anti-canonical triangles.  It turns out that the degenarte but more canonical embedding into \(\mathbf{P}^{45}\) has a much better behaved tropicalization.

* Covers of stacky curves and limits of plane quintics                :paper:
:PROPERTIES:
:where:  Transactions of the Americal Mathematical Society
:when:     2019
:links: [[file:papers/StackyAdmissibleCovers.pdf][pdf]], [[http://arxiv.org/abs/1507.03252/][arxiv]], [[https://www.ams.org/journals/tran/2019-371-01/S0002-9947-2018-07301-9/home.html][journal]]
:ID:       1d0dda32-8233-4fd8-8303-a6d7e16dc0cc
:END:
#+begin_abstract
We construct a well-behaved compactification of the space of finite covers of a stacky curve using admissible cover degenerations. Using our construction, we compactify the space of tetragonal curves on Hirzebruch surfaces. As an application, we explicitly describe the boundary divisors of the closure in \(\overline{M}_6\) of the locus of smooth plane quintic curves.
#+end_abstract

* Syzygy divisors on Hurwitz spaces                                   :paper:
:PROPERTIES:
:with:     [[anandpatel:][Anand Patel]]
:where:  Contemporary Mathematics
:when:     2018
:links: [[file:papers/HigherMaroni.pdf][pdf]], [[https://arxiv.org/abs/1805.00648][arxiv]], [[https://www.ams.org/books/conm/703/14139][journal]]
:ID:       e4a32e17-c28b-45a2-bfb1-8622e151af99
:END:
#+begin_abstract
We describe a sequence of effective divisors on the Hurwitz space H(d,g) for d dividing g-1 and compute their cycle classes on a partial compactification. These divisors arise from vector bundles of syzygies canonically associated to a branched cover. We find that the cycle classes are all proportional to each other.
#+end_abstract

* The canonical syzygy conjecture for ribbons                         :paper:
:PROPERTIES:
:where:  Mathematische Zeitschrift
:when:     2018
:links: [[file:papers/RibbonGreen.pdf][pdf]], [[http://arxiv.org/abs/1510.07755/][arxiv]]
:ID:       c399a596-99cb-41bc-945b-a2846c40757e
:END:
#+begin_abstract
We prove the analogue for ribbons of Green\'s canonical syzygy conjecture, formulated by Bayer and Eisenbud. Our proof uses the results of Voisin and Hirschowitz-Ramanan on Green\'s conjecture for general smooth curves.
#+end_abstract

* Toward GIT stability of syzygies of canonical curves                :paper:
:PROPERTIES:
:with:     [[maksym:][Maksym Fedorchuk]], [[davidswinarski:][David Swinarski]]
:where:  Algebraic Geometry
:when:     2016
:links: [[file:papers/gitsyzygy.pdf][pdf]], [[http://arxiv.org/abs/1401.6101/][arxiv]], [[http://www.algebraicgeometry.nl/2016-1/2016-1-001.pdf][journal]]
:ID:       800287ce-183c-42d7-ad07-0f73202dc7c3
:END:
#+begin_abstract
We introduce the problem of GIT stability for syzygy points of canonical curves with a view toward a GIT construction of the canonical model of the moduli space of stable curves. As the first step in this direction, we prove semi-stability of the first syzygy point for a general canonical curve of odd genus. 
#+end_abstract

* The Picard rank conjecture for the Hurwitz spaces of degree up to five :paper:
:PROPERTIES:
:with:     [[anandpatel:][Anand Patel]]
:where:  Algebra & Number Theory
:when:     2015
:links: [[file:papers/PicH345.pdf][pdf]], [[http://arxiv.org/abs/1401.6101/][arxiv]], [[http://msp.org/ant/2015/9-2/p05.xhtml][journal]]
:ID:       e0e0aebf-32c6-4041-95d5-16574e6c0513
:END:
#+begin_abstract
We prove that the rational Picard group of the simple Hurwitz space H_{d,g} is trivial for d up to five. We also relate the rational Picard groups of the Hurwitz spaces to the rational Picard groups of the Severi varieties of nodal curves on Hirzebruch surfaces.
#+end_abstract

* Groebner techniques for ribbons                                     :paper:
:PROPERTIES:
:with:     [[maksym:][Maksym Fedorchuk]], [[davidswinarski:][David Swinarski]]
:where:  Albanian Journal of Mathematics
:when:     2014
:links: [[file:papers/groebner.pdf][pdf]], [[https://sites.google.com/site/albjmath/archives/vol-8/2014-6][journal]]
:ID:       b355cfa4-8d4b-4110-93f7-f85699fe3e36
:END:
#+begin_abstract
We use Groebner basis techniques to study the balanced canonical ribbon in each odd genus g \geq 5. We obtain equations and syzygies of the ribbon, give a Groebner interpretation of part of Alper, Fedorchuk, and Smyth\'s proof of finite Hilbert stability for canonical curves, and discuss the obstacles in using ribbons to give a new proof of Generic Green\'s Conjecture (Voisin\'s Theorem).
#+end_abstract

* Compactifications of Hurwitz spaces                                 :paper:
:PROPERTIES:
:where:  International Mathematics Research Notices
:when:     2014
:links: [[file:papers/CompHurwitz.pdf][pdf]], [[http://arxiv.org/abs/1206.4535/][arxiv]], [[http://imrn.oxfordjournals.org/content/early/2013/04/08/imrn.rnt060.abstract][journal]]
:ID:       504645b5-633e-42dd-9727-2c83fd1bb8d3
:END:
#+begin_abstract
We construct several modular compactifications of the Hurwitz space $H^d_{g/h}$ of genus $g$ curves expressed as $d$-sheeted, simply branched covers of genus $h$ curves. These compactifications are obtained by allowing the branch points of the covers to collide to a variable extent. They are very well-behaved if $d = 2, 3$, or if relatively few collisions are allowed. We recover as special cases the spaces of twisted admissible covers of Abramovich, Corti and Vistoli and the spaces of hyperelliptic curves of Fedorchuk.
#+end_abstract

* Class of the Hodge eigenbundle using orbifold Riemann-Roch            :preprint:
:PROPERTIES:
:where:  Pre-print, appendix to [[https://drive.google.com/file/d/1wq-Fh3DiqODc51t-J0phIexVF7B4lxsY/view][/Cyclic covering morphisms on \(\overline M_{0,n}\)/]] by [[https://www2.bc.edu/maksym-fedorchuk/][Maksym Fedorchuk]]
:when:     2013
:links: [[file:papers/CyclicAppendix.pdf][pdf]]
:ID:       3b6a466e-3eef-4ba3-9515-07dcf2a34e83
:END:
#+begin_abstract
We algebraically compute the class of the Hodge eigenbundles in the cyclic covering construction using Grothendieck-Riemann-Roch for stacks.
#+end_abstract

* Sharp slope bounds for sweeping families of trigonal curves         :paper:
:PROPERTIES:
:with:     [[anandpatel:][Anand Patel]]
:where:  Mathematical Research Letters
:when:     2013
:links: [[file:papers/TrigonalSlopes.pdf][pdf]], [[http://arxiv.org/abs/1211.2827/][arxiv]], [[http://www.intlpress.com/site/pub/pages/journals/items/mrl/content/vols/0020/0005/a005/][journal]]
:ID:       75d3ebc0-1174-40e1-9ec5-a949bad877de
:END:
#+begin_abstract
We establish sharp bounds for the slopes of curves in \(\overline{M}_g\) that sweep the locus of trigonal curves, proving Stankova-Frenkel\'s conjectured bound of 7+6/g for even g and obtaining the bound 7+20/(3g+1) for odd g. For even g, we find an explicit expression of the so-called Maroni divisor in the Picard group of the space of admissible triple covers. For odd g, we describe the analogous extremal effective divisor and give a similar explicit expression. 
#+end_abstract

* Modular compactifications of the space of marked trigonal curves    :paper:
:PROPERTIES:
:where:  Advances in Mathematics
:when:     2013
:links: [[file:papers/MarkedTrigonal.pdf][pdf]], [[http://arxiv.org/abs/1206.4503/][arxiv]], [[https://www.sciencedirect.com/science/article/pii/S0001870813002776][journal]]
:ID:       833f39b4-0d38-4903-8356-aac9fc2b16d0
:END:
#+begin_abstract
We construct a sequence of modular compactifications of the space of marked trigonal curves by allowing the branch points to coincide to a given extent. Beginning with the standard admissible cover compactification, the sequence first proceeds through contractions of the boundary divisors and then through flips of the so-called Maroni strata, culminating in a Fano model for even genera and a Fano fibration for odd genera. While the sequence of divisorial contractions arises from a more general construction, the sequence of flips uses the particular geometry of triple covers. We explicitly describe the Mori chamber decomposition given by this sequence of flips.
#+end_abstract

* Alternate compactifications of Hurwitz spaces                      :thesis:
:PROPERTIES:
:where:  PhD Thesis (Harvard)
:when:     2012
:links: [[file:papers/thesis.pdf][pdf]]
:ID:       5da2ae43-0723-4518-87a0-08743399185a
:END:
#+begin_abstract
We construct several modular compactifications of the Hurwitz space $H^d_{g/h}$ of genus $g$ curves expressed as $d$-sheeted, simply branched covers of genus $h$ curves. They are obtained by allowing the branch points of the cover to collide to a variable extent, generalizing the spaces of twisted admissible covers of \citet*{acv:03}. The resulting spaces are very well-behaved if $d$ is small or if relatively few collisions are allowed. In particular, for $d = 2$ and $3$, they are always well-behaved. For $d = 2$, we recover the spaces of hyperelliptic curves of \citet{fedorchuk10:_modul_hyp}. For $d = 3$, we obtain new birational models of the space of triple covers.

We describe in detail the birational geometry of the spaces of triple covers of $\P^1$ with a marked fiber. In this case, we obtain a sequence of birational models that begins with the space of marked (twisted) admissible covers and proceeds through the following transformations:
 1. sequential contractions of the boundary divisors,
 2. contraction of the hyperelliptic divisor,
 3. sequential flips of the higher Maroni loci,
 4. contraction of the Maroni divisor (for even $g$).
The sequence culminates in a Fano variety in the case of even $g$, which we describe explicitly, and a variety fibered over $\P^1$ with Fano fibers in the case of odd $g$.
#+end_abstract

* An introduction to intersection homology       :expository:paper:highlight:
:properties:
:where:  Minor thesis (Harvard)
:when:     2010
:links: [[file:papers/anandrd_minor_thesis.pdf][pdf]]
:ID:       0f97be8d-e4d3-4515-bf1f-981c9e8380a0
:labels:    [[id:05f9493f-833e-4f64-a2b5-321a11c91a3b][expository]]
:end:

This is the minor thesis I wrote as a PhD student at Harvard.  It is an exposition of Intersection Homology following Goresky and MacPherson with  appendices on homological algebra and sheaf theory. 

* Normalization of algebraic varieties                     :expository:paper:
:properties:
:where:  MIT Undergraduate Journal of Mathematics
:when:     2008
:links: [[file:papers/anandrd_ug_thesis.pdf][pdf]]
:ID:       97f6df09-0591-49b7-97d0-e79b606af653
:labels:    [[id:05f9493f-833e-4f64-a2b5-321a11c91a3b][expository]]
:end:

#+begin_abstract
. We study the process of normalization of affine algebraic varieties and an algorithm to carry it out. We illustrate the application of normalization to the problem of resolution of singularities by proving that normal varieties are regular in codimension 1. 
#+end_abstract
