:PROPERTIES:
:ID:       1a667b02-c72c-4225-acbc-d5064ab2f748
:END:
#+title: For prospective PhD students | Anand Deopurkar
#+subtitle: Thinking of doing a PhD at ANU with me as a supervisor?
#+description: Guidelines for prospective PhD students of Anand Deopurkar
#+keywords: PhD Algebraic Geometry Anand Deopurkar 

Thanks!  I am happy that you find my work interesting.

Before you write to me, please do the following.

1. (Important)
   Read this page and mention in your email that you have done so.
   Make the subject of your email "[Prospective PhD] ...".

2. Explain your background in algebraic geometry and commutative algebra.

   Please be specific.  Mention how you acquired this background (classes, independent reading, etc), which books you have read, whether you did any exercises, etc.

3. Explain your background in other areas that may be relevant, like representation theory, complex analysis, algebraic topology, etc.

4. Send a copy of your transcript (unofficial is fine) and curriculum vitae.

5. Send me the most sophisticated mathematical document you have written as a sample of your work.
   This does not have to be original research; expository is fine.

6. List at least two people whom I can contact for a reference.

The duration of a PhD at ANU is short: about 3 to 3.5 years.  
So it is improtant that candidates come in with sufficient background.
I may not be able to accept you if I think you do not meet this criterion.
Please do not take it as a judgement of your mathematical ability, readiness to do a PhD in some other area, or at another institution.

Thanks again and all the best!

