# Created 2025-04-13 Sun 11:24
#+title: Stability conditions, metrics, and compactification
#+author: Anand Deopurkar
(Notes for the talk at Edinburgh in 2024).

Throughout the talk, \(C\) will be a triangulated category.
Examples to keep in mind are \(C = D^b(\operatorname{Coh} X)\) or \(C = D^b(\operatorname{mod}-A)\).
We have a notion, due to Bridgeland, of a stability condition on \(C\).
(If you do not know about what this is, do not worry.  I will give the necessary background when needed.)
One of the most fascinating feature of this notion is that the set of all stability conditions on \(C\) naturally has the structure of a complex manifold, called \(\operatorname{Stab}(C)\).
Thus, associated to a triangulated category \(C\) is a manifold \(\operatorname{Stab}C\).

\[ C \leadsto \operatorname{Stab} C\]

In this talk, I want to convey three main points:

1. It is important to understand the geometry of \(\operatorname{Stab}(C)\).
2. We can think of \(\operatorname{Stab}(C)\) as a set of metrics on \(C\).
3. A compactification of \(\operatorname{Stab}(C)\) inspired by (2).
* Implications of the geometry of \(\operatorname{Stab}(C)\).

To convince you that understanding the geometry of \(\operatorname{Stab}C\) is worthwhile, let me illustrate two implications of doing so.
Both implications have, a priori, nothing to do with stability conditions.
In fact, the second one has, a priori, nothing to do even with triangulated categories.
In both examples, there is a group \(G\) that we seek to understand.
It acts by auto-equivalences on \(C\), and therefore acts by homeomorphisms on \(\operatorname{Stab}(C)\).
The setting of \(G\) acting on \(C\) is a bit exotic.
The setting of \(G\) acting on \(\operatorname{Stab}C\) is more familiar.
Understanding the geometry of this action leads to information about \(G\).

Without further ado, here is the first implication.

*Theorem* (Bayer--Bridgeland): Let \(X\) be a K3 surface of Picard rank 1, and \(C = D^b \operatorname{Coh}(X)\).
Then \(\operatorname{Stab}(C)\) is contractible.  As a consequence, \(\operatorname{Aut}(C)\) is generated by the expected set of generators.

Thus, knowing that \(\operatorname{Stab}C\) is contractible allows us to pin down \(\operatorname{Aut}(C)\).

Let us now briefly look at the second implication. 
Let \(\Gamma\) be a simple graph.
Associated to \(\Gamma\) is a group called the Artin-Tits braid group \(B_{\Gamma}\).
These groups are poorly understood, mainly because we do not have very many examples of good actions for them.
For example, it is unknown whether \(B_{\Gamma}\) is a linear group, or even whether it has a solvable word problem.

Nevertheless, this group acts naturally on a triangulated category \(C_{\Gamma}\) and hence on its stability manifold.

*Theorem* If \(\operatorname{Stab}(C_{\Gamma})\) is simply connected, then the action of \(B_{\Gamma}\) on \(C_{\Gamma}\) is faithful.  As a consequence, the word problem for \(B_{\Gamma}\) is solvable.

*Theorem* If \(\operatorname{Stab}(C_{\Gamma})\) is contractible, then the \(K(\pi,1)\) conjecture holds for \(B_{\Gamma}\).
* Stability conditions and metrics

I now want to describe a point of view I have been exploring with Asilata Bapat and Tony Licata.
We have been looking at stability conditions from the point of view of metric geometry.
Before going into the details, let me give a few elementary definitions.
** Metrics on categories

A /metric/ on a category \(C\) is a fuction
\[ \ell \colon  \operatorname{Mor} C \to \mathbf{R}_{\geq 0}\]
such that
1. if \(f\) is an isomorphism, then \(\ell(f) = 0\).
2. for compasable morphisms \(f\) and \(g\), we have
   \[ \ell(g \circ f) \leq \ell(f) + \ell(g).\]
** How a stability condition gives a metric

We now have to recall a few things about stability conditions.

A part of the data of a stability condition is a collection of objects of \(C\) called /semi-stable/ objects, such that every object \(x \in C\) has a filtration
\[ 0 = x_0 \to x_1 \to \cdots \to x_n = x\]
whose factors \(a_i = \operatorname{Cone}(x_i \to x_{i+1})\) are semi-stable.
This filtration is unique after imposing a suitable monotonicity condition, that I will supress.
This unique filtration is called the /Harder-Narasimhan filtration/ of \(x\).

Another part of the data of a stability condition is a group homomorphism, called the central charge,
\[ Z \colon K(C) \to \mathbf{C}. \]
The semi-stable objects and the central charge are supposed to satisfy compactibility conditions that I will suppress.

Now, let \(\sigma\) be a stability condition.
Associated to \(\sigma\) is a metric \(\ell = \ell_{\sigma}\) on \(C\), defined as follows.
We set
\[ \ell (f) = m(\operatorname{Cone}(f)),\]
where \(m(x)\) is the /mass/ of \(x\), defined as follows:
\[m(x) = \sum |Z(a_i)|.\]

It is easy to check that \(\ell(f) = 0\) if \(f\) is an isomorphism.
The triangle inequality follows from the octahedral axiom and the fact that if
\[ x \to y \to z \xrightarrow{+1} \]
is a distinguished triangle, then
\[ m(y) \leq m(x) + m(z).\]
*** q-Analogue
The definition has a natural \(q\)-analogue, which I will suppress in the interest of time.
** To what extent can a stability condition be recovered from the metric?

For example, let us try to recreate Harder--Narasimhan filtrations purely from the metric.

The Harder--Narasimhan filtration
\[ 0 = x_0 \to x_1 \to \cdots \to x_n = x\]
is a /geodesic path/ from \(0\) to \(x\).
Unfortunately, there can be many other geodesic paths.
So being geodesic does not quite characterise the Harder--Narasimhan filtrations.

Nevertheless, we can prove the following.

*Proposition*. The object \(x\) is stable if and only if the path \(0 \to x\) is an indivisible geodesic path.

As a result, we can reconstruct the set of stable objects purely from the metric.

The central charge is trickier to re-construct.
In fact, there are examples (for example \(C = D^b(\operatorname{Coh} \mathbf{P}^1)\)), that show that different central charges can lead to the same metrics.
However, in many cases, we can also reconstruct the central charge.

*Theorem*. Let \(C = C_{\Gamma}\) be the 2-CY category associated to a quiver \(\Gamma\).
Then a stability condition \(\sigma\) is uniquely determined up to translation by the metric \(\ell_{\sigma}\).

I suspect a similar statement is true for \(D^b \operatorname{Coh}K3\), but I have not written down a proof.
* Thurston compactification

By the construction \(\sigma \leadsto \ell_{\sigma}\), we can think of \(\operatorname{Stab} C\) as a space of metrics on \(C\).
By taking this point of view, we can try to use the same techniques on \(\operatorname{Stab} C\) as people have used to study moduli spaces of metrics elsewhere in mathematics.
** Key definitions from Teichmuller theory
One example of a highly studied moduli space of metrics is the Teichmuller space
\[ T_g  = \{\text{Hyperbolic metrics on a surface of genus \(g\)}\}.\]
The spcae \(T_g\) is a manifold of dimension \(6g-g\) and admits an action of the mapping class group \(\operatorname{Mod}_g\).

*Remark*. There are reasons to believe that \(\operatorname{Stab} C_{\Gamma}\) with the action of \(B_{\Gamma}\) should be analogous to \(T_g\) with the action of the mapping class group.  So it is a good idea to employ techniques used to study \(T_g\) on \(\operatorname{Stab} C_{\Gamma}\).

One of the fundamental constructions in trying to understand the action of \(\operatorname{Mod}_g\) on \(T_g\) is a compactification of \(T_g\) due to Thurston.
It goes as follows.

Let \(S\) be the set of isotopy classes of (simple closed) curves on the surface.
At the heart of the construction is a map \(i \colon T_g \to \mathbf{P}^S\), defined by
\[ \mu \mapsto \ell_{\mu},\]
where
\[\ell_{\mu}(c) = \text{Length of \(c\) wrt \(\mu\)}.\]
This map 
- is injective, in fact homeo onto its image
- its image has a compact closure
- the closure is a manifold with boundary

What do we see on the boundary?
An important class of functionals on the boundary are the intersection functionals of curves.
For a simple closed curve \(\gamma\), define
\[ i_{\gamma}(c) = \# c \cap \gamma.\]
Then the points \([i_{\gamma}]\), as \(\gamma\) varies, form a dense subset of the boundary.
** Repeat definitions for categories
By viewing a stability condition as a metric, we can do the same construction for \(\operatorname{Stab}\).
Fix a suitable set of objects \(S\).
Define a map
\[ i \colon \operatorname{Stab} C \to \mathbf{P}^S\]
by
\[ \sigma \mapsto [\ell_{\sigma}(0 \to s)] = m_{\sigma}(s).\]
And hope for the best!
** Results
We can prove a number of features in general, and even more features for specific classes of categories.

*Theorem*. If \(S\) contains a classical generator of \(C\), then the image of \(i\) has a compact closure.

For \(C = C_{\Gamma}\), the map is also injective (modulo translation and scaling).
(In general, the map is not injective, but it can be made injective by considering the \(q\)-analogues.)
*** What kinds of points do we see in the boundary?
We see points corresponding to degenerate stability conditions (in the sense of Bolognese).
We also see points analogous to the intersection functionals.

Assume that \(C\) is linear over a field \(k\) and of finite type.
Let \(x \in C\) be a spherical object.
Define \(i_x \colon S \to \mathbf{R}\) to be function that is a slight modification of the function
\[ y \mapsto \dim \hom(x,y) = \sum \dim \hom^i(x,y).\]

*Theorem*. In the above situation, \([i_x]\) lies in the boundary.

Not only the statement, but even a proof of this theorem closely mirrors the Teichmuller theory analogue.
*** Picture in the A2 case

Finally, let me draw the picture in the smallest but highly non-trivial case where \(\Gamma\) is the \(A_2\)-quiver.
In this case, \(\operatorname{Stab} C_{\Gamma}\) modulo translations and scaling is an open 2-disk.
The Thurston compactification turns out to be the closed 2-disk.
The rational points on the boundary circle correspond to the hom functionals of the spherical objects.
