:PROPERTIES:
:ID:       9ad7fb07-194d-485d-bfbb-6eef16e1add4
:END:
#+title: A Thurston compactification of the space of stability conditions
#+LATEX_HEADER_EXTRA: \usepackage{fullpage}
#+options: ':t ":t

This is going to be a condensed version of the three talks in Haifa.

* Analogy with the Teichmuller space.

I will begin by drawing two parallel pictures.
The first is of the Teichmuller space and the mapping class group, which we know very well.
The second is of the stability manifold of a category and the Artin-Tits group, which we do not know very well.
The aim will be to use our knowledge of the Teichmuller story to say something on the other side.

#+begin_verse
| \(T_g\) | \(\operatorname{Stab} (C_{\Gamma})\) |
#+end_verse

Here \(T_g\) is the Teichmuller space of a surface of genus \(g\).
Let me explain the right hand side.
Here \(\Gamma\) is a finite simple graph.
\(C_{\Gamma}\) is the 2-Calabi--Yau category associated to \(\Gamma\).
And \(\operatorname{Stab}(C_{\Gamma})\) is the manifold of Bridgeland stability conditions on \(C_{\Gamma}\).

** What is the 2-Calabi--Yau category associated to \(\Gamma\)?
- A \(\mathbf{C}\)-linear tringulated category (so has shifts and cones)
- 2-Calabi--Yau, that is:
  \[ \operatorname{Hom}(x,y) \cong \operatorname{Hom}(y,x[2])^*\]
- For example, suppose \(\Gamma\) is the \(A_n\) chain.
  Consider the \(A_n\) surface singularity \(Y:x^2+y^2 = z^{n+1}\).
  Let \(\pi \colon X \to Y\) be the minimal resolution of singularities.
  Then the exceptional divisor in \(X\) is a chain of \(n\) rational curves.
  We have
  \[C_{\Gamma} = \{x \in D^b(\operatorname{Coh} X) \mid R\pi_{*} x = 0\}.\]
  For example, the bundle \(O(-1)\) supported on the \(i\)-th component of the chain lies in \(C_{\Gamma}\).
  Call this \(P_i\).
  It turns out that \(P_1, \dots, P_n\) generate \(C_{\Gamma}\).
  We have
  \[ \hom^{0}(P_i, P_i) = \hom^2(P_i,P_i) = 1 \quad \hom^1(P_i, P_{i+1}) = 1,\]
  and all other homs are 0.
- In general, \(C_{\Gamma}\) is generated by objects \(P_v\), one for each vertex \(v \in \Gamma\), satisfying
  \[ \hom^0(P_v,P_v) = \hom^2(P_v,P_v) = 1 \quad \hom^1(P_v, P_w) = 1,\]
  if \(v - w\) is an edge of \(\Gamma\). 
** What are stability conditions?
- Will take too long to define.
- Gives a metric on the category.
  That is, for every arrow \(f \colon x \to y\), a non-negative number \(l(f)\) such that the triangle inequality is satisfied: \(l(x \to z) \leq l(x \to y) + l(y \to z)\).
- The set of all stability conditions is a manifold. 
** Group actions
On \(T_g\) we have the action of the mapping class group \(\operatorname{Mod}_g\).
On \(C_{\Gamma}\), and hence on \(\operatorname{Stab}(C_{\Gamma})\), we have the action of the Artin--Tits group \(A_{\Gamma}\).
The action of \(\operatorname{Mod}_g\) is faithful, and the quotient \(T_g \to M_g\) is a covering space with covering group \(\operatorname{Mod}_g\).
The action of \(A_{\Gamma}\) on \(\operatorname{Stab}(C_\Gamma)\) is not know to be faithful, but the quotient \(\operatorname{Stab}(C_{\Gamma}) \to \operatorname{Stab}(C_{\Gamma}) / A_{\Gamma} = U_{\Gamma}\) is a covering space and \[\pi_1(\operatorname{Stab}(C_{\Gamma})) = A_{\Gamma}.\]

*Conjecture*.  The action of \(A_{\Gamma}\) on \(\operatorname{Stab}(C_{\Gamma})\) is faithful.  Equivalently, \(\operatorname{Stab}(C_{\Gamma})\) is simply connected.

This has major implications. 
For example, this implies (in particular) that the action of \(A_{\Gamma}\) on \(C_{\Gamma}\) is faithful.
And therefore:

*Consequence*. The word and conjugacy problems for \(A_{\Gamma}\) are solvable.

Another longstanding open conjecture here is the \(K(\pi,1)\)-conjecture.

*Conjecture*.
 1. The space \(U\) is a \(K(\pi,1)\), equivalently (in light of the above conjecture)
 2. \(\operatorname{Stab}(C_{\Gamma})\) is contractible.

*Question*.
1. Fenchel-Nielsen coordinates for \(\operatorname{Stab}(C_{\Gamma})\)?
2. Other approaches to contratibility of \(T_g\)?

* Thurston compactification

A large part of our understanding of \(\operatorname{Mod}_g\) comes from studying its action on the compactified Teichumuller space, and on the Teichumuller boundary.
The Teichumuller space is homeomorphic to an open ball, and it has a beautiful compactification due to Thurston as a closed ball (so the boundary is a sphere).

Let us recall how that goes.
Let \(S\) be the set of isotopy classes of simple closed curves on \(\Sigma_g\).
We map the Teichmuller space \(T_g\) to the infinite projective space \(\mathbf{R}P^S\) by the map
\[ i \colon \mu \mapsto [l_\mu(\gamma) \mid \gamma \in S].\]
The compactification \(\overline T_g\) is the closure of the image of \(T_g\).

The following hold.
1. The map \(i\) is injective and in fact a homeo onto its image.
2. The closure of the image of \(i\) is compact.
3. The closure is homeomorphic to a closed ball.
   The boundary can be interpreted as the space of measured foliations on \(\Sigma_g\).
   A dense subset of the boundary (its "rational points") correspond to "intersection functionals".
   The intersection functional associated to a simple closed curve \(\delta\) is
   \[ h_\delta : \gamma \mapsto |\delta \cap \gamma|.\]
   These \([h_{\delta}]\) appear in the boundray (and are dense in the boundary).

* Thurston compactification for \(\operatorname{Stab}(C_{\Gamma})\):

Since a stability condition gives a metric, many of these ideas have direct analogues.
First, we pick a analogue of the set \(S\).
This will be a subset of the set of objects of \(C_{\Gamma}\).
There is a lot of flexibility here, but a reasonable choice is to take \(S\) to be the set of spherical objects of \(C_{\Gamma}\).
These are the simplest kinds of objects in \(C_{\Gamma}\) in the sense that their endomorphism algebra \(\operatorname{Hom}^{*}(x,x)\) is the smallest possible: 1 dim in degree 0 and 2 and 0 otherwise.

We then have a map
\[ \mathbf{P} \operatorname{Stab} = \operatorname{Stab} / \mathbf{C}  \to \mathbf{P}^S\]
given by
\[ \tau \mapsto [l_\tau(x) \mid x \in S].\]
We then hope for the best!
(The best = all three analogues of Thurston's theorem hold.)

** What can be proved? (AKA: is this a good idea?)
Let \(\Gamma\) be any connected quiver. 

1. The map \(i\) is injective. Homeomorphism?  Not sure.

2. The closure of the image of \(i\) is compact.

3. The boundary contains all "intersection functionals".

   Intersection functional: fix an \(x \in S\).
   Define 
   \[ h_x : y \to \dim \operatorname{Hom}^{*}(x,y).\]

   - Theorem ::  The points \([h_x] \in \mathbf{P}^S\) lie in the closure of the image of \(i\).

   - Proof ::
     Let us recall how the proof goes in Teichmuller theory.
     Fix a simple closed curve \(\delta\) (draw picture).
     Choose any metric \(\mu\).
     Let \(\sigma\) be the Dehn twist in \(\delta\).
     Consider the pull-back metric \(\sigma^{*}(\mu)\).
     Then the length of \(\gamma\) under \(\sigma^{*}(\mu)\) is the length of \(\sigma(\gamma)\) under \(\mu\).
     The curve \(\sigma(\gamma)\) looks like this (draw picture).
     Its length is 
     \[ l(\sigma \gamma) \leq l(\gamma) + l(\delta)\]
     This is accurate if there is exactly one intersection point.
     If there are more, the same local picture holds at each point, and we get
     \[ l(\sigma \gamma) \leq l(\gamma) + h_{\delta}(\gamma) \cdot l(\delta).\]
     If we iterate this, we get
     \[ l_{\sigma^n \mu} (\gamma) \leq l(\gamma) + n h_{\delta}(\gamma) l(\delta).\]
     The key point is that as \(n \to \infty\), the error in the RHS and LHS is negligible compared to \(n\).
     And hence the projective functional \(l_{\sigma^n \mu}\) approaches the intersection functional \([h_{\delta}]\).

     The categorical proof is an exact analogue.
     Fix a spherical object \(x\).
     Let \(\tau\) be a stability condition.
     The analogue of the Dehn twist is the spherical twist \(\sigma_x \colon \mathcal{C} \to \mathcal{C}\).
     It is defined as follows:
     \[ \sigma_x(y) = \operatorname{Cone} (\operatorname{Hom}(x,y) \otimes x \to y).\]
     By definition, we have the exact triangle
     \[ \operatorname{Hom}(x,y) \otimes x \to y \to \sigma_x(y),\]
     which after a shift becomes
     \[ y \to \sigma_x(y) \to \operatorname{Hom}(x,y) \otimes x[1].\]
     By the triangle inequality, this gives
     \[ l_{\sigma^* \tau} (y) \leq l_\tau y + h_x(y) l_\tau x.\]
     And by iterating,
     \[ l_{\sigma^n \tau} (y) \leq l_\tau y + n h_x(y) l_\tau x.\]
     The key again is to prove that the difference is negligible compared to \(n\), and therefore in \(\mathbf{P}^S\), we have
     \[ \lim_{n \to \infty} [l_{\sigma^n \tau}] = [h_x].\]

   In the case of the \(A_n\) quiver, we can prove that the closure of the intersection functionals \([h_x]\) is a sphere.
   The Braid group acts on this sphere by picewise linear maps.
   We do not know that this is precisely the boundary.

   In the \(n = 2\), case, however, we can prove the best possible outcome and obtain a very nice picture.

   Draw the Farey triangulation.
   

* Further questions and remarks
- What is the categorical meaning of the irrational points on the boundary?
  What are categorical measured foliations or laminations?

- \(q\) analogue.
  Is there a \(q\)-analog in geometry?
  
- Bridgeland-Smith / Dmitrov-Haiden-Kontsevich-Katzarkov: may be \(\operatorname{Stab}\) should be thought of as the space of "flat" metrics, instead of the space of "hyperbolic" metrics.
  Then what we are doing is more like a flat analogue of Thurston constrution.
  Have people studied a flat analogue of Thurston's construction?
