#+title: Reading Seminar on Fourier Mukai Transforms in Algebraic Geometry
#+date: 2021 Semester 1

We organised our reading and wrote comments on an anonymous collaborative whiteboard (https://www.mathdown.net/?doc=I7X3CpuNsKa#DbCoh).
We used a Google Jamboard and zoom when we met in person (and zoom).

Below is a transcript of the whiteboard.

* Sections 11.1 and 11.2

- 11.1 :: the proof is clumsy. Use $j_*j^*j_*\cal{F}=j_*\cal{O}\otimes j_*\cal{F}=j_*(j^*j_*\cal{O}\otimes F)$ and then apply (i) to prove the second equality in (ii). And for (iii), use $Hom(j_*\cal{O},j_*\cal{F})=j_*Hom(j^*j_*\cal{O},\cal{F})$ coupled with (i).


* Section 10.2, 10.3
1. In Remark 10.8ii, it is mentioned that the corresponding fact for abelian varieties is deeper. What part of the argument of Cor 10.7 breaks down for abelian varieties? Is it integrality of Mukai vectors?

2. It's a bit odd that 10.3 says nothing about why M is a K3.
   (It's derived equivalent to a K3, hence a K3.)

3. In the proof of 10.10, why does $\phi$ induce an isometry on $H^2$ if $\phi(0,0,1) = \pm(0,0,1)$?

4. Proposition 10.24 seems to say, in particular, that every (?) (-2) Mukai vector is the class of a spherical sheaf.

5. The proof of Lemma 10.6 went a bit quickly for me so it would be nice to talk briefly about it.

6. I found the first part of Section 10.3 to be a very readable explanation of coarse and fine moduli spaces. But I got lost in the second part, so I would like to have a discussion about it.

7. Why is the Kahler cone connected?

* Section 10.1
1. Trivial canonical bundle implies first Chern class is zero?

2. Can there be an isomorphism of K3 surfaces (as complex manifolds) which is not algebraic?



* Sections 9.4, 9.5
1. The digression on page 217 is pretty cool. I'd like to discuss it.

2. 

* Sections 9.1, 9.2, 9.3

1. Proof of 9.19: the paragraph at the top of page 202 is superfluous. 

2. 9.20: as stated the closed point $a\in A$ plays no role. Of course one can reverse the roles of $A$ and $\hat A$, tenroing with line bundles on $\hat A$ and translating by points in $A$. 

3. 9.26: Doesn't seem correct. The commutative square giving the fact that $f:B\to A$ is a homomorphism isn't cartesian, hence there is no reason to expect that the base-change map $f^*m_*(\cal{F}\boxtimes\cal{E})\to m_*(f^*\cal{F}\boxtimes f^*\cal{E})$ should be an isomorphism.
  I think it even fails for skypscraper sheaves.

4. Proof of 9.30: the only place where 9.26 is used is in this proof, more specidically in the sequence on equation in the middle of page 208. In this application $f=\varphi_L^{}$ is an isomorphism, in which case there is no problem. The square in 3. is cartesian.

   Also in the proof of 9.30, I was confused for a long time about the proof of commutativity of the square on page 208, but then realised that for an isomorphism, the push-forward is the same as the pull-back by the inverse.

5. Don't get both remark 9.5.

6. Curiosity: what happens to the translation non-invariant line bundles under the FM transform?

7. Can we look at the SL2 action in the case of an elliptic curve?

* Sections 8.4 and 9.1
1. No need to leave out the proof of 8.42, which follows easily from the isomorphism $Hom_X(i_*\cal{E},i_*\cal{E})\cong Hom_Y(i^*i_*\cal{E},\cal{E})$.

2. 8.45: I did find a proof, but it wasn't quite so trivial. If someone has an easier argument it would be great to see it.

3. Don't get both remark 9.5.


* Sections 8.2 and 8.3

2. Proof of lemma 8.21: Why $p_* (q^* \epsilon^\vee \otimes S^\vee \otimes \omega_X [dim(X)] \cong Hom(p_*(q^* \epsilon \otimes S), \mathcal{O}_X)$?

5. I find the following form of 8.28 easier to understand: Every $F \in D^b(X)$ has a filtration $$ 0 = F_0 \to F_1 \to \cdots \to F_n = F$$ whose "subquotients" are $R\pi_*(F(r)) \otimes \Omega^{-r}(-r)$. Likewise, $F$ also admits a filtration whose "subquotients" are $R\pi_* (F \otimes \Omega^{-r}(-r)) \otimes \mathcal O(r)$. 

4. What is the entire section 8.3 doing?

1. 8.30: there's definitely something wrong in the statement, after all the exact sequence $0\to\Omega(1)\to\cal{O}^{n+1}\to\cal{O}(1)\to0$ gives lots of nonzero maps $\Omega(1)\to\cal{O}$. 
    But no maps from $\mathcal O \to \Omega(1)$! So, may be the sequence should be written the other way round?

3. Esercise 8.5 seems very important; can someone go through or say some words on it?

* Week 8: Section 8.1
1. Here is an example of Example 8.17: Let $X$ be a K3 surface. Then $Y = {\rm Hilb}^n X$ (the Hilbert scheme of $n$ points on $X$) is an algebraic symplectic variety of dimension $2n$. Suppose we have a $(-2)$ curve $C \subset X$. Then we have a $\mathbb P^n \cong  {\rm Hilb^n} C \subset Y$. On $X$, we have a spherical twist $D^b(X) \to D^b(X)$ given by $\mathcal O_C$. On $Y$, we have a $\mathbb P^n$-twist $D^b(Y) \to D^b(Y)$ given by $\mathcal O_{{\rm Hilb}^n C}$.
    1. In general, how you obtain this $(-2)$ curve C? 
       In general, there is no such (-2) curve. But some special K3 surfaces may have one. For example, if you move your K3 surface in a family and it acquires a suitable singularity (of type ADE), then its minimal resolution will be a K3 surface that has (-2) curves.

2. Proof of 8.6: The first isomorphism is because $\mathcal{O}_\Delta$defines an equivalence?

3. Lemma 8.12 and its Corollary 8.13 are both interesting. Can anyone give more insight by illustrating a nice example?

4. I don't understand Remark 8.11. Why isn't the inverse given by the adjoint (whose kernel *is* easily described)?

5. I couldn't do Exercise 8.7.

6. I don't understand 8.10ii and 8.10vi

7. In 8.17, why is H*(X,O_X)=H*(P^n) for an algebraic symplectic variety X? 

* Week 7: Chapter 7
1. Proof of 7.2, step 4: Does not need the spectral sequence, and is in fact better with top/bottom truncations.
2. Proof of 7.2, step 5: "the map $f \colon x \mapsto \mathcal Q_x$ is injective" and hence "$df$ is injective for $x \in X$ generic". I get what he's trying to do, but what are the source and target of $f$? I think one has to use some kind of Hilbert/Quot scheme here to make sense of the target of $f$.
3. Proof of 7.1, step 3: Why the adjunction morphism delta is not trivial then it is surjective? What does is mean by the kernel of delta is concentrated in k(x)?
4. Remark 7.7: Can anyone explain the first isomorphism relating the hom with Fourier-Mikai transform and homw ith the pull-back of the dualizing kernel?
5. Proof of 7.10: Why can we assume H(F)=0?
6. Why /phi_p is an equivalence implies /phi_P_R = /phi_P_L and then P_R = P_L? Don't understand the argument in Corollary 5.21.
7. If time permits or Anand is happy to help, is it possible to illusrate the construction on the intro of Section 7.3 with a simple example? At least we have an example to keep in mind why goong through the propositions in the section.


* Week 5/6: Sections 5.2, chapter 6
1. In 5.2, is the multiplication by $\sqrt{{\rm td}X}$ just a nice formal trick, or is there a deeper explanation?
    1. This particular term appears in commuting the isomorphisms in between Hochschild cohomology and ordinary cohomology?
    2. I don't really understand how the Todd class behaves with respect to push/pull, products, etc. In particular I don't understand the proof of 5.29.

2. I benefited from doing Exercise 5.34.
    2. Do you mind to share it? :)

3. In Remarks 5.25(ii): why are $\text{CH}(X)$ and $K(X)$ isomorphic after tensoring with $\mathbb Q$?

4. Can someone explain why the proof of Proposition 6.1 has to go by way of Fourier-Mukai kernels? Wouldn't it be simpler to argue that the canonical ring R(X) can be expressed as the graded ring of natural transformations $T^n\to T^{n+k}$, where $T=S[-n]$ with $S$ the Serre functor?

5. If we proceed as in the proof of Proposition 6.1 in the book, what is the composition? How do you compose maps $i_*{\mathcal{O}}_X\to i_*\omega_X^k$ and $i_*\mathcal{O}_X\to i_*\omega_X^\ell$?
    1. You tensor the second factor by an appropriate power of $\omega$. In other words, apply an appropriate power + shift of the Serre functor. This gives a composition $i_*\cal{O_X} \to i_*\omega_X^k \to i_*\omega_X^{k+l}$.

6. The proof of $\pi_X^* \omega_X = \pi_Y^* \omega_Y$ (without the $r$-exponent) on page 149 is only sketched. It'll be nice to talk about it.

7. Any updates on Conjecture 6.24?

8. In Lemma 6.11 and Corollary 6.12 there are some liberties taken. The endomorphism ring is k only if the point is closed, but then the result gets applied to points that decidedly aren't closed.


* Week 4: Sections 4.3 (skim) and 5.1
1. Main ideas
   1. Definition of FM transform
   2. Right/left adjoints
   3. Composition
   4. When is a functor a FM transform
   5. Uniqueness of FM kernel for an equivalence 

2. I don't understand the beginning of the proof of 5.23, specifically "Choosing local sections of $\mathcal P$ shows that there is a morphism $X \to Y$ inducing $f$."

   The argument easily shows that, if $p$ is a closed point of $X\times Y$ and $i:p\to X\times Y$ is the close immersion, then $i^*P$ is either zero or 1 dimemnsional. So the sheaf P is locally generated over $\mathcal{O}_{X\times Y}$ by one generator. And then by pulling to $\{x\}\times Y$ one sees that this generates already over $\mathcal{O}_X$. Flatness over $X$ proves that, in a neighborhood of $(x,f(x))$, $P$ is locally free of rank 1 over $\mathcal{O}_X\subset\mathcal{O}_{X\times Y}$. So locally the picture is $\mathcal{O}_X\subset\mathcal{O}_{X\times Y}\to\frac{\mathcal{O}_{X\times Y}}{\mathcal{I}}$ with the composite an isomorphism.

3. Can someone motivate/explain the rationale of Fourier-Mukai transform by illustrating an interesting example or even few of them? Maybe on K3 surfaces/Calabi-Yau manifold?

4. What does it mean by a saturated derived categories in the paragraph after the proof of Prop 5.9 in pg 117?

* Week 3: Sections 4.1 and 4.2 (and possibly 4.3)

1.  Main ideas
    Broad main idea: Canonically extract an algebra A from the category so that the category is "D^b(mod A)"
   1. The Serre functor is *intrinsic* (commutes with every auto-equivalence). 
   2. Categorical characterisation of points.
      - Funny how it fails to characterise the points when $\omega_X = O_X$ (Exercise 4.4).
   3. Categorical characterisation of line bundles ("dual" to points).
    
2. Can Anand explain further on the second point in his email on Monday using an example?  In fact, can you give a more intutive understanding of O(1) and why we can often look at a shift of it O(-n) ? (Hartshorne's definition of twisting sheaf O(1) seems hard to grasp) I can foresee that this ample line bundle is going to come out in discussions frequently, so it would be better to pin it down ealier than later.

3. Proof of Proposition 4.11. By the time one has proved that $F(k(x))=k(y)$ [middle of page 97], one could also observe that $F$ preserves the t-structure. After all $D^b(X)^{\leq0}$ is the subcategory of all $A$ such that $Hom(A,k(x)[m])=0$ for all closed points $x$ and all $m<0$. It follows that $F$ also preserves the heart of the t-structure. And now the fact that $\omega_Y$ is (anti)-ample is just because there exist epimorphisms from direct sums of $\omega_Y^k$ to arbitrary coherent sheaves $S$. 

4. I am already stuck on Exercise 4.4. Help! (Edit: I got unstuck.)

5. Remark 4.7: Is there a characterisation of point-like objects if the canonical bundle is neither ample nor anti-ample? I ask this question even though Huybrechts asks us later to forget about point-like objects beyond this proof, because the remark is tantalising.

6. Last Friday, Anand talked about Cezh complex. Can someone explain what the the forgetting index do in the coboundary map to make it a chain map?

7. Why the skyscraper sheaf/residue field k(x) tensor with the canonical bundle/dualizing sheaf w_X (this is the canonical n-th differential form line bundle?) is isomorphic to k(x)? Side question: skyscraper sheaf k(x) defined on an open set or just a point x.

8. For lemma 4.5, I can't see where the zero hom condition on negative shifts being used.

9. A structure sheaf is a kind of line bundle?

10. I don't understand the last part of the proof of Proposition 4.6 (which aims to show that the cohomology sheaves are supported in dimension 0.)  In particular, I would like to understand why any point-like object in D^b(X) is of codimension dim(X), as asserted in Remark 4.7


* Week 2: Chapter 3 
1. Caution about page 75, line 7: If F and E are quasicoherent then the sheaf Hom(F,E) isn't in general quasicoherent. One needs F to be coherent for this to be true. 
    On page 76, the $R\mathcal Hom$ should go from $D^-(Coh X)^{\rm op} \times D^+(QCoh X) \to D^+(QCoh X)$. In general, all the $D^-(Qcoh)$ in this section should be replaced by $D^-(Coh)$ whenever $R\mathcal Hom$ appears.
    
   (i) Can one explain the reason of replacing Qcoh by Coh with some easy examples? These higher functor properties seems hard to digest without examples in mind.

2. Page 83, the proof of Lemma 3.31: I don't see why "Of course, it suffices to show this for $\mathfrak{a}=\mathfrak{m}$." And the case $\mathfrak{a}=\mathfrak{m}$ should be handled more elegantly, just tensor the exact sequence $0\rightarrow \mathfrak{m}\rightarrow A\rightarrow A/\mathfrak{m}\rightarrow 0$ with the module $M$. Anyway: it's better to just appeal to the local criterion of flatness.

3. Proof of 3.17 could be more direct. With the choice of m, we have a map $F^\bullet \to \mathcal H^m[m]$ compose it with a nonzero map $\mathcal H^m[m] \to k(x)[m]$.

4. Is formula (3.18) true (page 85) with $u^*$ and $v^*$ replaced by $Lu^*$ and $Lv^*$ (for arbitrary $u$)?

5. The statement about cohomology and base change needs a flatness hypothesis ($F$ flat over $Y$). Otherwise, it is false.

6. Why is (3.20) equivalent to (3.19) in the section on Grothendieck-Verdier duality?


* Week 1: Section 3.1 + relevant material from Chapter 1 and Chapter 2

 1. Food for thought: what's an example of $A \subset B$ (abelian subcat of an abelian cat) that is *not thick*?

 2. I believe Proposition 2.42 for $D^+$, but why does it also work for $D^b$? Ah! Truncation.

 3. Remark 1.16 reminded me of Ravi Vakil's mnemonic 'RAPL' (Right Adjoints Preserve Limits). This makes sense because both right adjoints and limits are "trying to approximate an object from below."

 4. How do you think about an exact functor $K(A) \to K(B)$? In particular, why is the inner Hom functor exact (page 50)?

 5. The $RHom$ is tricky!

 6. Exercise 2.27 is suspicious: the claimed result does not seem to be true for $K(\mathcal{A})$ precisely because quasi-isomorphisms need not be invertible.

 7. Why doesn't $QCoh(X)$ have enough projectives?

 8. Do projective objects restrict to projective objects on open sets? What about injective objects?

 9. At first glance, Corollary 3.15 appears to be saying that the category $D^b Coh(X)$ is semisimple, but that's of course not true because $Coh(X)$ is already not semisimple. The catch is that being a direct sum of shifts of cohomology objects is a weaker condition than being a direct sum of simple objects. Apparently the correct word to use for the setting of Corollary 3.15 is "formality".

 10. I think the proofs of 3.8, 3.9, 3.10 are good advertisements for the "cohomology filtration" (and foreshadowing a bit, the Harder-Narasimhan filtration). 

 11. In Ex. 2.27, it is stated that short exact sequences in a category A go to distinguished triangles in K(A). But then in the very next line the proof seems to involve the inverse of a quasi - isomorphism which does not make sense in K(A) ?

 12. It is hard for me to grok the universal property of the derived functor. Can someone decipher it for me?

 13. Does $Qcoh(\mathbb A^2 - 0)$ have projectives?

      It doesn't have enough projectives; you can see this because products aren't exact. For each $n>0$ consider on $\mathbb{A}^2$ the map $\cal{O}\oplus\cal{O}\rightarrow\cal{O}$ given by the matrix $(x^n,y^n)$. The restriction to $\mathbb{A}^2-0$ is surjective, but the restriction of the product over $n$ isn't.

