#+title: Styling
#+author: Anand Deopurkar
#+property: header-args:scss :tangle "css/main.scss" :eval no :mkdirp yes
#+property: header-args:javascript :tangle "js/collapsibility.js" :eval no :mkdirp yes

The CSS is adapted from [[https://github.com/asilata/asilata.github.io/][Asilata Bapat]].

* Colours
We define the colour options for all components of the page.
We use four colours.
- ~canvas~ :: Background colour
- ~canvas-pop~ :: Slightly emphasised canvas colour
- ~writing~ :: Foreground colour
- ~writing-pop~ :: Colour used for "pop"
These are variables.

Now we set some predefined palettes.
Later on we can just include the one we want.
#+begin_src scss :tangle no
  //alifbepe 
  $canvas: #fffdfc;
  $canvas-pop: #c7bba8;
  $writing: #000;
  $writing-pop: #d05a5b;
#+end_src

#+begin_src scss :tangle no
  //autumn 
  $canvas: #fbf6ee;
  $canvas-pop: #fac591;
  $writing: #060000;
  $writing-pop: #f87d5b; 
#+end_src

#+begin_src scss :tangle no
  //eucalyptus-warm 
  $canvas: #fbf6ec;
  $canvas-pop: #dcad67;
  $writing: #1f0e07;
  $writing-pop: #a69b65; 
#+end_src

#+begin_src scss :tangle no
  //eucalyptus-cool 
  $canvas: #f2f3f7;
  $canvas-pop: #c8cad9;
  $writing: #212227;
  $writing-pop: #6a7469;
#+end_src

#+begin_src scss :tangle no
  //winter 
  $canvas: #fcfaf5;
  $canvas-pop: #6badb5;
  $writing: #303821;
  $writing-pop: #6badb5;
#+end_src

#+begin_src scss :tangle no
  //spring 
  $canvas: #fcfaf5;
  $canvas-pop: #88b56b;
  $writing: #303821;
  $writing-pop: #88b56b;
#+end_src

#+begin_src scss :tangle no
  //summer 
  $canvas: #fcfaf5;
  $canvas-pop: #986bb5;
  $writing: #303821;
  $writing-pop: #986bb5;
#+end_src

#+begin_src scss 
  //autumn 
  $canvas: #fcfaf5;
  $canvas-pop: #b5736b;
  $writing: #303821;
  $writing-pop: #b5736b;
#+end_src

* Main CSS
We come to the main part of the CSS code, namely the positioning and layout options, as well as the font options.
** Body
#+begin_src scss
  ,* { color: $writing; }

  html {
      scroll-behavior: smooth;
  }
  body {
      column-rule: 1px solid $canvas-pop;
      background-color: $canvas;
      ::-moz-selection {
          background-color: $canvas-pop;
      }
      ::-selection {
          background-color: $canvas-pop;
      }
      a:hover {
  	color: $writing-pop;
      }
      font-family: sans-serif;
      margin-top: 0em;
      line-height: 1.5em;
      width: 90%;
      max-width: 1080px;
      margin-left: auto;
      margin-right: auto;
  }
#+end_src
** Links
#+begin_src scss
  ,* a {
      text-decoration: underline;
  }
  
#+end_src
** Headings
Headlines
#+begin_src scss
  h1, h2, h3, h4 {
      font-weight: normal;
      display: inline-block;
      line-height: 1.5em;
  }
  h1, h2{
      border-bottom: 0.15em solid $writing-pop;
  }
  h3, h4{
      margin-bottom: 0em;
  }

#+end_src

Collapsible and collapsed headlines.
#+begin_src scss
  .collapsible{
      cursor: pointer;
  }
  .collapsed{
      cursor: pointer;
      &:after {
  	content: '...';
      }
  }
#+end_src


** Lists
#+begin_src scss
  ul, ol{
        padding-left: 1em;
        margin-top: 0em;
        margin-bottom: 0em;
    }
    li {
        margin-top: 0.5em;
        margin-bottom: 0.5em;
    }

  dd {
      p {
  	margin-top: 0em;
      }
  }

  table, tr, th, td, colgroup, tbody {
      border: none;
      border-collapse: collapse;
  }
  td {
      padding: 0.0em 0.5em;
  }
#+end_src


** Figures and pictures
#+begin_src scss
  figure {
      padding: 0em;
      margin: 0em;
  }
  #mypicture {
      border-color: $canvas-pop;
      width: 18em;
      margin-left: auto;
      margin-right: auto;
  }
#+end_src


** Various div classes
Title and intro
#+begin_src scss
  .title {
      line-height: 1.5em;
  }
  .intro {
      column-width: 18em;
      column-gap: 1em;
      margin-left: auto;
      margin-right: auto;
  }
#+end_src

Abstract and quotes
#+begin_src scss
  .abstract {
      border-left: 0.5em solid $canvas-pop;;
      padding-left:0.5em;
  }
  
  .abstract > p:first-of-type::before {
      content: "Abstract.";
      font-weight: bold;
  }
#+end_src


** Table of contents
#+begin_src scss
  #table-of-contents {
      padding-right: 1em;
      margin-right: 1em;
      margin-bottom: 1em;
      display: block;
      h2 {
          display: none;
      }
      ul {
          list-style-type: none;
          padding: 0em;
          margin: 0em;
      }
      li {
          margin-top: 0em;
          margin-bottom: 0.5em;
      }
      a {
  	border-bottom: 0.15em solid $writing-pop;
  	text-decoration: none;
      }
  }
#+end_src

** Footer, preamble, and postamble
#+begin_src scss
  footer {
      color: $canvas-pop;
      border-top: 1px solid $canvas-pop;
      font-size: 80%;
      margin-top:2em;
      padding-top:0.3em;
  }

  #preamble {
      margin-top: 1em;
      a {
  	border-bottom: 0.15em solid $writing-pop;
  	text-decoration: none;
      }
  }

  #postamble {
      border-top: 1px solid $canvas-pop;
      font-size: 80%;
      margin-top: 1em;
      text-align: right;
      column-span: all;
  }
#+end_src

** Mystery
Not sure what this does
#+begin_src scss
  .container::after {
      content: "";
      clear: both;
      display: table;
  }

#+end_src

This styles tables, I guess.
#+begin_src scss
  @mixin alternate-rows($color) {
      table {
          tbody > tr:nth-child(odd){
              background: $color;
          }
      }
  }
#+end_src

** Media queries
Changes for smaller screens and print. 
#+begin_src scss
  @media (max-width: 720px){
      body {
  	font-size: 90%;
  	width: 95%;
      }
  }

  // Print stylesheet
  @media print {
      footer, nav {display:none;}
      width: 100%;
      margin: 0px;
      padding: 0px;
      a:after {
          content: " '(' attr(href) ') '";
      }
  }
#+end_src


* Javascript
:PROPERTIES:
:ID:       aeacc433-b46d-4f38-bdaf-803e879ce98d
:END:
The following script adds collapsible elements.
It works as follows.  Suppose we have a part of the page of the form

Headline
Content

and we wish to fold/unfold Content when headline is clicked.
Then we simply add the class "collapsible" or "collapsed" to Headline.
On clicking the Headline, the javascript will toggle the visibility of Content and also toggle the class name of Headline between "collapsible" and "collapsed".

#+begin_src javascript 
  document.addEventListener("DOMContentLoaded", function () {
      
      // We make all h2 and h3 collapsible/collapsed by default.

      defcollapse = "collapsible"
      if (document.documentElement.clientWidth < 720){
  	defcollapse = "collapsed";
      }
      
      var headlines = document.querySelectorAll(".outline-2 h2, .outline-2 h3");
      for (var i = 0; i < headlines.length; i++){
  	if (!(headlines[i].classList.contains("collapsed") ||
  	     headlines[i].classList.contains("collapsible"))){
  	    headlines[i].classList.add(defcollapse);
  	}
      }

      // The target headline is never collapsed.
      var headlines = document.querySelectorAll(":target");
      for (var i = 0; i < headlines.length; i++) {
  	if (headlines[i].classList.contains("collapsed")){
              headlines[i].classList.remove("collapsed");
  	    headlines[i].classList.add("collapsible");
  	}
      }

      var headlines = document.querySelectorAll(".collapsible");
      for (var i = 0; i < headlines.length; i++) {
          addCollapsiblility(headlines[i], true);
      }

      
      var collapsedHeadlines = document.querySelectorAll(".collapsed");
      for (var i = 0; i < collapsedHeadlines.length; i++) {
          addCollapsiblility(collapsedHeadlines[i], false);
      }
  });

  function addCollapsiblility(headline, visible){
      headline.addEventListener("click", toggleVisibilityOfNext);
      var parentElement = headline.parentElement;
      var childrenElements = parentElement.children;
      var isVisible = visible;

      for (var i = 1; i < childrenElements.length; i++) {
          var content = childrenElements[i];
          if (isVisible) {
              content.style.display = "block";
          } else {
              content.style.display = "none";
          }
      }

      function toggleVisibilityOfNext (){
          if (isVisible){
              headline.classList.remove("collapsible");
              headline.classList.add("collapsed");
              for (var i = 1; i < childrenElements.length; i++) {
                  var content = childrenElements[i];
                  content.style.display = "none";
              }
              isVisible = false;
          } else {
              headline.classList.remove("collapsed");
              headline.classList.add("collapsible");
              for (var i = 1; i < childrenElements.length; i++) {
                  var content = childrenElements[i];
                  content.style.display = "block";
              }
              isVisible = true;
          }
      }
  }
#+end_src

* Tangling etc
Tangle the code from this file and then compile it to css.
#+name: tangle-and-compile
#+begin_src emacs-lisp :results silent :tangle no
  (org-babel-tangle)
  (shell-command "cd css; sassc main.scss main.css")
#+end_src
